// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agynio/api/identity/v1/identity.proto

package identityv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/agynio/e2e/suites/go-core/.gen/go/agynio/api/identity/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IdentityServiceName is the fully-qualified name of the IdentityService service.
	IdentityServiceName = "agynio.api.identity.v1.IdentityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IdentityServiceRegisterIdentityProcedure is the fully-qualified name of the IdentityService's
	// RegisterIdentity RPC.
	IdentityServiceRegisterIdentityProcedure = "/agynio.api.identity.v1.IdentityService/RegisterIdentity"
	// IdentityServiceGetIdentityTypeProcedure is the fully-qualified name of the IdentityService's
	// GetIdentityType RPC.
	IdentityServiceGetIdentityTypeProcedure = "/agynio.api.identity.v1.IdentityService/GetIdentityType"
	// IdentityServiceBatchGetIdentityTypesProcedure is the fully-qualified name of the
	// IdentityService's BatchGetIdentityTypes RPC.
	IdentityServiceBatchGetIdentityTypesProcedure = "/agynio.api.identity.v1.IdentityService/BatchGetIdentityTypes"
	// IdentityServiceSetNicknameProcedure is the fully-qualified name of the IdentityService's
	// SetNickname RPC.
	IdentityServiceSetNicknameProcedure = "/agynio.api.identity.v1.IdentityService/SetNickname"
	// IdentityServiceRemoveNicknameProcedure is the fully-qualified name of the IdentityService's
	// RemoveNickname RPC.
	IdentityServiceRemoveNicknameProcedure = "/agynio.api.identity.v1.IdentityService/RemoveNickname"
	// IdentityServiceResolveNicknameProcedure is the fully-qualified name of the IdentityService's
	// ResolveNickname RPC.
	IdentityServiceResolveNicknameProcedure = "/agynio.api.identity.v1.IdentityService/ResolveNickname"
	// IdentityServiceBatchGetNicknamesProcedure is the fully-qualified name of the IdentityService's
	// BatchGetNicknames RPC.
	IdentityServiceBatchGetNicknamesProcedure = "/agynio.api.identity.v1.IdentityService/BatchGetNicknames"
)

// IdentityServiceClient is a client for the agynio.api.identity.v1.IdentityService service.
type IdentityServiceClient interface {
	// RegisterIdentity stores a new identity ID and its type.
	// Returns ALREADY_EXISTS if the identity_id is already registered.
	RegisterIdentity(context.Context, *connect.Request[v1.RegisterIdentityRequest]) (*connect.Response[v1.RegisterIdentityResponse], error)
	// GetIdentityType returns the type for a single identity ID.
	// Returns NOT_FOUND if the identity_id is unknown.
	GetIdentityType(context.Context, *connect.Request[v1.GetIdentityTypeRequest]) (*connect.Response[v1.GetIdentityTypeResponse], error)
	// BatchGetIdentityTypes returns known identity types for the requested IDs.
	// Unknown identity IDs are omitted from the response.
	BatchGetIdentityTypes(context.Context, *connect.Request[v1.BatchGetIdentityTypesRequest]) (*connect.Response[v1.BatchGetIdentityTypesResponse], error)
	// SetNickname sets or updates the nickname for an identity within an org.
	// Returns ALREADY_EXISTS if the nickname is already taken in the org.
	SetNickname(context.Context, *connect.Request[v1.SetNicknameRequest]) (*connect.Response[v1.SetNicknameResponse], error)
	// RemoveNickname deletes the nickname entry for an identity within an org.
	RemoveNickname(context.Context, *connect.Request[v1.RemoveNicknameRequest]) (*connect.Response[v1.RemoveNicknameResponse], error)
	// ResolveNickname resolves an @nickname within an org to its identity.
	ResolveNickname(context.Context, *connect.Request[v1.ResolveNicknameRequest]) (*connect.Response[v1.ResolveNicknameResponse], error)
	// BatchGetNicknames resolves identity IDs to nicknames within an org.
	// Unknown or unset nicknames are omitted from the response.
	BatchGetNicknames(context.Context, *connect.Request[v1.BatchGetNicknamesRequest]) (*connect.Response[v1.BatchGetNicknamesResponse], error)
}

// NewIdentityServiceClient constructs a client for the agynio.api.identity.v1.IdentityService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIdentityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IdentityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	identityServiceMethods := v1.File_agynio_api_identity_v1_identity_proto.Services().ByName("IdentityService").Methods()
	return &identityServiceClient{
		registerIdentity: connect.NewClient[v1.RegisterIdentityRequest, v1.RegisterIdentityResponse](
			httpClient,
			baseURL+IdentityServiceRegisterIdentityProcedure,
			connect.WithSchema(identityServiceMethods.ByName("RegisterIdentity")),
			connect.WithClientOptions(opts...),
		),
		getIdentityType: connect.NewClient[v1.GetIdentityTypeRequest, v1.GetIdentityTypeResponse](
			httpClient,
			baseURL+IdentityServiceGetIdentityTypeProcedure,
			connect.WithSchema(identityServiceMethods.ByName("GetIdentityType")),
			connect.WithClientOptions(opts...),
		),
		batchGetIdentityTypes: connect.NewClient[v1.BatchGetIdentityTypesRequest, v1.BatchGetIdentityTypesResponse](
			httpClient,
			baseURL+IdentityServiceBatchGetIdentityTypesProcedure,
			connect.WithSchema(identityServiceMethods.ByName("BatchGetIdentityTypes")),
			connect.WithClientOptions(opts...),
		),
		setNickname: connect.NewClient[v1.SetNicknameRequest, v1.SetNicknameResponse](
			httpClient,
			baseURL+IdentityServiceSetNicknameProcedure,
			connect.WithSchema(identityServiceMethods.ByName("SetNickname")),
			connect.WithClientOptions(opts...),
		),
		removeNickname: connect.NewClient[v1.RemoveNicknameRequest, v1.RemoveNicknameResponse](
			httpClient,
			baseURL+IdentityServiceRemoveNicknameProcedure,
			connect.WithSchema(identityServiceMethods.ByName("RemoveNickname")),
			connect.WithClientOptions(opts...),
		),
		resolveNickname: connect.NewClient[v1.ResolveNicknameRequest, v1.ResolveNicknameResponse](
			httpClient,
			baseURL+IdentityServiceResolveNicknameProcedure,
			connect.WithSchema(identityServiceMethods.ByName("ResolveNickname")),
			connect.WithClientOptions(opts...),
		),
		batchGetNicknames: connect.NewClient[v1.BatchGetNicknamesRequest, v1.BatchGetNicknamesResponse](
			httpClient,
			baseURL+IdentityServiceBatchGetNicknamesProcedure,
			connect.WithSchema(identityServiceMethods.ByName("BatchGetNicknames")),
			connect.WithClientOptions(opts...),
		),
	}
}

// identityServiceClient implements IdentityServiceClient.
type identityServiceClient struct {
	registerIdentity      *connect.Client[v1.RegisterIdentityRequest, v1.RegisterIdentityResponse]
	getIdentityType       *connect.Client[v1.GetIdentityTypeRequest, v1.GetIdentityTypeResponse]
	batchGetIdentityTypes *connect.Client[v1.BatchGetIdentityTypesRequest, v1.BatchGetIdentityTypesResponse]
	setNickname           *connect.Client[v1.SetNicknameRequest, v1.SetNicknameResponse]
	removeNickname        *connect.Client[v1.RemoveNicknameRequest, v1.RemoveNicknameResponse]
	resolveNickname       *connect.Client[v1.ResolveNicknameRequest, v1.ResolveNicknameResponse]
	batchGetNicknames     *connect.Client[v1.BatchGetNicknamesRequest, v1.BatchGetNicknamesResponse]
}

// RegisterIdentity calls agynio.api.identity.v1.IdentityService.RegisterIdentity.
func (c *identityServiceClient) RegisterIdentity(ctx context.Context, req *connect.Request[v1.RegisterIdentityRequest]) (*connect.Response[v1.RegisterIdentityResponse], error) {
	return c.registerIdentity.CallUnary(ctx, req)
}

// GetIdentityType calls agynio.api.identity.v1.IdentityService.GetIdentityType.
func (c *identityServiceClient) GetIdentityType(ctx context.Context, req *connect.Request[v1.GetIdentityTypeRequest]) (*connect.Response[v1.GetIdentityTypeResponse], error) {
	return c.getIdentityType.CallUnary(ctx, req)
}

// BatchGetIdentityTypes calls agynio.api.identity.v1.IdentityService.BatchGetIdentityTypes.
func (c *identityServiceClient) BatchGetIdentityTypes(ctx context.Context, req *connect.Request[v1.BatchGetIdentityTypesRequest]) (*connect.Response[v1.BatchGetIdentityTypesResponse], error) {
	return c.batchGetIdentityTypes.CallUnary(ctx, req)
}

// SetNickname calls agynio.api.identity.v1.IdentityService.SetNickname.
func (c *identityServiceClient) SetNickname(ctx context.Context, req *connect.Request[v1.SetNicknameRequest]) (*connect.Response[v1.SetNicknameResponse], error) {
	return c.setNickname.CallUnary(ctx, req)
}

// RemoveNickname calls agynio.api.identity.v1.IdentityService.RemoveNickname.
func (c *identityServiceClient) RemoveNickname(ctx context.Context, req *connect.Request[v1.RemoveNicknameRequest]) (*connect.Response[v1.RemoveNicknameResponse], error) {
	return c.removeNickname.CallUnary(ctx, req)
}

// ResolveNickname calls agynio.api.identity.v1.IdentityService.ResolveNickname.
func (c *identityServiceClient) ResolveNickname(ctx context.Context, req *connect.Request[v1.ResolveNicknameRequest]) (*connect.Response[v1.ResolveNicknameResponse], error) {
	return c.resolveNickname.CallUnary(ctx, req)
}

// BatchGetNicknames calls agynio.api.identity.v1.IdentityService.BatchGetNicknames.
func (c *identityServiceClient) BatchGetNicknames(ctx context.Context, req *connect.Request[v1.BatchGetNicknamesRequest]) (*connect.Response[v1.BatchGetNicknamesResponse], error) {
	return c.batchGetNicknames.CallUnary(ctx, req)
}

// IdentityServiceHandler is an implementation of the agynio.api.identity.v1.IdentityService
// service.
type IdentityServiceHandler interface {
	// RegisterIdentity stores a new identity ID and its type.
	// Returns ALREADY_EXISTS if the identity_id is already registered.
	RegisterIdentity(context.Context, *connect.Request[v1.RegisterIdentityRequest]) (*connect.Response[v1.RegisterIdentityResponse], error)
	// GetIdentityType returns the type for a single identity ID.
	// Returns NOT_FOUND if the identity_id is unknown.
	GetIdentityType(context.Context, *connect.Request[v1.GetIdentityTypeRequest]) (*connect.Response[v1.GetIdentityTypeResponse], error)
	// BatchGetIdentityTypes returns known identity types for the requested IDs.
	// Unknown identity IDs are omitted from the response.
	BatchGetIdentityTypes(context.Context, *connect.Request[v1.BatchGetIdentityTypesRequest]) (*connect.Response[v1.BatchGetIdentityTypesResponse], error)
	// SetNickname sets or updates the nickname for an identity within an org.
	// Returns ALREADY_EXISTS if the nickname is already taken in the org.
	SetNickname(context.Context, *connect.Request[v1.SetNicknameRequest]) (*connect.Response[v1.SetNicknameResponse], error)
	// RemoveNickname deletes the nickname entry for an identity within an org.
	RemoveNickname(context.Context, *connect.Request[v1.RemoveNicknameRequest]) (*connect.Response[v1.RemoveNicknameResponse], error)
	// ResolveNickname resolves an @nickname within an org to its identity.
	ResolveNickname(context.Context, *connect.Request[v1.ResolveNicknameRequest]) (*connect.Response[v1.ResolveNicknameResponse], error)
	// BatchGetNicknames resolves identity IDs to nicknames within an org.
	// Unknown or unset nicknames are omitted from the response.
	BatchGetNicknames(context.Context, *connect.Request[v1.BatchGetNicknamesRequest]) (*connect.Response[v1.BatchGetNicknamesResponse], error)
}

// NewIdentityServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIdentityServiceHandler(svc IdentityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	identityServiceMethods := v1.File_agynio_api_identity_v1_identity_proto.Services().ByName("IdentityService").Methods()
	identityServiceRegisterIdentityHandler := connect.NewUnaryHandler(
		IdentityServiceRegisterIdentityProcedure,
		svc.RegisterIdentity,
		connect.WithSchema(identityServiceMethods.ByName("RegisterIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceGetIdentityTypeHandler := connect.NewUnaryHandler(
		IdentityServiceGetIdentityTypeProcedure,
		svc.GetIdentityType,
		connect.WithSchema(identityServiceMethods.ByName("GetIdentityType")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceBatchGetIdentityTypesHandler := connect.NewUnaryHandler(
		IdentityServiceBatchGetIdentityTypesProcedure,
		svc.BatchGetIdentityTypes,
		connect.WithSchema(identityServiceMethods.ByName("BatchGetIdentityTypes")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceSetNicknameHandler := connect.NewUnaryHandler(
		IdentityServiceSetNicknameProcedure,
		svc.SetNickname,
		connect.WithSchema(identityServiceMethods.ByName("SetNickname")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceRemoveNicknameHandler := connect.NewUnaryHandler(
		IdentityServiceRemoveNicknameProcedure,
		svc.RemoveNickname,
		connect.WithSchema(identityServiceMethods.ByName("RemoveNickname")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceResolveNicknameHandler := connect.NewUnaryHandler(
		IdentityServiceResolveNicknameProcedure,
		svc.ResolveNickname,
		connect.WithSchema(identityServiceMethods.ByName("ResolveNickname")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceBatchGetNicknamesHandler := connect.NewUnaryHandler(
		IdentityServiceBatchGetNicknamesProcedure,
		svc.BatchGetNicknames,
		connect.WithSchema(identityServiceMethods.ByName("BatchGetNicknames")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agynio.api.identity.v1.IdentityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IdentityServiceRegisterIdentityProcedure:
			identityServiceRegisterIdentityHandler.ServeHTTP(w, r)
		case IdentityServiceGetIdentityTypeProcedure:
			identityServiceGetIdentityTypeHandler.ServeHTTP(w, r)
		case IdentityServiceBatchGetIdentityTypesProcedure:
			identityServiceBatchGetIdentityTypesHandler.ServeHTTP(w, r)
		case IdentityServiceSetNicknameProcedure:
			identityServiceSetNicknameHandler.ServeHTTP(w, r)
		case IdentityServiceRemoveNicknameProcedure:
			identityServiceRemoveNicknameHandler.ServeHTTP(w, r)
		case IdentityServiceResolveNicknameProcedure:
			identityServiceResolveNicknameHandler.ServeHTTP(w, r)
		case IdentityServiceBatchGetNicknamesProcedure:
			identityServiceBatchGetNicknamesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIdentityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIdentityServiceHandler struct{}

func (UnimplementedIdentityServiceHandler) RegisterIdentity(context.Context, *connect.Request[v1.RegisterIdentityRequest]) (*connect.Response[v1.RegisterIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.identity.v1.IdentityService.RegisterIdentity is not implemented"))
}

func (UnimplementedIdentityServiceHandler) GetIdentityType(context.Context, *connect.Request[v1.GetIdentityTypeRequest]) (*connect.Response[v1.GetIdentityTypeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.identity.v1.IdentityService.GetIdentityType is not implemented"))
}

func (UnimplementedIdentityServiceHandler) BatchGetIdentityTypes(context.Context, *connect.Request[v1.BatchGetIdentityTypesRequest]) (*connect.Response[v1.BatchGetIdentityTypesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.identity.v1.IdentityService.BatchGetIdentityTypes is not implemented"))
}

func (UnimplementedIdentityServiceHandler) SetNickname(context.Context, *connect.Request[v1.SetNicknameRequest]) (*connect.Response[v1.SetNicknameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.identity.v1.IdentityService.SetNickname is not implemented"))
}

func (UnimplementedIdentityServiceHandler) RemoveNickname(context.Context, *connect.Request[v1.RemoveNicknameRequest]) (*connect.Response[v1.RemoveNicknameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.identity.v1.IdentityService.RemoveNickname is not implemented"))
}

func (UnimplementedIdentityServiceHandler) ResolveNickname(context.Context, *connect.Request[v1.ResolveNicknameRequest]) (*connect.Response[v1.ResolveNicknameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.identity.v1.IdentityService.ResolveNickname is not implemented"))
}

func (UnimplementedIdentityServiceHandler) BatchGetNicknames(context.Context, *connect.Request[v1.BatchGetNicknamesRequest]) (*connect.Response[v1.BatchGetNicknamesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.identity.v1.IdentityService.BatchGetNicknames is not implemented"))
}
