// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: agynio/api/gateway/v1/agents.proto

package gatewayv1

import (
	context "context"
	v1 "github.com/agynio/e2e/suites/go-core/.gen/go/agynio/api/agents/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentsGateway_CreateAgent_FullMethodName                     = "/agynio.api.gateway.v1.AgentsGateway/CreateAgent"
	AgentsGateway_GetAgent_FullMethodName                        = "/agynio.api.gateway.v1.AgentsGateway/GetAgent"
	AgentsGateway_UpdateAgent_FullMethodName                     = "/agynio.api.gateway.v1.AgentsGateway/UpdateAgent"
	AgentsGateway_DeleteAgent_FullMethodName                     = "/agynio.api.gateway.v1.AgentsGateway/DeleteAgent"
	AgentsGateway_ListAgents_FullMethodName                      = "/agynio.api.gateway.v1.AgentsGateway/ListAgents"
	AgentsGateway_CreateVolume_FullMethodName                    = "/agynio.api.gateway.v1.AgentsGateway/CreateVolume"
	AgentsGateway_GetVolume_FullMethodName                       = "/agynio.api.gateway.v1.AgentsGateway/GetVolume"
	AgentsGateway_UpdateVolume_FullMethodName                    = "/agynio.api.gateway.v1.AgentsGateway/UpdateVolume"
	AgentsGateway_DeleteVolume_FullMethodName                    = "/agynio.api.gateway.v1.AgentsGateway/DeleteVolume"
	AgentsGateway_ListVolumes_FullMethodName                     = "/agynio.api.gateway.v1.AgentsGateway/ListVolumes"
	AgentsGateway_CreateVolumeAttachment_FullMethodName          = "/agynio.api.gateway.v1.AgentsGateway/CreateVolumeAttachment"
	AgentsGateway_GetVolumeAttachment_FullMethodName             = "/agynio.api.gateway.v1.AgentsGateway/GetVolumeAttachment"
	AgentsGateway_DeleteVolumeAttachment_FullMethodName          = "/agynio.api.gateway.v1.AgentsGateway/DeleteVolumeAttachment"
	AgentsGateway_ListVolumeAttachments_FullMethodName           = "/agynio.api.gateway.v1.AgentsGateway/ListVolumeAttachments"
	AgentsGateway_CreateMcp_FullMethodName                       = "/agynio.api.gateway.v1.AgentsGateway/CreateMcp"
	AgentsGateway_GetMcp_FullMethodName                          = "/agynio.api.gateway.v1.AgentsGateway/GetMcp"
	AgentsGateway_UpdateMcp_FullMethodName                       = "/agynio.api.gateway.v1.AgentsGateway/UpdateMcp"
	AgentsGateway_DeleteMcp_FullMethodName                       = "/agynio.api.gateway.v1.AgentsGateway/DeleteMcp"
	AgentsGateway_ListMcps_FullMethodName                        = "/agynio.api.gateway.v1.AgentsGateway/ListMcps"
	AgentsGateway_CreateSkill_FullMethodName                     = "/agynio.api.gateway.v1.AgentsGateway/CreateSkill"
	AgentsGateway_GetSkill_FullMethodName                        = "/agynio.api.gateway.v1.AgentsGateway/GetSkill"
	AgentsGateway_UpdateSkill_FullMethodName                     = "/agynio.api.gateway.v1.AgentsGateway/UpdateSkill"
	AgentsGateway_DeleteSkill_FullMethodName                     = "/agynio.api.gateway.v1.AgentsGateway/DeleteSkill"
	AgentsGateway_ListSkills_FullMethodName                      = "/agynio.api.gateway.v1.AgentsGateway/ListSkills"
	AgentsGateway_CreateHook_FullMethodName                      = "/agynio.api.gateway.v1.AgentsGateway/CreateHook"
	AgentsGateway_GetHook_FullMethodName                         = "/agynio.api.gateway.v1.AgentsGateway/GetHook"
	AgentsGateway_UpdateHook_FullMethodName                      = "/agynio.api.gateway.v1.AgentsGateway/UpdateHook"
	AgentsGateway_DeleteHook_FullMethodName                      = "/agynio.api.gateway.v1.AgentsGateway/DeleteHook"
	AgentsGateway_ListHooks_FullMethodName                       = "/agynio.api.gateway.v1.AgentsGateway/ListHooks"
	AgentsGateway_CreateEnv_FullMethodName                       = "/agynio.api.gateway.v1.AgentsGateway/CreateEnv"
	AgentsGateway_GetEnv_FullMethodName                          = "/agynio.api.gateway.v1.AgentsGateway/GetEnv"
	AgentsGateway_UpdateEnv_FullMethodName                       = "/agynio.api.gateway.v1.AgentsGateway/UpdateEnv"
	AgentsGateway_DeleteEnv_FullMethodName                       = "/agynio.api.gateway.v1.AgentsGateway/DeleteEnv"
	AgentsGateway_ListEnvs_FullMethodName                        = "/agynio.api.gateway.v1.AgentsGateway/ListEnvs"
	AgentsGateway_CreateInitScript_FullMethodName                = "/agynio.api.gateway.v1.AgentsGateway/CreateInitScript"
	AgentsGateway_GetInitScript_FullMethodName                   = "/agynio.api.gateway.v1.AgentsGateway/GetInitScript"
	AgentsGateway_UpdateInitScript_FullMethodName                = "/agynio.api.gateway.v1.AgentsGateway/UpdateInitScript"
	AgentsGateway_DeleteInitScript_FullMethodName                = "/agynio.api.gateway.v1.AgentsGateway/DeleteInitScript"
	AgentsGateway_ListInitScripts_FullMethodName                 = "/agynio.api.gateway.v1.AgentsGateway/ListInitScripts"
	AgentsGateway_CreateImagePullSecretAttachment_FullMethodName = "/agynio.api.gateway.v1.AgentsGateway/CreateImagePullSecretAttachment"
	AgentsGateway_GetImagePullSecretAttachment_FullMethodName    = "/agynio.api.gateway.v1.AgentsGateway/GetImagePullSecretAttachment"
	AgentsGateway_DeleteImagePullSecretAttachment_FullMethodName = "/agynio.api.gateway.v1.AgentsGateway/DeleteImagePullSecretAttachment"
	AgentsGateway_ListImagePullSecretAttachments_FullMethodName  = "/agynio.api.gateway.v1.AgentsGateway/ListImagePullSecretAttachments"
)

// AgentsGatewayClient is the client API for AgentsGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentsGatewayClient interface {
	// --- Agents ---
	CreateAgent(ctx context.Context, in *v1.CreateAgentRequest, opts ...grpc.CallOption) (*v1.CreateAgentResponse, error)
	GetAgent(ctx context.Context, in *v1.GetAgentRequest, opts ...grpc.CallOption) (*v1.GetAgentResponse, error)
	UpdateAgent(ctx context.Context, in *v1.UpdateAgentRequest, opts ...grpc.CallOption) (*v1.UpdateAgentResponse, error)
	DeleteAgent(ctx context.Context, in *v1.DeleteAgentRequest, opts ...grpc.CallOption) (*v1.DeleteAgentResponse, error)
	ListAgents(ctx context.Context, in *v1.ListAgentsRequest, opts ...grpc.CallOption) (*v1.ListAgentsResponse, error)
	// --- Volumes ---
	CreateVolume(ctx context.Context, in *v1.CreateVolumeRequest, opts ...grpc.CallOption) (*v1.CreateVolumeResponse, error)
	GetVolume(ctx context.Context, in *v1.GetVolumeRequest, opts ...grpc.CallOption) (*v1.GetVolumeResponse, error)
	UpdateVolume(ctx context.Context, in *v1.UpdateVolumeRequest, opts ...grpc.CallOption) (*v1.UpdateVolumeResponse, error)
	DeleteVolume(ctx context.Context, in *v1.DeleteVolumeRequest, opts ...grpc.CallOption) (*v1.DeleteVolumeResponse, error)
	ListVolumes(ctx context.Context, in *v1.ListVolumesRequest, opts ...grpc.CallOption) (*v1.ListVolumesResponse, error)
	// --- Volume Attachments (no Update) ---
	CreateVolumeAttachment(ctx context.Context, in *v1.CreateVolumeAttachmentRequest, opts ...grpc.CallOption) (*v1.CreateVolumeAttachmentResponse, error)
	GetVolumeAttachment(ctx context.Context, in *v1.GetVolumeAttachmentRequest, opts ...grpc.CallOption) (*v1.GetVolumeAttachmentResponse, error)
	DeleteVolumeAttachment(ctx context.Context, in *v1.DeleteVolumeAttachmentRequest, opts ...grpc.CallOption) (*v1.DeleteVolumeAttachmentResponse, error)
	ListVolumeAttachments(ctx context.Context, in *v1.ListVolumeAttachmentsRequest, opts ...grpc.CallOption) (*v1.ListVolumeAttachmentsResponse, error)
	// --- MCPs ---
	CreateMcp(ctx context.Context, in *v1.CreateMcpRequest, opts ...grpc.CallOption) (*v1.CreateMcpResponse, error)
	GetMcp(ctx context.Context, in *v1.GetMcpRequest, opts ...grpc.CallOption) (*v1.GetMcpResponse, error)
	UpdateMcp(ctx context.Context, in *v1.UpdateMcpRequest, opts ...grpc.CallOption) (*v1.UpdateMcpResponse, error)
	DeleteMcp(ctx context.Context, in *v1.DeleteMcpRequest, opts ...grpc.CallOption) (*v1.DeleteMcpResponse, error)
	ListMcps(ctx context.Context, in *v1.ListMcpsRequest, opts ...grpc.CallOption) (*v1.ListMcpsResponse, error)
	// --- Skills ---
	CreateSkill(ctx context.Context, in *v1.CreateSkillRequest, opts ...grpc.CallOption) (*v1.CreateSkillResponse, error)
	GetSkill(ctx context.Context, in *v1.GetSkillRequest, opts ...grpc.CallOption) (*v1.GetSkillResponse, error)
	UpdateSkill(ctx context.Context, in *v1.UpdateSkillRequest, opts ...grpc.CallOption) (*v1.UpdateSkillResponse, error)
	DeleteSkill(ctx context.Context, in *v1.DeleteSkillRequest, opts ...grpc.CallOption) (*v1.DeleteSkillResponse, error)
	ListSkills(ctx context.Context, in *v1.ListSkillsRequest, opts ...grpc.CallOption) (*v1.ListSkillsResponse, error)
	// --- Hooks ---
	CreateHook(ctx context.Context, in *v1.CreateHookRequest, opts ...grpc.CallOption) (*v1.CreateHookResponse, error)
	GetHook(ctx context.Context, in *v1.GetHookRequest, opts ...grpc.CallOption) (*v1.GetHookResponse, error)
	UpdateHook(ctx context.Context, in *v1.UpdateHookRequest, opts ...grpc.CallOption) (*v1.UpdateHookResponse, error)
	DeleteHook(ctx context.Context, in *v1.DeleteHookRequest, opts ...grpc.CallOption) (*v1.DeleteHookResponse, error)
	ListHooks(ctx context.Context, in *v1.ListHooksRequest, opts ...grpc.CallOption) (*v1.ListHooksResponse, error)
	// --- Envs ---
	CreateEnv(ctx context.Context, in *v1.CreateEnvRequest, opts ...grpc.CallOption) (*v1.CreateEnvResponse, error)
	GetEnv(ctx context.Context, in *v1.GetEnvRequest, opts ...grpc.CallOption) (*v1.GetEnvResponse, error)
	UpdateEnv(ctx context.Context, in *v1.UpdateEnvRequest, opts ...grpc.CallOption) (*v1.UpdateEnvResponse, error)
	DeleteEnv(ctx context.Context, in *v1.DeleteEnvRequest, opts ...grpc.CallOption) (*v1.DeleteEnvResponse, error)
	ListEnvs(ctx context.Context, in *v1.ListEnvsRequest, opts ...grpc.CallOption) (*v1.ListEnvsResponse, error)
	// --- Init Scripts ---
	CreateInitScript(ctx context.Context, in *v1.CreateInitScriptRequest, opts ...grpc.CallOption) (*v1.CreateInitScriptResponse, error)
	GetInitScript(ctx context.Context, in *v1.GetInitScriptRequest, opts ...grpc.CallOption) (*v1.GetInitScriptResponse, error)
	UpdateInitScript(ctx context.Context, in *v1.UpdateInitScriptRequest, opts ...grpc.CallOption) (*v1.UpdateInitScriptResponse, error)
	DeleteInitScript(ctx context.Context, in *v1.DeleteInitScriptRequest, opts ...grpc.CallOption) (*v1.DeleteInitScriptResponse, error)
	ListInitScripts(ctx context.Context, in *v1.ListInitScriptsRequest, opts ...grpc.CallOption) (*v1.ListInitScriptsResponse, error)
	// --- Image Pull Secret Attachments (no Update - immutable) ---
	CreateImagePullSecretAttachment(ctx context.Context, in *v1.CreateImagePullSecretAttachmentRequest, opts ...grpc.CallOption) (*v1.CreateImagePullSecretAttachmentResponse, error)
	GetImagePullSecretAttachment(ctx context.Context, in *v1.GetImagePullSecretAttachmentRequest, opts ...grpc.CallOption) (*v1.GetImagePullSecretAttachmentResponse, error)
	DeleteImagePullSecretAttachment(ctx context.Context, in *v1.DeleteImagePullSecretAttachmentRequest, opts ...grpc.CallOption) (*v1.DeleteImagePullSecretAttachmentResponse, error)
	ListImagePullSecretAttachments(ctx context.Context, in *v1.ListImagePullSecretAttachmentsRequest, opts ...grpc.CallOption) (*v1.ListImagePullSecretAttachmentsResponse, error)
}

type agentsGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentsGatewayClient(cc grpc.ClientConnInterface) AgentsGatewayClient {
	return &agentsGatewayClient{cc}
}

func (c *agentsGatewayClient) CreateAgent(ctx context.Context, in *v1.CreateAgentRequest, opts ...grpc.CallOption) (*v1.CreateAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.CreateAgentResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_CreateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) GetAgent(ctx context.Context, in *v1.GetAgentRequest, opts ...grpc.CallOption) (*v1.GetAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetAgentResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) UpdateAgent(ctx context.Context, in *v1.UpdateAgentRequest, opts ...grpc.CallOption) (*v1.UpdateAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.UpdateAgentResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_UpdateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) DeleteAgent(ctx context.Context, in *v1.DeleteAgentRequest, opts ...grpc.CallOption) (*v1.DeleteAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.DeleteAgentResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_DeleteAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) ListAgents(ctx context.Context, in *v1.ListAgentsRequest, opts ...grpc.CallOption) (*v1.ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListAgentsResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) CreateVolume(ctx context.Context, in *v1.CreateVolumeRequest, opts ...grpc.CallOption) (*v1.CreateVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.CreateVolumeResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_CreateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) GetVolume(ctx context.Context, in *v1.GetVolumeRequest, opts ...grpc.CallOption) (*v1.GetVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetVolumeResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_GetVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) UpdateVolume(ctx context.Context, in *v1.UpdateVolumeRequest, opts ...grpc.CallOption) (*v1.UpdateVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.UpdateVolumeResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_UpdateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) DeleteVolume(ctx context.Context, in *v1.DeleteVolumeRequest, opts ...grpc.CallOption) (*v1.DeleteVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.DeleteVolumeResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_DeleteVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) ListVolumes(ctx context.Context, in *v1.ListVolumesRequest, opts ...grpc.CallOption) (*v1.ListVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListVolumesResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_ListVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) CreateVolumeAttachment(ctx context.Context, in *v1.CreateVolumeAttachmentRequest, opts ...grpc.CallOption) (*v1.CreateVolumeAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.CreateVolumeAttachmentResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_CreateVolumeAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) GetVolumeAttachment(ctx context.Context, in *v1.GetVolumeAttachmentRequest, opts ...grpc.CallOption) (*v1.GetVolumeAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetVolumeAttachmentResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_GetVolumeAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) DeleteVolumeAttachment(ctx context.Context, in *v1.DeleteVolumeAttachmentRequest, opts ...grpc.CallOption) (*v1.DeleteVolumeAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.DeleteVolumeAttachmentResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_DeleteVolumeAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) ListVolumeAttachments(ctx context.Context, in *v1.ListVolumeAttachmentsRequest, opts ...grpc.CallOption) (*v1.ListVolumeAttachmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListVolumeAttachmentsResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_ListVolumeAttachments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) CreateMcp(ctx context.Context, in *v1.CreateMcpRequest, opts ...grpc.CallOption) (*v1.CreateMcpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.CreateMcpResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_CreateMcp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) GetMcp(ctx context.Context, in *v1.GetMcpRequest, opts ...grpc.CallOption) (*v1.GetMcpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetMcpResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_GetMcp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) UpdateMcp(ctx context.Context, in *v1.UpdateMcpRequest, opts ...grpc.CallOption) (*v1.UpdateMcpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.UpdateMcpResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_UpdateMcp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) DeleteMcp(ctx context.Context, in *v1.DeleteMcpRequest, opts ...grpc.CallOption) (*v1.DeleteMcpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.DeleteMcpResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_DeleteMcp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) ListMcps(ctx context.Context, in *v1.ListMcpsRequest, opts ...grpc.CallOption) (*v1.ListMcpsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListMcpsResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_ListMcps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) CreateSkill(ctx context.Context, in *v1.CreateSkillRequest, opts ...grpc.CallOption) (*v1.CreateSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.CreateSkillResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_CreateSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) GetSkill(ctx context.Context, in *v1.GetSkillRequest, opts ...grpc.CallOption) (*v1.GetSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetSkillResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_GetSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) UpdateSkill(ctx context.Context, in *v1.UpdateSkillRequest, opts ...grpc.CallOption) (*v1.UpdateSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.UpdateSkillResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_UpdateSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) DeleteSkill(ctx context.Context, in *v1.DeleteSkillRequest, opts ...grpc.CallOption) (*v1.DeleteSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.DeleteSkillResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_DeleteSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) ListSkills(ctx context.Context, in *v1.ListSkillsRequest, opts ...grpc.CallOption) (*v1.ListSkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListSkillsResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_ListSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) CreateHook(ctx context.Context, in *v1.CreateHookRequest, opts ...grpc.CallOption) (*v1.CreateHookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.CreateHookResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_CreateHook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) GetHook(ctx context.Context, in *v1.GetHookRequest, opts ...grpc.CallOption) (*v1.GetHookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetHookResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_GetHook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) UpdateHook(ctx context.Context, in *v1.UpdateHookRequest, opts ...grpc.CallOption) (*v1.UpdateHookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.UpdateHookResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_UpdateHook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) DeleteHook(ctx context.Context, in *v1.DeleteHookRequest, opts ...grpc.CallOption) (*v1.DeleteHookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.DeleteHookResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_DeleteHook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) ListHooks(ctx context.Context, in *v1.ListHooksRequest, opts ...grpc.CallOption) (*v1.ListHooksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListHooksResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_ListHooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) CreateEnv(ctx context.Context, in *v1.CreateEnvRequest, opts ...grpc.CallOption) (*v1.CreateEnvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.CreateEnvResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_CreateEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) GetEnv(ctx context.Context, in *v1.GetEnvRequest, opts ...grpc.CallOption) (*v1.GetEnvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetEnvResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_GetEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) UpdateEnv(ctx context.Context, in *v1.UpdateEnvRequest, opts ...grpc.CallOption) (*v1.UpdateEnvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.UpdateEnvResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_UpdateEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) DeleteEnv(ctx context.Context, in *v1.DeleteEnvRequest, opts ...grpc.CallOption) (*v1.DeleteEnvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.DeleteEnvResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_DeleteEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) ListEnvs(ctx context.Context, in *v1.ListEnvsRequest, opts ...grpc.CallOption) (*v1.ListEnvsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListEnvsResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_ListEnvs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) CreateInitScript(ctx context.Context, in *v1.CreateInitScriptRequest, opts ...grpc.CallOption) (*v1.CreateInitScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.CreateInitScriptResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_CreateInitScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) GetInitScript(ctx context.Context, in *v1.GetInitScriptRequest, opts ...grpc.CallOption) (*v1.GetInitScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetInitScriptResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_GetInitScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) UpdateInitScript(ctx context.Context, in *v1.UpdateInitScriptRequest, opts ...grpc.CallOption) (*v1.UpdateInitScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.UpdateInitScriptResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_UpdateInitScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) DeleteInitScript(ctx context.Context, in *v1.DeleteInitScriptRequest, opts ...grpc.CallOption) (*v1.DeleteInitScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.DeleteInitScriptResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_DeleteInitScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) ListInitScripts(ctx context.Context, in *v1.ListInitScriptsRequest, opts ...grpc.CallOption) (*v1.ListInitScriptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListInitScriptsResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_ListInitScripts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) CreateImagePullSecretAttachment(ctx context.Context, in *v1.CreateImagePullSecretAttachmentRequest, opts ...grpc.CallOption) (*v1.CreateImagePullSecretAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.CreateImagePullSecretAttachmentResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_CreateImagePullSecretAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) GetImagePullSecretAttachment(ctx context.Context, in *v1.GetImagePullSecretAttachmentRequest, opts ...grpc.CallOption) (*v1.GetImagePullSecretAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetImagePullSecretAttachmentResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_GetImagePullSecretAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) DeleteImagePullSecretAttachment(ctx context.Context, in *v1.DeleteImagePullSecretAttachmentRequest, opts ...grpc.CallOption) (*v1.DeleteImagePullSecretAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.DeleteImagePullSecretAttachmentResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_DeleteImagePullSecretAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsGatewayClient) ListImagePullSecretAttachments(ctx context.Context, in *v1.ListImagePullSecretAttachmentsRequest, opts ...grpc.CallOption) (*v1.ListImagePullSecretAttachmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListImagePullSecretAttachmentsResponse)
	err := c.cc.Invoke(ctx, AgentsGateway_ListImagePullSecretAttachments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentsGatewayServer is the server API for AgentsGateway service.
// All implementations should embed UnimplementedAgentsGatewayServer
// for forward compatibility.
type AgentsGatewayServer interface {
	// --- Agents ---
	CreateAgent(context.Context, *v1.CreateAgentRequest) (*v1.CreateAgentResponse, error)
	GetAgent(context.Context, *v1.GetAgentRequest) (*v1.GetAgentResponse, error)
	UpdateAgent(context.Context, *v1.UpdateAgentRequest) (*v1.UpdateAgentResponse, error)
	DeleteAgent(context.Context, *v1.DeleteAgentRequest) (*v1.DeleteAgentResponse, error)
	ListAgents(context.Context, *v1.ListAgentsRequest) (*v1.ListAgentsResponse, error)
	// --- Volumes ---
	CreateVolume(context.Context, *v1.CreateVolumeRequest) (*v1.CreateVolumeResponse, error)
	GetVolume(context.Context, *v1.GetVolumeRequest) (*v1.GetVolumeResponse, error)
	UpdateVolume(context.Context, *v1.UpdateVolumeRequest) (*v1.UpdateVolumeResponse, error)
	DeleteVolume(context.Context, *v1.DeleteVolumeRequest) (*v1.DeleteVolumeResponse, error)
	ListVolumes(context.Context, *v1.ListVolumesRequest) (*v1.ListVolumesResponse, error)
	// --- Volume Attachments (no Update) ---
	CreateVolumeAttachment(context.Context, *v1.CreateVolumeAttachmentRequest) (*v1.CreateVolumeAttachmentResponse, error)
	GetVolumeAttachment(context.Context, *v1.GetVolumeAttachmentRequest) (*v1.GetVolumeAttachmentResponse, error)
	DeleteVolumeAttachment(context.Context, *v1.DeleteVolumeAttachmentRequest) (*v1.DeleteVolumeAttachmentResponse, error)
	ListVolumeAttachments(context.Context, *v1.ListVolumeAttachmentsRequest) (*v1.ListVolumeAttachmentsResponse, error)
	// --- MCPs ---
	CreateMcp(context.Context, *v1.CreateMcpRequest) (*v1.CreateMcpResponse, error)
	GetMcp(context.Context, *v1.GetMcpRequest) (*v1.GetMcpResponse, error)
	UpdateMcp(context.Context, *v1.UpdateMcpRequest) (*v1.UpdateMcpResponse, error)
	DeleteMcp(context.Context, *v1.DeleteMcpRequest) (*v1.DeleteMcpResponse, error)
	ListMcps(context.Context, *v1.ListMcpsRequest) (*v1.ListMcpsResponse, error)
	// --- Skills ---
	CreateSkill(context.Context, *v1.CreateSkillRequest) (*v1.CreateSkillResponse, error)
	GetSkill(context.Context, *v1.GetSkillRequest) (*v1.GetSkillResponse, error)
	UpdateSkill(context.Context, *v1.UpdateSkillRequest) (*v1.UpdateSkillResponse, error)
	DeleteSkill(context.Context, *v1.DeleteSkillRequest) (*v1.DeleteSkillResponse, error)
	ListSkills(context.Context, *v1.ListSkillsRequest) (*v1.ListSkillsResponse, error)
	// --- Hooks ---
	CreateHook(context.Context, *v1.CreateHookRequest) (*v1.CreateHookResponse, error)
	GetHook(context.Context, *v1.GetHookRequest) (*v1.GetHookResponse, error)
	UpdateHook(context.Context, *v1.UpdateHookRequest) (*v1.UpdateHookResponse, error)
	DeleteHook(context.Context, *v1.DeleteHookRequest) (*v1.DeleteHookResponse, error)
	ListHooks(context.Context, *v1.ListHooksRequest) (*v1.ListHooksResponse, error)
	// --- Envs ---
	CreateEnv(context.Context, *v1.CreateEnvRequest) (*v1.CreateEnvResponse, error)
	GetEnv(context.Context, *v1.GetEnvRequest) (*v1.GetEnvResponse, error)
	UpdateEnv(context.Context, *v1.UpdateEnvRequest) (*v1.UpdateEnvResponse, error)
	DeleteEnv(context.Context, *v1.DeleteEnvRequest) (*v1.DeleteEnvResponse, error)
	ListEnvs(context.Context, *v1.ListEnvsRequest) (*v1.ListEnvsResponse, error)
	// --- Init Scripts ---
	CreateInitScript(context.Context, *v1.CreateInitScriptRequest) (*v1.CreateInitScriptResponse, error)
	GetInitScript(context.Context, *v1.GetInitScriptRequest) (*v1.GetInitScriptResponse, error)
	UpdateInitScript(context.Context, *v1.UpdateInitScriptRequest) (*v1.UpdateInitScriptResponse, error)
	DeleteInitScript(context.Context, *v1.DeleteInitScriptRequest) (*v1.DeleteInitScriptResponse, error)
	ListInitScripts(context.Context, *v1.ListInitScriptsRequest) (*v1.ListInitScriptsResponse, error)
	// --- Image Pull Secret Attachments (no Update - immutable) ---
	CreateImagePullSecretAttachment(context.Context, *v1.CreateImagePullSecretAttachmentRequest) (*v1.CreateImagePullSecretAttachmentResponse, error)
	GetImagePullSecretAttachment(context.Context, *v1.GetImagePullSecretAttachmentRequest) (*v1.GetImagePullSecretAttachmentResponse, error)
	DeleteImagePullSecretAttachment(context.Context, *v1.DeleteImagePullSecretAttachmentRequest) (*v1.DeleteImagePullSecretAttachmentResponse, error)
	ListImagePullSecretAttachments(context.Context, *v1.ListImagePullSecretAttachmentsRequest) (*v1.ListImagePullSecretAttachmentsResponse, error)
}

// UnimplementedAgentsGatewayServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentsGatewayServer struct{}

func (UnimplementedAgentsGatewayServer) CreateAgent(context.Context, *v1.CreateAgentRequest) (*v1.CreateAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAgent not implemented")
}
func (UnimplementedAgentsGatewayServer) GetAgent(context.Context, *v1.GetAgentRequest) (*v1.GetAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedAgentsGatewayServer) UpdateAgent(context.Context, *v1.UpdateAgentRequest) (*v1.UpdateAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAgent not implemented")
}
func (UnimplementedAgentsGatewayServer) DeleteAgent(context.Context, *v1.DeleteAgentRequest) (*v1.DeleteAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAgent not implemented")
}
func (UnimplementedAgentsGatewayServer) ListAgents(context.Context, *v1.ListAgentsRequest) (*v1.ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAgentsGatewayServer) CreateVolume(context.Context, *v1.CreateVolumeRequest) (*v1.CreateVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedAgentsGatewayServer) GetVolume(context.Context, *v1.GetVolumeRequest) (*v1.GetVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVolume not implemented")
}
func (UnimplementedAgentsGatewayServer) UpdateVolume(context.Context, *v1.UpdateVolumeRequest) (*v1.UpdateVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVolume not implemented")
}
func (UnimplementedAgentsGatewayServer) DeleteVolume(context.Context, *v1.DeleteVolumeRequest) (*v1.DeleteVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVolume not implemented")
}
func (UnimplementedAgentsGatewayServer) ListVolumes(context.Context, *v1.ListVolumesRequest) (*v1.ListVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVolumes not implemented")
}
func (UnimplementedAgentsGatewayServer) CreateVolumeAttachment(context.Context, *v1.CreateVolumeAttachmentRequest) (*v1.CreateVolumeAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVolumeAttachment not implemented")
}
func (UnimplementedAgentsGatewayServer) GetVolumeAttachment(context.Context, *v1.GetVolumeAttachmentRequest) (*v1.GetVolumeAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVolumeAttachment not implemented")
}
func (UnimplementedAgentsGatewayServer) DeleteVolumeAttachment(context.Context, *v1.DeleteVolumeAttachmentRequest) (*v1.DeleteVolumeAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVolumeAttachment not implemented")
}
func (UnimplementedAgentsGatewayServer) ListVolumeAttachments(context.Context, *v1.ListVolumeAttachmentsRequest) (*v1.ListVolumeAttachmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVolumeAttachments not implemented")
}
func (UnimplementedAgentsGatewayServer) CreateMcp(context.Context, *v1.CreateMcpRequest) (*v1.CreateMcpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMcp not implemented")
}
func (UnimplementedAgentsGatewayServer) GetMcp(context.Context, *v1.GetMcpRequest) (*v1.GetMcpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMcp not implemented")
}
func (UnimplementedAgentsGatewayServer) UpdateMcp(context.Context, *v1.UpdateMcpRequest) (*v1.UpdateMcpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMcp not implemented")
}
func (UnimplementedAgentsGatewayServer) DeleteMcp(context.Context, *v1.DeleteMcpRequest) (*v1.DeleteMcpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMcp not implemented")
}
func (UnimplementedAgentsGatewayServer) ListMcps(context.Context, *v1.ListMcpsRequest) (*v1.ListMcpsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMcps not implemented")
}
func (UnimplementedAgentsGatewayServer) CreateSkill(context.Context, *v1.CreateSkillRequest) (*v1.CreateSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSkill not implemented")
}
func (UnimplementedAgentsGatewayServer) GetSkill(context.Context, *v1.GetSkillRequest) (*v1.GetSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkill not implemented")
}
func (UnimplementedAgentsGatewayServer) UpdateSkill(context.Context, *v1.UpdateSkillRequest) (*v1.UpdateSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSkill not implemented")
}
func (UnimplementedAgentsGatewayServer) DeleteSkill(context.Context, *v1.DeleteSkillRequest) (*v1.DeleteSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSkill not implemented")
}
func (UnimplementedAgentsGatewayServer) ListSkills(context.Context, *v1.ListSkillsRequest) (*v1.ListSkillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedAgentsGatewayServer) CreateHook(context.Context, *v1.CreateHookRequest) (*v1.CreateHookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateHook not implemented")
}
func (UnimplementedAgentsGatewayServer) GetHook(context.Context, *v1.GetHookRequest) (*v1.GetHookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHook not implemented")
}
func (UnimplementedAgentsGatewayServer) UpdateHook(context.Context, *v1.UpdateHookRequest) (*v1.UpdateHookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateHook not implemented")
}
func (UnimplementedAgentsGatewayServer) DeleteHook(context.Context, *v1.DeleteHookRequest) (*v1.DeleteHookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteHook not implemented")
}
func (UnimplementedAgentsGatewayServer) ListHooks(context.Context, *v1.ListHooksRequest) (*v1.ListHooksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHooks not implemented")
}
func (UnimplementedAgentsGatewayServer) CreateEnv(context.Context, *v1.CreateEnvRequest) (*v1.CreateEnvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEnv not implemented")
}
func (UnimplementedAgentsGatewayServer) GetEnv(context.Context, *v1.GetEnvRequest) (*v1.GetEnvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnv not implemented")
}
func (UnimplementedAgentsGatewayServer) UpdateEnv(context.Context, *v1.UpdateEnvRequest) (*v1.UpdateEnvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEnv not implemented")
}
func (UnimplementedAgentsGatewayServer) DeleteEnv(context.Context, *v1.DeleteEnvRequest) (*v1.DeleteEnvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEnv not implemented")
}
func (UnimplementedAgentsGatewayServer) ListEnvs(context.Context, *v1.ListEnvsRequest) (*v1.ListEnvsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEnvs not implemented")
}
func (UnimplementedAgentsGatewayServer) CreateInitScript(context.Context, *v1.CreateInitScriptRequest) (*v1.CreateInitScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInitScript not implemented")
}
func (UnimplementedAgentsGatewayServer) GetInitScript(context.Context, *v1.GetInitScriptRequest) (*v1.GetInitScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInitScript not implemented")
}
func (UnimplementedAgentsGatewayServer) UpdateInitScript(context.Context, *v1.UpdateInitScriptRequest) (*v1.UpdateInitScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateInitScript not implemented")
}
func (UnimplementedAgentsGatewayServer) DeleteInitScript(context.Context, *v1.DeleteInitScriptRequest) (*v1.DeleteInitScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteInitScript not implemented")
}
func (UnimplementedAgentsGatewayServer) ListInitScripts(context.Context, *v1.ListInitScriptsRequest) (*v1.ListInitScriptsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInitScripts not implemented")
}
func (UnimplementedAgentsGatewayServer) CreateImagePullSecretAttachment(context.Context, *v1.CreateImagePullSecretAttachmentRequest) (*v1.CreateImagePullSecretAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateImagePullSecretAttachment not implemented")
}
func (UnimplementedAgentsGatewayServer) GetImagePullSecretAttachment(context.Context, *v1.GetImagePullSecretAttachmentRequest) (*v1.GetImagePullSecretAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetImagePullSecretAttachment not implemented")
}
func (UnimplementedAgentsGatewayServer) DeleteImagePullSecretAttachment(context.Context, *v1.DeleteImagePullSecretAttachmentRequest) (*v1.DeleteImagePullSecretAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteImagePullSecretAttachment not implemented")
}
func (UnimplementedAgentsGatewayServer) ListImagePullSecretAttachments(context.Context, *v1.ListImagePullSecretAttachmentsRequest) (*v1.ListImagePullSecretAttachmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImagePullSecretAttachments not implemented")
}
func (UnimplementedAgentsGatewayServer) testEmbeddedByValue() {}

// UnsafeAgentsGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentsGatewayServer will
// result in compilation errors.
type UnsafeAgentsGatewayServer interface {
	mustEmbedUnimplementedAgentsGatewayServer()
}

func RegisterAgentsGatewayServer(s grpc.ServiceRegistrar, srv AgentsGatewayServer) {
	// If the following call panics, it indicates UnimplementedAgentsGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentsGateway_ServiceDesc, srv)
}

func _AgentsGateway_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.CreateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_CreateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).CreateAgent(ctx, req.(*v1.CreateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).GetAgent(ctx, req.(*v1.GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_UpdateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UpdateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).UpdateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_UpdateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).UpdateAgent(ctx, req.(*v1.UpdateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_DeleteAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.DeleteAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).DeleteAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_DeleteAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).DeleteAgent(ctx, req.(*v1.DeleteAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).ListAgents(ctx, req.(*v1.ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.CreateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_CreateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).CreateVolume(ctx, req.(*v1.CreateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_GetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).GetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_GetVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).GetVolume(ctx, req.(*v1.GetVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_UpdateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UpdateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).UpdateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_UpdateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).UpdateVolume(ctx, req.(*v1.UpdateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.DeleteVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_DeleteVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).DeleteVolume(ctx, req.(*v1.DeleteVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_ListVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).ListVolumes(ctx, req.(*v1.ListVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_CreateVolumeAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.CreateVolumeAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).CreateVolumeAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_CreateVolumeAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).CreateVolumeAttachment(ctx, req.(*v1.CreateVolumeAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_GetVolumeAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetVolumeAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).GetVolumeAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_GetVolumeAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).GetVolumeAttachment(ctx, req.(*v1.GetVolumeAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_DeleteVolumeAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.DeleteVolumeAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).DeleteVolumeAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_DeleteVolumeAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).DeleteVolumeAttachment(ctx, req.(*v1.DeleteVolumeAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_ListVolumeAttachments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListVolumeAttachmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).ListVolumeAttachments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_ListVolumeAttachments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).ListVolumeAttachments(ctx, req.(*v1.ListVolumeAttachmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_CreateMcp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.CreateMcpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).CreateMcp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_CreateMcp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).CreateMcp(ctx, req.(*v1.CreateMcpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_GetMcp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetMcpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).GetMcp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_GetMcp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).GetMcp(ctx, req.(*v1.GetMcpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_UpdateMcp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UpdateMcpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).UpdateMcp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_UpdateMcp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).UpdateMcp(ctx, req.(*v1.UpdateMcpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_DeleteMcp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.DeleteMcpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).DeleteMcp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_DeleteMcp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).DeleteMcp(ctx, req.(*v1.DeleteMcpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_ListMcps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListMcpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).ListMcps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_ListMcps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).ListMcps(ctx, req.(*v1.ListMcpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_CreateSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.CreateSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).CreateSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_CreateSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).CreateSkill(ctx, req.(*v1.CreateSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_GetSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).GetSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_GetSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).GetSkill(ctx, req.(*v1.GetSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_UpdateSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UpdateSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).UpdateSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_UpdateSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).UpdateSkill(ctx, req.(*v1.UpdateSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_DeleteSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.DeleteSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).DeleteSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_DeleteSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).DeleteSkill(ctx, req.(*v1.DeleteSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).ListSkills(ctx, req.(*v1.ListSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_CreateHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.CreateHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).CreateHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_CreateHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).CreateHook(ctx, req.(*v1.CreateHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_GetHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).GetHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_GetHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).GetHook(ctx, req.(*v1.GetHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_UpdateHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UpdateHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).UpdateHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_UpdateHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).UpdateHook(ctx, req.(*v1.UpdateHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_DeleteHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.DeleteHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).DeleteHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_DeleteHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).DeleteHook(ctx, req.(*v1.DeleteHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_ListHooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListHooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).ListHooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_ListHooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).ListHooks(ctx, req.(*v1.ListHooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_CreateEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.CreateEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).CreateEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_CreateEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).CreateEnv(ctx, req.(*v1.CreateEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_GetEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).GetEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_GetEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).GetEnv(ctx, req.(*v1.GetEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_UpdateEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UpdateEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).UpdateEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_UpdateEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).UpdateEnv(ctx, req.(*v1.UpdateEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_DeleteEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.DeleteEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).DeleteEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_DeleteEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).DeleteEnv(ctx, req.(*v1.DeleteEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_ListEnvs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListEnvsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).ListEnvs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_ListEnvs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).ListEnvs(ctx, req.(*v1.ListEnvsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_CreateInitScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.CreateInitScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).CreateInitScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_CreateInitScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).CreateInitScript(ctx, req.(*v1.CreateInitScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_GetInitScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetInitScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).GetInitScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_GetInitScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).GetInitScript(ctx, req.(*v1.GetInitScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_UpdateInitScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UpdateInitScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).UpdateInitScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_UpdateInitScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).UpdateInitScript(ctx, req.(*v1.UpdateInitScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_DeleteInitScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.DeleteInitScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).DeleteInitScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_DeleteInitScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).DeleteInitScript(ctx, req.(*v1.DeleteInitScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_ListInitScripts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListInitScriptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).ListInitScripts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_ListInitScripts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).ListInitScripts(ctx, req.(*v1.ListInitScriptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_CreateImagePullSecretAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.CreateImagePullSecretAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).CreateImagePullSecretAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_CreateImagePullSecretAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).CreateImagePullSecretAttachment(ctx, req.(*v1.CreateImagePullSecretAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_GetImagePullSecretAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetImagePullSecretAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).GetImagePullSecretAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_GetImagePullSecretAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).GetImagePullSecretAttachment(ctx, req.(*v1.GetImagePullSecretAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_DeleteImagePullSecretAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.DeleteImagePullSecretAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).DeleteImagePullSecretAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_DeleteImagePullSecretAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).DeleteImagePullSecretAttachment(ctx, req.(*v1.DeleteImagePullSecretAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentsGateway_ListImagePullSecretAttachments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListImagePullSecretAttachmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsGatewayServer).ListImagePullSecretAttachments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentsGateway_ListImagePullSecretAttachments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsGatewayServer).ListImagePullSecretAttachments(ctx, req.(*v1.ListImagePullSecretAttachmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentsGateway_ServiceDesc is the grpc.ServiceDesc for AgentsGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentsGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agynio.api.gateway.v1.AgentsGateway",
	HandlerType: (*AgentsGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgent",
			Handler:    _AgentsGateway_CreateAgent_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _AgentsGateway_GetAgent_Handler,
		},
		{
			MethodName: "UpdateAgent",
			Handler:    _AgentsGateway_UpdateAgent_Handler,
		},
		{
			MethodName: "DeleteAgent",
			Handler:    _AgentsGateway_DeleteAgent_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _AgentsGateway_ListAgents_Handler,
		},
		{
			MethodName: "CreateVolume",
			Handler:    _AgentsGateway_CreateVolume_Handler,
		},
		{
			MethodName: "GetVolume",
			Handler:    _AgentsGateway_GetVolume_Handler,
		},
		{
			MethodName: "UpdateVolume",
			Handler:    _AgentsGateway_UpdateVolume_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _AgentsGateway_DeleteVolume_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _AgentsGateway_ListVolumes_Handler,
		},
		{
			MethodName: "CreateVolumeAttachment",
			Handler:    _AgentsGateway_CreateVolumeAttachment_Handler,
		},
		{
			MethodName: "GetVolumeAttachment",
			Handler:    _AgentsGateway_GetVolumeAttachment_Handler,
		},
		{
			MethodName: "DeleteVolumeAttachment",
			Handler:    _AgentsGateway_DeleteVolumeAttachment_Handler,
		},
		{
			MethodName: "ListVolumeAttachments",
			Handler:    _AgentsGateway_ListVolumeAttachments_Handler,
		},
		{
			MethodName: "CreateMcp",
			Handler:    _AgentsGateway_CreateMcp_Handler,
		},
		{
			MethodName: "GetMcp",
			Handler:    _AgentsGateway_GetMcp_Handler,
		},
		{
			MethodName: "UpdateMcp",
			Handler:    _AgentsGateway_UpdateMcp_Handler,
		},
		{
			MethodName: "DeleteMcp",
			Handler:    _AgentsGateway_DeleteMcp_Handler,
		},
		{
			MethodName: "ListMcps",
			Handler:    _AgentsGateway_ListMcps_Handler,
		},
		{
			MethodName: "CreateSkill",
			Handler:    _AgentsGateway_CreateSkill_Handler,
		},
		{
			MethodName: "GetSkill",
			Handler:    _AgentsGateway_GetSkill_Handler,
		},
		{
			MethodName: "UpdateSkill",
			Handler:    _AgentsGateway_UpdateSkill_Handler,
		},
		{
			MethodName: "DeleteSkill",
			Handler:    _AgentsGateway_DeleteSkill_Handler,
		},
		{
			MethodName: "ListSkills",
			Handler:    _AgentsGateway_ListSkills_Handler,
		},
		{
			MethodName: "CreateHook",
			Handler:    _AgentsGateway_CreateHook_Handler,
		},
		{
			MethodName: "GetHook",
			Handler:    _AgentsGateway_GetHook_Handler,
		},
		{
			MethodName: "UpdateHook",
			Handler:    _AgentsGateway_UpdateHook_Handler,
		},
		{
			MethodName: "DeleteHook",
			Handler:    _AgentsGateway_DeleteHook_Handler,
		},
		{
			MethodName: "ListHooks",
			Handler:    _AgentsGateway_ListHooks_Handler,
		},
		{
			MethodName: "CreateEnv",
			Handler:    _AgentsGateway_CreateEnv_Handler,
		},
		{
			MethodName: "GetEnv",
			Handler:    _AgentsGateway_GetEnv_Handler,
		},
		{
			MethodName: "UpdateEnv",
			Handler:    _AgentsGateway_UpdateEnv_Handler,
		},
		{
			MethodName: "DeleteEnv",
			Handler:    _AgentsGateway_DeleteEnv_Handler,
		},
		{
			MethodName: "ListEnvs",
			Handler:    _AgentsGateway_ListEnvs_Handler,
		},
		{
			MethodName: "CreateInitScript",
			Handler:    _AgentsGateway_CreateInitScript_Handler,
		},
		{
			MethodName: "GetInitScript",
			Handler:    _AgentsGateway_GetInitScript_Handler,
		},
		{
			MethodName: "UpdateInitScript",
			Handler:    _AgentsGateway_UpdateInitScript_Handler,
		},
		{
			MethodName: "DeleteInitScript",
			Handler:    _AgentsGateway_DeleteInitScript_Handler,
		},
		{
			MethodName: "ListInitScripts",
			Handler:    _AgentsGateway_ListInitScripts_Handler,
		},
		{
			MethodName: "CreateImagePullSecretAttachment",
			Handler:    _AgentsGateway_CreateImagePullSecretAttachment_Handler,
		},
		{
			MethodName: "GetImagePullSecretAttachment",
			Handler:    _AgentsGateway_GetImagePullSecretAttachment_Handler,
		},
		{
			MethodName: "DeleteImagePullSecretAttachment",
			Handler:    _AgentsGateway_DeleteImagePullSecretAttachment_Handler,
		},
		{
			MethodName: "ListImagePullSecretAttachments",
			Handler:    _AgentsGateway_ListImagePullSecretAttachments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agynio/api/gateway/v1/agents.proto",
}
