// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agynio/api/gateway/v1/llm.proto

package gatewayv1

import (
	v1 "github.com/agynio/e2e/suites/go-core/.gen/go/agynio/api/llm/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_agynio_api_gateway_v1_llm_proto protoreflect.FileDescriptor

const file_agynio_api_gateway_v1_llm_proto_rawDesc = "" +
	"\n" +
	"\x1fagynio/api/gateway/v1/llm.proto\x12\x15agynio.api.gateway.v1\x1a\x1bagynio/api/llm/v1/llm.proto2\xb8\x10\n" +
	"\n" +
	"LLMGateway\x12n\n" +
	"\x11CreateLLMProvider\x12+.agynio.api.llm.v1.CreateLLMProviderRequest\x1a,.agynio.api.llm.v1.CreateLLMProviderResponse\x12e\n" +
	"\x0eGetLLMProvider\x12(.agynio.api.llm.v1.GetLLMProviderRequest\x1a).agynio.api.llm.v1.GetLLMProviderResponse\x12n\n" +
	"\x11UpdateLLMProvider\x12+.agynio.api.llm.v1.UpdateLLMProviderRequest\x1a,.agynio.api.llm.v1.UpdateLLMProviderResponse\x12n\n" +
	"\x11DeleteLLMProvider\x12+.agynio.api.llm.v1.DeleteLLMProviderRequest\x1a,.agynio.api.llm.v1.DeleteLLMProviderResponse\x12k\n" +
	"\x10ListLLMProviders\x12*.agynio.api.llm.v1.ListLLMProvidersRequest\x1a+.agynio.api.llm.v1.ListLLMProvidersResponse\x12\\\n" +
	"\vCreateModel\x12%.agynio.api.llm.v1.CreateModelRequest\x1a&.agynio.api.llm.v1.CreateModelResponse\x12S\n" +
	"\bGetModel\x12\".agynio.api.llm.v1.GetModelRequest\x1a#.agynio.api.llm.v1.GetModelResponse\x12\\\n" +
	"\vUpdateModel\x12%.agynio.api.llm.v1.UpdateModelRequest\x1a&.agynio.api.llm.v1.UpdateModelResponse\x12\\\n" +
	"\vDeleteModel\x12%.agynio.api.llm.v1.DeleteModelRequest\x1a&.agynio.api.llm.v1.DeleteModelResponse\x12Y\n" +
	"\n" +
	"ListModels\x12$.agynio.api.llm.v1.ListModelsRequest\x1a%.agynio.api.llm.v1.ListModelsResponse\x12q\n" +
	"\x12CreateSubscription\x12,.agynio.api.llm.v1.CreateSubscriptionRequest\x1a-.agynio.api.llm.v1.CreateSubscriptionResponse\x12h\n" +
	"\x0fGetSubscription\x12).agynio.api.llm.v1.GetSubscriptionRequest\x1a*.agynio.api.llm.v1.GetSubscriptionResponse\x12q\n" +
	"\x12UpdateSubscription\x12,.agynio.api.llm.v1.UpdateSubscriptionRequest\x1a-.agynio.api.llm.v1.UpdateSubscriptionResponse\x12q\n" +
	"\x12DeleteSubscription\x12,.agynio.api.llm.v1.DeleteSubscriptionRequest\x1a-.agynio.api.llm.v1.DeleteSubscriptionResponse\x12n\n" +
	"\x11ListSubscriptions\x12+.agynio.api.llm.v1.ListSubscriptionsRequest\x1a,.agynio.api.llm.v1.ListSubscriptionsResponse\x12\x8f\x01\n" +
	"\x1cCreateSubscriptionAttachment\x126.agynio.api.llm.v1.CreateSubscriptionAttachmentRequest\x1a7.agynio.api.llm.v1.CreateSubscriptionAttachmentResponse\x12\x8f\x01\n" +
	"\x1cDeleteSubscriptionAttachment\x126.agynio.api.llm.v1.DeleteSubscriptionAttachmentRequest\x1a7.agynio.api.llm.v1.DeleteSubscriptionAttachmentResponse\x12\x8c\x01\n" +
	"\x1bListSubscriptionAttachments\x125.agynio.api.llm.v1.ListSubscriptionAttachmentsRequest\x1a6.agynio.api.llm.v1.ListSubscriptionAttachmentsResponse\x12V\n" +
	"\tTestModel\x12#.agynio.api.llm.v1.TestModelRequest\x1a$.agynio.api.llm.v1.TestModelResponseB\xea\x01\n" +
	"\x19com.agynio.api.gateway.v1B\bLlmProtoP\x01ZLgithub.com/agynio/e2e/suites/go-core/.gen/go/agynio/api/gateway/v1;gatewayv1\xa2\x02\x03AAG\xaa\x02\x15Agynio.Api.Gateway.V1\xca\x02\x15Agynio\\Api\\Gateway\\V1\xe2\x02!Agynio\\Api\\Gateway\\V1\\GPBMetadata\xea\x02\x18Agynio::Api::Gateway::V1b\x06proto3"

var file_agynio_api_gateway_v1_llm_proto_goTypes = []any{
	(*v1.CreateLLMProviderRequest)(nil),             // 0: agynio.api.llm.v1.CreateLLMProviderRequest
	(*v1.GetLLMProviderRequest)(nil),                // 1: agynio.api.llm.v1.GetLLMProviderRequest
	(*v1.UpdateLLMProviderRequest)(nil),             // 2: agynio.api.llm.v1.UpdateLLMProviderRequest
	(*v1.DeleteLLMProviderRequest)(nil),             // 3: agynio.api.llm.v1.DeleteLLMProviderRequest
	(*v1.ListLLMProvidersRequest)(nil),              // 4: agynio.api.llm.v1.ListLLMProvidersRequest
	(*v1.CreateModelRequest)(nil),                   // 5: agynio.api.llm.v1.CreateModelRequest
	(*v1.GetModelRequest)(nil),                      // 6: agynio.api.llm.v1.GetModelRequest
	(*v1.UpdateModelRequest)(nil),                   // 7: agynio.api.llm.v1.UpdateModelRequest
	(*v1.DeleteModelRequest)(nil),                   // 8: agynio.api.llm.v1.DeleteModelRequest
	(*v1.ListModelsRequest)(nil),                    // 9: agynio.api.llm.v1.ListModelsRequest
	(*v1.CreateSubscriptionRequest)(nil),            // 10: agynio.api.llm.v1.CreateSubscriptionRequest
	(*v1.GetSubscriptionRequest)(nil),               // 11: agynio.api.llm.v1.GetSubscriptionRequest
	(*v1.UpdateSubscriptionRequest)(nil),            // 12: agynio.api.llm.v1.UpdateSubscriptionRequest
	(*v1.DeleteSubscriptionRequest)(nil),            // 13: agynio.api.llm.v1.DeleteSubscriptionRequest
	(*v1.ListSubscriptionsRequest)(nil),             // 14: agynio.api.llm.v1.ListSubscriptionsRequest
	(*v1.CreateSubscriptionAttachmentRequest)(nil),  // 15: agynio.api.llm.v1.CreateSubscriptionAttachmentRequest
	(*v1.DeleteSubscriptionAttachmentRequest)(nil),  // 16: agynio.api.llm.v1.DeleteSubscriptionAttachmentRequest
	(*v1.ListSubscriptionAttachmentsRequest)(nil),   // 17: agynio.api.llm.v1.ListSubscriptionAttachmentsRequest
	(*v1.TestModelRequest)(nil),                     // 18: agynio.api.llm.v1.TestModelRequest
	(*v1.CreateLLMProviderResponse)(nil),            // 19: agynio.api.llm.v1.CreateLLMProviderResponse
	(*v1.GetLLMProviderResponse)(nil),               // 20: agynio.api.llm.v1.GetLLMProviderResponse
	(*v1.UpdateLLMProviderResponse)(nil),            // 21: agynio.api.llm.v1.UpdateLLMProviderResponse
	(*v1.DeleteLLMProviderResponse)(nil),            // 22: agynio.api.llm.v1.DeleteLLMProviderResponse
	(*v1.ListLLMProvidersResponse)(nil),             // 23: agynio.api.llm.v1.ListLLMProvidersResponse
	(*v1.CreateModelResponse)(nil),                  // 24: agynio.api.llm.v1.CreateModelResponse
	(*v1.GetModelResponse)(nil),                     // 25: agynio.api.llm.v1.GetModelResponse
	(*v1.UpdateModelResponse)(nil),                  // 26: agynio.api.llm.v1.UpdateModelResponse
	(*v1.DeleteModelResponse)(nil),                  // 27: agynio.api.llm.v1.DeleteModelResponse
	(*v1.ListModelsResponse)(nil),                   // 28: agynio.api.llm.v1.ListModelsResponse
	(*v1.CreateSubscriptionResponse)(nil),           // 29: agynio.api.llm.v1.CreateSubscriptionResponse
	(*v1.GetSubscriptionResponse)(nil),              // 30: agynio.api.llm.v1.GetSubscriptionResponse
	(*v1.UpdateSubscriptionResponse)(nil),           // 31: agynio.api.llm.v1.UpdateSubscriptionResponse
	(*v1.DeleteSubscriptionResponse)(nil),           // 32: agynio.api.llm.v1.DeleteSubscriptionResponse
	(*v1.ListSubscriptionsResponse)(nil),            // 33: agynio.api.llm.v1.ListSubscriptionsResponse
	(*v1.CreateSubscriptionAttachmentResponse)(nil), // 34: agynio.api.llm.v1.CreateSubscriptionAttachmentResponse
	(*v1.DeleteSubscriptionAttachmentResponse)(nil), // 35: agynio.api.llm.v1.DeleteSubscriptionAttachmentResponse
	(*v1.ListSubscriptionAttachmentsResponse)(nil),  // 36: agynio.api.llm.v1.ListSubscriptionAttachmentsResponse
	(*v1.TestModelResponse)(nil),                    // 37: agynio.api.llm.v1.TestModelResponse
}
var file_agynio_api_gateway_v1_llm_proto_depIdxs = []int32{
	0,  // 0: agynio.api.gateway.v1.LLMGateway.CreateLLMProvider:input_type -> agynio.api.llm.v1.CreateLLMProviderRequest
	1,  // 1: agynio.api.gateway.v1.LLMGateway.GetLLMProvider:input_type -> agynio.api.llm.v1.GetLLMProviderRequest
	2,  // 2: agynio.api.gateway.v1.LLMGateway.UpdateLLMProvider:input_type -> agynio.api.llm.v1.UpdateLLMProviderRequest
	3,  // 3: agynio.api.gateway.v1.LLMGateway.DeleteLLMProvider:input_type -> agynio.api.llm.v1.DeleteLLMProviderRequest
	4,  // 4: agynio.api.gateway.v1.LLMGateway.ListLLMProviders:input_type -> agynio.api.llm.v1.ListLLMProvidersRequest
	5,  // 5: agynio.api.gateway.v1.LLMGateway.CreateModel:input_type -> agynio.api.llm.v1.CreateModelRequest
	6,  // 6: agynio.api.gateway.v1.LLMGateway.GetModel:input_type -> agynio.api.llm.v1.GetModelRequest
	7,  // 7: agynio.api.gateway.v1.LLMGateway.UpdateModel:input_type -> agynio.api.llm.v1.UpdateModelRequest
	8,  // 8: agynio.api.gateway.v1.LLMGateway.DeleteModel:input_type -> agynio.api.llm.v1.DeleteModelRequest
	9,  // 9: agynio.api.gateway.v1.LLMGateway.ListModels:input_type -> agynio.api.llm.v1.ListModelsRequest
	10, // 10: agynio.api.gateway.v1.LLMGateway.CreateSubscription:input_type -> agynio.api.llm.v1.CreateSubscriptionRequest
	11, // 11: agynio.api.gateway.v1.LLMGateway.GetSubscription:input_type -> agynio.api.llm.v1.GetSubscriptionRequest
	12, // 12: agynio.api.gateway.v1.LLMGateway.UpdateSubscription:input_type -> agynio.api.llm.v1.UpdateSubscriptionRequest
	13, // 13: agynio.api.gateway.v1.LLMGateway.DeleteSubscription:input_type -> agynio.api.llm.v1.DeleteSubscriptionRequest
	14, // 14: agynio.api.gateway.v1.LLMGateway.ListSubscriptions:input_type -> agynio.api.llm.v1.ListSubscriptionsRequest
	15, // 15: agynio.api.gateway.v1.LLMGateway.CreateSubscriptionAttachment:input_type -> agynio.api.llm.v1.CreateSubscriptionAttachmentRequest
	16, // 16: agynio.api.gateway.v1.LLMGateway.DeleteSubscriptionAttachment:input_type -> agynio.api.llm.v1.DeleteSubscriptionAttachmentRequest
	17, // 17: agynio.api.gateway.v1.LLMGateway.ListSubscriptionAttachments:input_type -> agynio.api.llm.v1.ListSubscriptionAttachmentsRequest
	18, // 18: agynio.api.gateway.v1.LLMGateway.TestModel:input_type -> agynio.api.llm.v1.TestModelRequest
	19, // 19: agynio.api.gateway.v1.LLMGateway.CreateLLMProvider:output_type -> agynio.api.llm.v1.CreateLLMProviderResponse
	20, // 20: agynio.api.gateway.v1.LLMGateway.GetLLMProvider:output_type -> agynio.api.llm.v1.GetLLMProviderResponse
	21, // 21: agynio.api.gateway.v1.LLMGateway.UpdateLLMProvider:output_type -> agynio.api.llm.v1.UpdateLLMProviderResponse
	22, // 22: agynio.api.gateway.v1.LLMGateway.DeleteLLMProvider:output_type -> agynio.api.llm.v1.DeleteLLMProviderResponse
	23, // 23: agynio.api.gateway.v1.LLMGateway.ListLLMProviders:output_type -> agynio.api.llm.v1.ListLLMProvidersResponse
	24, // 24: agynio.api.gateway.v1.LLMGateway.CreateModel:output_type -> agynio.api.llm.v1.CreateModelResponse
	25, // 25: agynio.api.gateway.v1.LLMGateway.GetModel:output_type -> agynio.api.llm.v1.GetModelResponse
	26, // 26: agynio.api.gateway.v1.LLMGateway.UpdateModel:output_type -> agynio.api.llm.v1.UpdateModelResponse
	27, // 27: agynio.api.gateway.v1.LLMGateway.DeleteModel:output_type -> agynio.api.llm.v1.DeleteModelResponse
	28, // 28: agynio.api.gateway.v1.LLMGateway.ListModels:output_type -> agynio.api.llm.v1.ListModelsResponse
	29, // 29: agynio.api.gateway.v1.LLMGateway.CreateSubscription:output_type -> agynio.api.llm.v1.CreateSubscriptionResponse
	30, // 30: agynio.api.gateway.v1.LLMGateway.GetSubscription:output_type -> agynio.api.llm.v1.GetSubscriptionResponse
	31, // 31: agynio.api.gateway.v1.LLMGateway.UpdateSubscription:output_type -> agynio.api.llm.v1.UpdateSubscriptionResponse
	32, // 32: agynio.api.gateway.v1.LLMGateway.DeleteSubscription:output_type -> agynio.api.llm.v1.DeleteSubscriptionResponse
	33, // 33: agynio.api.gateway.v1.LLMGateway.ListSubscriptions:output_type -> agynio.api.llm.v1.ListSubscriptionsResponse
	34, // 34: agynio.api.gateway.v1.LLMGateway.CreateSubscriptionAttachment:output_type -> agynio.api.llm.v1.CreateSubscriptionAttachmentResponse
	35, // 35: agynio.api.gateway.v1.LLMGateway.DeleteSubscriptionAttachment:output_type -> agynio.api.llm.v1.DeleteSubscriptionAttachmentResponse
	36, // 36: agynio.api.gateway.v1.LLMGateway.ListSubscriptionAttachments:output_type -> agynio.api.llm.v1.ListSubscriptionAttachmentsResponse
	37, // 37: agynio.api.gateway.v1.LLMGateway.TestModel:output_type -> agynio.api.llm.v1.TestModelResponse
	19, // [19:38] is the sub-list for method output_type
	0,  // [0:19] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_agynio_api_gateway_v1_llm_proto_init() }
func file_agynio_api_gateway_v1_llm_proto_init() {
	if File_agynio_api_gateway_v1_llm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agynio_api_gateway_v1_llm_proto_rawDesc), len(file_agynio_api_gateway_v1_llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agynio_api_gateway_v1_llm_proto_goTypes,
		DependencyIndexes: file_agynio_api_gateway_v1_llm_proto_depIdxs,
	}.Build()
	File_agynio_api_gateway_v1_llm_proto = out.File
	file_agynio_api_gateway_v1_llm_proto_goTypes = nil
	file_agynio_api_gateway_v1_llm_proto_depIdxs = nil
}
