// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agynio/api/gateway/v1/llm.proto

package gatewayv1

import (
	context "context"
	v1 "github.com/agynio/e2e/suites/go-core/.gen/go/agynio/api/llm/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LLMGateway_CreateLLMProvider_FullMethodName = "/agynio.api.gateway.v1.LLMGateway/CreateLLMProvider"
	LLMGateway_GetLLMProvider_FullMethodName    = "/agynio.api.gateway.v1.LLMGateway/GetLLMProvider"
	LLMGateway_UpdateLLMProvider_FullMethodName = "/agynio.api.gateway.v1.LLMGateway/UpdateLLMProvider"
	LLMGateway_DeleteLLMProvider_FullMethodName = "/agynio.api.gateway.v1.LLMGateway/DeleteLLMProvider"
	LLMGateway_ListLLMProviders_FullMethodName  = "/agynio.api.gateway.v1.LLMGateway/ListLLMProviders"
	LLMGateway_CreateModel_FullMethodName       = "/agynio.api.gateway.v1.LLMGateway/CreateModel"
	LLMGateway_GetModel_FullMethodName          = "/agynio.api.gateway.v1.LLMGateway/GetModel"
	LLMGateway_UpdateModel_FullMethodName       = "/agynio.api.gateway.v1.LLMGateway/UpdateModel"
	LLMGateway_DeleteModel_FullMethodName       = "/agynio.api.gateway.v1.LLMGateway/DeleteModel"
	LLMGateway_ListModels_FullMethodName        = "/agynio.api.gateway.v1.LLMGateway/ListModels"
	LLMGateway_TestModel_FullMethodName         = "/agynio.api.gateway.v1.LLMGateway/TestModel"
)

// LLMGatewayClient is the client API for LLMGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLMGatewayClient interface {
	// --- Providers ---
	CreateLLMProvider(ctx context.Context, in *v1.CreateLLMProviderRequest, opts ...grpc.CallOption) (*v1.CreateLLMProviderResponse, error)
	GetLLMProvider(ctx context.Context, in *v1.GetLLMProviderRequest, opts ...grpc.CallOption) (*v1.GetLLMProviderResponse, error)
	UpdateLLMProvider(ctx context.Context, in *v1.UpdateLLMProviderRequest, opts ...grpc.CallOption) (*v1.UpdateLLMProviderResponse, error)
	DeleteLLMProvider(ctx context.Context, in *v1.DeleteLLMProviderRequest, opts ...grpc.CallOption) (*v1.DeleteLLMProviderResponse, error)
	ListLLMProviders(ctx context.Context, in *v1.ListLLMProvidersRequest, opts ...grpc.CallOption) (*v1.ListLLMProvidersResponse, error)
	// --- Models ---
	CreateModel(ctx context.Context, in *v1.CreateModelRequest, opts ...grpc.CallOption) (*v1.CreateModelResponse, error)
	GetModel(ctx context.Context, in *v1.GetModelRequest, opts ...grpc.CallOption) (*v1.GetModelResponse, error)
	UpdateModel(ctx context.Context, in *v1.UpdateModelRequest, opts ...grpc.CallOption) (*v1.UpdateModelResponse, error)
	DeleteModel(ctx context.Context, in *v1.DeleteModelRequest, opts ...grpc.CallOption) (*v1.DeleteModelResponse, error)
	ListModels(ctx context.Context, in *v1.ListModelsRequest, opts ...grpc.CallOption) (*v1.ListModelsResponse, error)
	// --- Test ---
	TestModel(ctx context.Context, in *v1.TestModelRequest, opts ...grpc.CallOption) (*v1.TestModelResponse, error)
}

type lLMGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMGatewayClient(cc grpc.ClientConnInterface) LLMGatewayClient {
	return &lLMGatewayClient{cc}
}

func (c *lLMGatewayClient) CreateLLMProvider(ctx context.Context, in *v1.CreateLLMProviderRequest, opts ...grpc.CallOption) (*v1.CreateLLMProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.CreateLLMProviderResponse)
	err := c.cc.Invoke(ctx, LLMGateway_CreateLLMProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMGatewayClient) GetLLMProvider(ctx context.Context, in *v1.GetLLMProviderRequest, opts ...grpc.CallOption) (*v1.GetLLMProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetLLMProviderResponse)
	err := c.cc.Invoke(ctx, LLMGateway_GetLLMProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMGatewayClient) UpdateLLMProvider(ctx context.Context, in *v1.UpdateLLMProviderRequest, opts ...grpc.CallOption) (*v1.UpdateLLMProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.UpdateLLMProviderResponse)
	err := c.cc.Invoke(ctx, LLMGateway_UpdateLLMProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMGatewayClient) DeleteLLMProvider(ctx context.Context, in *v1.DeleteLLMProviderRequest, opts ...grpc.CallOption) (*v1.DeleteLLMProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.DeleteLLMProviderResponse)
	err := c.cc.Invoke(ctx, LLMGateway_DeleteLLMProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMGatewayClient) ListLLMProviders(ctx context.Context, in *v1.ListLLMProvidersRequest, opts ...grpc.CallOption) (*v1.ListLLMProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListLLMProvidersResponse)
	err := c.cc.Invoke(ctx, LLMGateway_ListLLMProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMGatewayClient) CreateModel(ctx context.Context, in *v1.CreateModelRequest, opts ...grpc.CallOption) (*v1.CreateModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.CreateModelResponse)
	err := c.cc.Invoke(ctx, LLMGateway_CreateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMGatewayClient) GetModel(ctx context.Context, in *v1.GetModelRequest, opts ...grpc.CallOption) (*v1.GetModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetModelResponse)
	err := c.cc.Invoke(ctx, LLMGateway_GetModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMGatewayClient) UpdateModel(ctx context.Context, in *v1.UpdateModelRequest, opts ...grpc.CallOption) (*v1.UpdateModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.UpdateModelResponse)
	err := c.cc.Invoke(ctx, LLMGateway_UpdateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMGatewayClient) DeleteModel(ctx context.Context, in *v1.DeleteModelRequest, opts ...grpc.CallOption) (*v1.DeleteModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.DeleteModelResponse)
	err := c.cc.Invoke(ctx, LLMGateway_DeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMGatewayClient) ListModels(ctx context.Context, in *v1.ListModelsRequest, opts ...grpc.CallOption) (*v1.ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListModelsResponse)
	err := c.cc.Invoke(ctx, LLMGateway_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMGatewayClient) TestModel(ctx context.Context, in *v1.TestModelRequest, opts ...grpc.CallOption) (*v1.TestModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.TestModelResponse)
	err := c.cc.Invoke(ctx, LLMGateway_TestModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMGatewayServer is the server API for LLMGateway service.
// All implementations should embed UnimplementedLLMGatewayServer
// for forward compatibility.
type LLMGatewayServer interface {
	// --- Providers ---
	CreateLLMProvider(context.Context, *v1.CreateLLMProviderRequest) (*v1.CreateLLMProviderResponse, error)
	GetLLMProvider(context.Context, *v1.GetLLMProviderRequest) (*v1.GetLLMProviderResponse, error)
	UpdateLLMProvider(context.Context, *v1.UpdateLLMProviderRequest) (*v1.UpdateLLMProviderResponse, error)
	DeleteLLMProvider(context.Context, *v1.DeleteLLMProviderRequest) (*v1.DeleteLLMProviderResponse, error)
	ListLLMProviders(context.Context, *v1.ListLLMProvidersRequest) (*v1.ListLLMProvidersResponse, error)
	// --- Models ---
	CreateModel(context.Context, *v1.CreateModelRequest) (*v1.CreateModelResponse, error)
	GetModel(context.Context, *v1.GetModelRequest) (*v1.GetModelResponse, error)
	UpdateModel(context.Context, *v1.UpdateModelRequest) (*v1.UpdateModelResponse, error)
	DeleteModel(context.Context, *v1.DeleteModelRequest) (*v1.DeleteModelResponse, error)
	ListModels(context.Context, *v1.ListModelsRequest) (*v1.ListModelsResponse, error)
	// --- Test ---
	TestModel(context.Context, *v1.TestModelRequest) (*v1.TestModelResponse, error)
}

// UnimplementedLLMGatewayServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLMGatewayServer struct{}

func (UnimplementedLLMGatewayServer) CreateLLMProvider(context.Context, *v1.CreateLLMProviderRequest) (*v1.CreateLLMProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLLMProvider not implemented")
}
func (UnimplementedLLMGatewayServer) GetLLMProvider(context.Context, *v1.GetLLMProviderRequest) (*v1.GetLLMProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLLMProvider not implemented")
}
func (UnimplementedLLMGatewayServer) UpdateLLMProvider(context.Context, *v1.UpdateLLMProviderRequest) (*v1.UpdateLLMProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLLMProvider not implemented")
}
func (UnimplementedLLMGatewayServer) DeleteLLMProvider(context.Context, *v1.DeleteLLMProviderRequest) (*v1.DeleteLLMProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLLMProvider not implemented")
}
func (UnimplementedLLMGatewayServer) ListLLMProviders(context.Context, *v1.ListLLMProvidersRequest) (*v1.ListLLMProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLLMProviders not implemented")
}
func (UnimplementedLLMGatewayServer) CreateModel(context.Context, *v1.CreateModelRequest) (*v1.CreateModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateModel not implemented")
}
func (UnimplementedLLMGatewayServer) GetModel(context.Context, *v1.GetModelRequest) (*v1.GetModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModel not implemented")
}
func (UnimplementedLLMGatewayServer) UpdateModel(context.Context, *v1.UpdateModelRequest) (*v1.UpdateModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateModel not implemented")
}
func (UnimplementedLLMGatewayServer) DeleteModel(context.Context, *v1.DeleteModelRequest) (*v1.DeleteModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteModel not implemented")
}
func (UnimplementedLLMGatewayServer) ListModels(context.Context, *v1.ListModelsRequest) (*v1.ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedLLMGatewayServer) TestModel(context.Context, *v1.TestModelRequest) (*v1.TestModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestModel not implemented")
}
func (UnimplementedLLMGatewayServer) testEmbeddedByValue() {}

// UnsafeLLMGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMGatewayServer will
// result in compilation errors.
type UnsafeLLMGatewayServer interface {
	mustEmbedUnimplementedLLMGatewayServer()
}

func RegisterLLMGatewayServer(s grpc.ServiceRegistrar, srv LLMGatewayServer) {
	// If the following call panics, it indicates UnimplementedLLMGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLMGateway_ServiceDesc, srv)
}

func _LLMGateway_CreateLLMProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.CreateLLMProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMGatewayServer).CreateLLMProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMGateway_CreateLLMProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMGatewayServer).CreateLLMProvider(ctx, req.(*v1.CreateLLMProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMGateway_GetLLMProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetLLMProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMGatewayServer).GetLLMProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMGateway_GetLLMProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMGatewayServer).GetLLMProvider(ctx, req.(*v1.GetLLMProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMGateway_UpdateLLMProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UpdateLLMProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMGatewayServer).UpdateLLMProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMGateway_UpdateLLMProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMGatewayServer).UpdateLLMProvider(ctx, req.(*v1.UpdateLLMProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMGateway_DeleteLLMProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.DeleteLLMProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMGatewayServer).DeleteLLMProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMGateway_DeleteLLMProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMGatewayServer).DeleteLLMProvider(ctx, req.(*v1.DeleteLLMProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMGateway_ListLLMProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListLLMProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMGatewayServer).ListLLMProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMGateway_ListLLMProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMGatewayServer).ListLLMProviders(ctx, req.(*v1.ListLLMProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMGateway_CreateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.CreateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMGatewayServer).CreateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMGateway_CreateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMGatewayServer).CreateModel(ctx, req.(*v1.CreateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMGateway_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMGatewayServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMGateway_GetModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMGatewayServer).GetModel(ctx, req.(*v1.GetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMGateway_UpdateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UpdateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMGatewayServer).UpdateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMGateway_UpdateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMGatewayServer).UpdateModel(ctx, req.(*v1.UpdateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMGateway_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.DeleteModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMGatewayServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMGateway_DeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMGatewayServer).DeleteModel(ctx, req.(*v1.DeleteModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMGateway_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMGatewayServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMGateway_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMGatewayServer).ListModels(ctx, req.(*v1.ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMGateway_TestModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.TestModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMGatewayServer).TestModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMGateway_TestModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMGatewayServer).TestModel(ctx, req.(*v1.TestModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLMGateway_ServiceDesc is the grpc.ServiceDesc for LLMGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agynio.api.gateway.v1.LLMGateway",
	HandlerType: (*LLMGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLLMProvider",
			Handler:    _LLMGateway_CreateLLMProvider_Handler,
		},
		{
			MethodName: "GetLLMProvider",
			Handler:    _LLMGateway_GetLLMProvider_Handler,
		},
		{
			MethodName: "UpdateLLMProvider",
			Handler:    _LLMGateway_UpdateLLMProvider_Handler,
		},
		{
			MethodName: "DeleteLLMProvider",
			Handler:    _LLMGateway_DeleteLLMProvider_Handler,
		},
		{
			MethodName: "ListLLMProviders",
			Handler:    _LLMGateway_ListLLMProviders_Handler,
		},
		{
			MethodName: "CreateModel",
			Handler:    _LLMGateway_CreateModel_Handler,
		},
		{
			MethodName: "GetModel",
			Handler:    _LLMGateway_GetModel_Handler,
		},
		{
			MethodName: "UpdateModel",
			Handler:    _LLMGateway_UpdateModel_Handler,
		},
		{
			MethodName: "DeleteModel",
			Handler:    _LLMGateway_DeleteModel_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _LLMGateway_ListModels_Handler,
		},
		{
			MethodName: "TestModel",
			Handler:    _LLMGateway_TestModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agynio/api/gateway/v1/llm.proto",
}
