// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agynio/api/gateway/v1/agents.proto

package gatewayv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/agynio/e2e/suites/go-core/.gen/go/agynio/api/agents/v1"
	v11 "github.com/agynio/e2e/suites/go-core/.gen/go/agynio/api/gateway/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentsGatewayName is the fully-qualified name of the AgentsGateway service.
	AgentsGatewayName = "agynio.api.gateway.v1.AgentsGateway"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentsGatewayCreateAgentProcedure is the fully-qualified name of the AgentsGateway's CreateAgent
	// RPC.
	AgentsGatewayCreateAgentProcedure = "/agynio.api.gateway.v1.AgentsGateway/CreateAgent"
	// AgentsGatewayGetAgentProcedure is the fully-qualified name of the AgentsGateway's GetAgent RPC.
	AgentsGatewayGetAgentProcedure = "/agynio.api.gateway.v1.AgentsGateway/GetAgent"
	// AgentsGatewayUpdateAgentProcedure is the fully-qualified name of the AgentsGateway's UpdateAgent
	// RPC.
	AgentsGatewayUpdateAgentProcedure = "/agynio.api.gateway.v1.AgentsGateway/UpdateAgent"
	// AgentsGatewayDeleteAgentProcedure is the fully-qualified name of the AgentsGateway's DeleteAgent
	// RPC.
	AgentsGatewayDeleteAgentProcedure = "/agynio.api.gateway.v1.AgentsGateway/DeleteAgent"
	// AgentsGatewayListAgentsProcedure is the fully-qualified name of the AgentsGateway's ListAgents
	// RPC.
	AgentsGatewayListAgentsProcedure = "/agynio.api.gateway.v1.AgentsGateway/ListAgents"
	// AgentsGatewayCreateVolumeProcedure is the fully-qualified name of the AgentsGateway's
	// CreateVolume RPC.
	AgentsGatewayCreateVolumeProcedure = "/agynio.api.gateway.v1.AgentsGateway/CreateVolume"
	// AgentsGatewayGetVolumeProcedure is the fully-qualified name of the AgentsGateway's GetVolume RPC.
	AgentsGatewayGetVolumeProcedure = "/agynio.api.gateway.v1.AgentsGateway/GetVolume"
	// AgentsGatewayUpdateVolumeProcedure is the fully-qualified name of the AgentsGateway's
	// UpdateVolume RPC.
	AgentsGatewayUpdateVolumeProcedure = "/agynio.api.gateway.v1.AgentsGateway/UpdateVolume"
	// AgentsGatewayDeleteVolumeProcedure is the fully-qualified name of the AgentsGateway's
	// DeleteVolume RPC.
	AgentsGatewayDeleteVolumeProcedure = "/agynio.api.gateway.v1.AgentsGateway/DeleteVolume"
	// AgentsGatewayListVolumesProcedure is the fully-qualified name of the AgentsGateway's ListVolumes
	// RPC.
	AgentsGatewayListVolumesProcedure = "/agynio.api.gateway.v1.AgentsGateway/ListVolumes"
	// AgentsGatewayCreateVolumeAttachmentProcedure is the fully-qualified name of the AgentsGateway's
	// CreateVolumeAttachment RPC.
	AgentsGatewayCreateVolumeAttachmentProcedure = "/agynio.api.gateway.v1.AgentsGateway/CreateVolumeAttachment"
	// AgentsGatewayGetVolumeAttachmentProcedure is the fully-qualified name of the AgentsGateway's
	// GetVolumeAttachment RPC.
	AgentsGatewayGetVolumeAttachmentProcedure = "/agynio.api.gateway.v1.AgentsGateway/GetVolumeAttachment"
	// AgentsGatewayDeleteVolumeAttachmentProcedure is the fully-qualified name of the AgentsGateway's
	// DeleteVolumeAttachment RPC.
	AgentsGatewayDeleteVolumeAttachmentProcedure = "/agynio.api.gateway.v1.AgentsGateway/DeleteVolumeAttachment"
	// AgentsGatewayListVolumeAttachmentsProcedure is the fully-qualified name of the AgentsGateway's
	// ListVolumeAttachments RPC.
	AgentsGatewayListVolumeAttachmentsProcedure = "/agynio.api.gateway.v1.AgentsGateway/ListVolumeAttachments"
	// AgentsGatewayCreateMcpProcedure is the fully-qualified name of the AgentsGateway's CreateMcp RPC.
	AgentsGatewayCreateMcpProcedure = "/agynio.api.gateway.v1.AgentsGateway/CreateMcp"
	// AgentsGatewayGetMcpProcedure is the fully-qualified name of the AgentsGateway's GetMcp RPC.
	AgentsGatewayGetMcpProcedure = "/agynio.api.gateway.v1.AgentsGateway/GetMcp"
	// AgentsGatewayUpdateMcpProcedure is the fully-qualified name of the AgentsGateway's UpdateMcp RPC.
	AgentsGatewayUpdateMcpProcedure = "/agynio.api.gateway.v1.AgentsGateway/UpdateMcp"
	// AgentsGatewayDeleteMcpProcedure is the fully-qualified name of the AgentsGateway's DeleteMcp RPC.
	AgentsGatewayDeleteMcpProcedure = "/agynio.api.gateway.v1.AgentsGateway/DeleteMcp"
	// AgentsGatewayListMcpsProcedure is the fully-qualified name of the AgentsGateway's ListMcps RPC.
	AgentsGatewayListMcpsProcedure = "/agynio.api.gateway.v1.AgentsGateway/ListMcps"
	// AgentsGatewayCreateSkillProcedure is the fully-qualified name of the AgentsGateway's CreateSkill
	// RPC.
	AgentsGatewayCreateSkillProcedure = "/agynio.api.gateway.v1.AgentsGateway/CreateSkill"
	// AgentsGatewayGetSkillProcedure is the fully-qualified name of the AgentsGateway's GetSkill RPC.
	AgentsGatewayGetSkillProcedure = "/agynio.api.gateway.v1.AgentsGateway/GetSkill"
	// AgentsGatewayUpdateSkillProcedure is the fully-qualified name of the AgentsGateway's UpdateSkill
	// RPC.
	AgentsGatewayUpdateSkillProcedure = "/agynio.api.gateway.v1.AgentsGateway/UpdateSkill"
	// AgentsGatewayDeleteSkillProcedure is the fully-qualified name of the AgentsGateway's DeleteSkill
	// RPC.
	AgentsGatewayDeleteSkillProcedure = "/agynio.api.gateway.v1.AgentsGateway/DeleteSkill"
	// AgentsGatewayListSkillsProcedure is the fully-qualified name of the AgentsGateway's ListSkills
	// RPC.
	AgentsGatewayListSkillsProcedure = "/agynio.api.gateway.v1.AgentsGateway/ListSkills"
	// AgentsGatewayCreateHookProcedure is the fully-qualified name of the AgentsGateway's CreateHook
	// RPC.
	AgentsGatewayCreateHookProcedure = "/agynio.api.gateway.v1.AgentsGateway/CreateHook"
	// AgentsGatewayGetHookProcedure is the fully-qualified name of the AgentsGateway's GetHook RPC.
	AgentsGatewayGetHookProcedure = "/agynio.api.gateway.v1.AgentsGateway/GetHook"
	// AgentsGatewayUpdateHookProcedure is the fully-qualified name of the AgentsGateway's UpdateHook
	// RPC.
	AgentsGatewayUpdateHookProcedure = "/agynio.api.gateway.v1.AgentsGateway/UpdateHook"
	// AgentsGatewayDeleteHookProcedure is the fully-qualified name of the AgentsGateway's DeleteHook
	// RPC.
	AgentsGatewayDeleteHookProcedure = "/agynio.api.gateway.v1.AgentsGateway/DeleteHook"
	// AgentsGatewayListHooksProcedure is the fully-qualified name of the AgentsGateway's ListHooks RPC.
	AgentsGatewayListHooksProcedure = "/agynio.api.gateway.v1.AgentsGateway/ListHooks"
	// AgentsGatewayCreateEnvProcedure is the fully-qualified name of the AgentsGateway's CreateEnv RPC.
	AgentsGatewayCreateEnvProcedure = "/agynio.api.gateway.v1.AgentsGateway/CreateEnv"
	// AgentsGatewayGetEnvProcedure is the fully-qualified name of the AgentsGateway's GetEnv RPC.
	AgentsGatewayGetEnvProcedure = "/agynio.api.gateway.v1.AgentsGateway/GetEnv"
	// AgentsGatewayUpdateEnvProcedure is the fully-qualified name of the AgentsGateway's UpdateEnv RPC.
	AgentsGatewayUpdateEnvProcedure = "/agynio.api.gateway.v1.AgentsGateway/UpdateEnv"
	// AgentsGatewayDeleteEnvProcedure is the fully-qualified name of the AgentsGateway's DeleteEnv RPC.
	AgentsGatewayDeleteEnvProcedure = "/agynio.api.gateway.v1.AgentsGateway/DeleteEnv"
	// AgentsGatewayListEnvsProcedure is the fully-qualified name of the AgentsGateway's ListEnvs RPC.
	AgentsGatewayListEnvsProcedure = "/agynio.api.gateway.v1.AgentsGateway/ListEnvs"
	// AgentsGatewayCreateInitScriptProcedure is the fully-qualified name of the AgentsGateway's
	// CreateInitScript RPC.
	AgentsGatewayCreateInitScriptProcedure = "/agynio.api.gateway.v1.AgentsGateway/CreateInitScript"
	// AgentsGatewayGetInitScriptProcedure is the fully-qualified name of the AgentsGateway's
	// GetInitScript RPC.
	AgentsGatewayGetInitScriptProcedure = "/agynio.api.gateway.v1.AgentsGateway/GetInitScript"
	// AgentsGatewayUpdateInitScriptProcedure is the fully-qualified name of the AgentsGateway's
	// UpdateInitScript RPC.
	AgentsGatewayUpdateInitScriptProcedure = "/agynio.api.gateway.v1.AgentsGateway/UpdateInitScript"
	// AgentsGatewayDeleteInitScriptProcedure is the fully-qualified name of the AgentsGateway's
	// DeleteInitScript RPC.
	AgentsGatewayDeleteInitScriptProcedure = "/agynio.api.gateway.v1.AgentsGateway/DeleteInitScript"
	// AgentsGatewayListInitScriptsProcedure is the fully-qualified name of the AgentsGateway's
	// ListInitScripts RPC.
	AgentsGatewayListInitScriptsProcedure = "/agynio.api.gateway.v1.AgentsGateway/ListInitScripts"
	// AgentsGatewayCreateImagePullSecretAttachmentProcedure is the fully-qualified name of the
	// AgentsGateway's CreateImagePullSecretAttachment RPC.
	AgentsGatewayCreateImagePullSecretAttachmentProcedure = "/agynio.api.gateway.v1.AgentsGateway/CreateImagePullSecretAttachment"
	// AgentsGatewayGetImagePullSecretAttachmentProcedure is the fully-qualified name of the
	// AgentsGateway's GetImagePullSecretAttachment RPC.
	AgentsGatewayGetImagePullSecretAttachmentProcedure = "/agynio.api.gateway.v1.AgentsGateway/GetImagePullSecretAttachment"
	// AgentsGatewayDeleteImagePullSecretAttachmentProcedure is the fully-qualified name of the
	// AgentsGateway's DeleteImagePullSecretAttachment RPC.
	AgentsGatewayDeleteImagePullSecretAttachmentProcedure = "/agynio.api.gateway.v1.AgentsGateway/DeleteImagePullSecretAttachment"
	// AgentsGatewayListImagePullSecretAttachmentsProcedure is the fully-qualified name of the
	// AgentsGateway's ListImagePullSecretAttachments RPC.
	AgentsGatewayListImagePullSecretAttachmentsProcedure = "/agynio.api.gateway.v1.AgentsGateway/ListImagePullSecretAttachments"
)

// AgentsGatewayClient is a client for the agynio.api.gateway.v1.AgentsGateway service.
type AgentsGatewayClient interface {
	// --- Agents ---
	CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error)
	GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error)
	UpdateAgent(context.Context, *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.UpdateAgentResponse], error)
	DeleteAgent(context.Context, *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[v1.DeleteAgentResponse], error)
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	// --- Volumes ---
	CreateVolume(context.Context, *connect.Request[v1.CreateVolumeRequest]) (*connect.Response[v1.CreateVolumeResponse], error)
	GetVolume(context.Context, *connect.Request[v1.GetVolumeRequest]) (*connect.Response[v1.GetVolumeResponse], error)
	UpdateVolume(context.Context, *connect.Request[v1.UpdateVolumeRequest]) (*connect.Response[v1.UpdateVolumeResponse], error)
	DeleteVolume(context.Context, *connect.Request[v1.DeleteVolumeRequest]) (*connect.Response[v1.DeleteVolumeResponse], error)
	ListVolumes(context.Context, *connect.Request[v1.ListVolumesRequest]) (*connect.Response[v1.ListVolumesResponse], error)
	// --- Volume Attachments (no Update) ---
	CreateVolumeAttachment(context.Context, *connect.Request[v1.CreateVolumeAttachmentRequest]) (*connect.Response[v1.CreateVolumeAttachmentResponse], error)
	GetVolumeAttachment(context.Context, *connect.Request[v1.GetVolumeAttachmentRequest]) (*connect.Response[v1.GetVolumeAttachmentResponse], error)
	DeleteVolumeAttachment(context.Context, *connect.Request[v1.DeleteVolumeAttachmentRequest]) (*connect.Response[v1.DeleteVolumeAttachmentResponse], error)
	ListVolumeAttachments(context.Context, *connect.Request[v1.ListVolumeAttachmentsRequest]) (*connect.Response[v1.ListVolumeAttachmentsResponse], error)
	// --- MCPs ---
	CreateMcp(context.Context, *connect.Request[v1.CreateMcpRequest]) (*connect.Response[v1.CreateMcpResponse], error)
	GetMcp(context.Context, *connect.Request[v1.GetMcpRequest]) (*connect.Response[v1.GetMcpResponse], error)
	UpdateMcp(context.Context, *connect.Request[v1.UpdateMcpRequest]) (*connect.Response[v1.UpdateMcpResponse], error)
	DeleteMcp(context.Context, *connect.Request[v1.DeleteMcpRequest]) (*connect.Response[v1.DeleteMcpResponse], error)
	ListMcps(context.Context, *connect.Request[v1.ListMcpsRequest]) (*connect.Response[v1.ListMcpsResponse], error)
	// --- Skills ---
	CreateSkill(context.Context, *connect.Request[v1.CreateSkillRequest]) (*connect.Response[v1.CreateSkillResponse], error)
	GetSkill(context.Context, *connect.Request[v1.GetSkillRequest]) (*connect.Response[v1.GetSkillResponse], error)
	UpdateSkill(context.Context, *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error)
	DeleteSkill(context.Context, *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error)
	ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error)
	// --- Hooks ---
	CreateHook(context.Context, *connect.Request[v1.CreateHookRequest]) (*connect.Response[v1.CreateHookResponse], error)
	GetHook(context.Context, *connect.Request[v1.GetHookRequest]) (*connect.Response[v1.GetHookResponse], error)
	UpdateHook(context.Context, *connect.Request[v1.UpdateHookRequest]) (*connect.Response[v1.UpdateHookResponse], error)
	DeleteHook(context.Context, *connect.Request[v1.DeleteHookRequest]) (*connect.Response[v1.DeleteHookResponse], error)
	ListHooks(context.Context, *connect.Request[v1.ListHooksRequest]) (*connect.Response[v1.ListHooksResponse], error)
	// --- Envs ---
	CreateEnv(context.Context, *connect.Request[v1.CreateEnvRequest]) (*connect.Response[v1.CreateEnvResponse], error)
	GetEnv(context.Context, *connect.Request[v1.GetEnvRequest]) (*connect.Response[v1.GetEnvResponse], error)
	UpdateEnv(context.Context, *connect.Request[v1.UpdateEnvRequest]) (*connect.Response[v1.UpdateEnvResponse], error)
	DeleteEnv(context.Context, *connect.Request[v1.DeleteEnvRequest]) (*connect.Response[v1.DeleteEnvResponse], error)
	ListEnvs(context.Context, *connect.Request[v1.ListEnvsRequest]) (*connect.Response[v1.ListEnvsResponse], error)
	// --- Init Scripts ---
	CreateInitScript(context.Context, *connect.Request[v1.CreateInitScriptRequest]) (*connect.Response[v1.CreateInitScriptResponse], error)
	GetInitScript(context.Context, *connect.Request[v1.GetInitScriptRequest]) (*connect.Response[v1.GetInitScriptResponse], error)
	UpdateInitScript(context.Context, *connect.Request[v1.UpdateInitScriptRequest]) (*connect.Response[v1.UpdateInitScriptResponse], error)
	DeleteInitScript(context.Context, *connect.Request[v1.DeleteInitScriptRequest]) (*connect.Response[v1.DeleteInitScriptResponse], error)
	ListInitScripts(context.Context, *connect.Request[v1.ListInitScriptsRequest]) (*connect.Response[v1.ListInitScriptsResponse], error)
	// --- Image Pull Secret Attachments (no Update - immutable) ---
	CreateImagePullSecretAttachment(context.Context, *connect.Request[v1.CreateImagePullSecretAttachmentRequest]) (*connect.Response[v1.CreateImagePullSecretAttachmentResponse], error)
	GetImagePullSecretAttachment(context.Context, *connect.Request[v1.GetImagePullSecretAttachmentRequest]) (*connect.Response[v1.GetImagePullSecretAttachmentResponse], error)
	DeleteImagePullSecretAttachment(context.Context, *connect.Request[v1.DeleteImagePullSecretAttachmentRequest]) (*connect.Response[v1.DeleteImagePullSecretAttachmentResponse], error)
	ListImagePullSecretAttachments(context.Context, *connect.Request[v1.ListImagePullSecretAttachmentsRequest]) (*connect.Response[v1.ListImagePullSecretAttachmentsResponse], error)
}

// NewAgentsGatewayClient constructs a client for the agynio.api.gateway.v1.AgentsGateway service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentsGatewayClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentsGatewayClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentsGatewayMethods := v11.File_agynio_api_gateway_v1_agents_proto.Services().ByName("AgentsGateway").Methods()
	return &agentsGatewayClient{
		createAgent: connect.NewClient[v1.CreateAgentRequest, v1.CreateAgentResponse](
			httpClient,
			baseURL+AgentsGatewayCreateAgentProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("CreateAgent")),
			connect.WithClientOptions(opts...),
		),
		getAgent: connect.NewClient[v1.GetAgentRequest, v1.GetAgentResponse](
			httpClient,
			baseURL+AgentsGatewayGetAgentProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("GetAgent")),
			connect.WithClientOptions(opts...),
		),
		updateAgent: connect.NewClient[v1.UpdateAgentRequest, v1.UpdateAgentResponse](
			httpClient,
			baseURL+AgentsGatewayUpdateAgentProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("UpdateAgent")),
			connect.WithClientOptions(opts...),
		),
		deleteAgent: connect.NewClient[v1.DeleteAgentRequest, v1.DeleteAgentResponse](
			httpClient,
			baseURL+AgentsGatewayDeleteAgentProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("DeleteAgent")),
			connect.WithClientOptions(opts...),
		),
		listAgents: connect.NewClient[v1.ListAgentsRequest, v1.ListAgentsResponse](
			httpClient,
			baseURL+AgentsGatewayListAgentsProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
		createVolume: connect.NewClient[v1.CreateVolumeRequest, v1.CreateVolumeResponse](
			httpClient,
			baseURL+AgentsGatewayCreateVolumeProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("CreateVolume")),
			connect.WithClientOptions(opts...),
		),
		getVolume: connect.NewClient[v1.GetVolumeRequest, v1.GetVolumeResponse](
			httpClient,
			baseURL+AgentsGatewayGetVolumeProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("GetVolume")),
			connect.WithClientOptions(opts...),
		),
		updateVolume: connect.NewClient[v1.UpdateVolumeRequest, v1.UpdateVolumeResponse](
			httpClient,
			baseURL+AgentsGatewayUpdateVolumeProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("UpdateVolume")),
			connect.WithClientOptions(opts...),
		),
		deleteVolume: connect.NewClient[v1.DeleteVolumeRequest, v1.DeleteVolumeResponse](
			httpClient,
			baseURL+AgentsGatewayDeleteVolumeProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("DeleteVolume")),
			connect.WithClientOptions(opts...),
		),
		listVolumes: connect.NewClient[v1.ListVolumesRequest, v1.ListVolumesResponse](
			httpClient,
			baseURL+AgentsGatewayListVolumesProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("ListVolumes")),
			connect.WithClientOptions(opts...),
		),
		createVolumeAttachment: connect.NewClient[v1.CreateVolumeAttachmentRequest, v1.CreateVolumeAttachmentResponse](
			httpClient,
			baseURL+AgentsGatewayCreateVolumeAttachmentProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("CreateVolumeAttachment")),
			connect.WithClientOptions(opts...),
		),
		getVolumeAttachment: connect.NewClient[v1.GetVolumeAttachmentRequest, v1.GetVolumeAttachmentResponse](
			httpClient,
			baseURL+AgentsGatewayGetVolumeAttachmentProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("GetVolumeAttachment")),
			connect.WithClientOptions(opts...),
		),
		deleteVolumeAttachment: connect.NewClient[v1.DeleteVolumeAttachmentRequest, v1.DeleteVolumeAttachmentResponse](
			httpClient,
			baseURL+AgentsGatewayDeleteVolumeAttachmentProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("DeleteVolumeAttachment")),
			connect.WithClientOptions(opts...),
		),
		listVolumeAttachments: connect.NewClient[v1.ListVolumeAttachmentsRequest, v1.ListVolumeAttachmentsResponse](
			httpClient,
			baseURL+AgentsGatewayListVolumeAttachmentsProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("ListVolumeAttachments")),
			connect.WithClientOptions(opts...),
		),
		createMcp: connect.NewClient[v1.CreateMcpRequest, v1.CreateMcpResponse](
			httpClient,
			baseURL+AgentsGatewayCreateMcpProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("CreateMcp")),
			connect.WithClientOptions(opts...),
		),
		getMcp: connect.NewClient[v1.GetMcpRequest, v1.GetMcpResponse](
			httpClient,
			baseURL+AgentsGatewayGetMcpProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("GetMcp")),
			connect.WithClientOptions(opts...),
		),
		updateMcp: connect.NewClient[v1.UpdateMcpRequest, v1.UpdateMcpResponse](
			httpClient,
			baseURL+AgentsGatewayUpdateMcpProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("UpdateMcp")),
			connect.WithClientOptions(opts...),
		),
		deleteMcp: connect.NewClient[v1.DeleteMcpRequest, v1.DeleteMcpResponse](
			httpClient,
			baseURL+AgentsGatewayDeleteMcpProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("DeleteMcp")),
			connect.WithClientOptions(opts...),
		),
		listMcps: connect.NewClient[v1.ListMcpsRequest, v1.ListMcpsResponse](
			httpClient,
			baseURL+AgentsGatewayListMcpsProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("ListMcps")),
			connect.WithClientOptions(opts...),
		),
		createSkill: connect.NewClient[v1.CreateSkillRequest, v1.CreateSkillResponse](
			httpClient,
			baseURL+AgentsGatewayCreateSkillProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("CreateSkill")),
			connect.WithClientOptions(opts...),
		),
		getSkill: connect.NewClient[v1.GetSkillRequest, v1.GetSkillResponse](
			httpClient,
			baseURL+AgentsGatewayGetSkillProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("GetSkill")),
			connect.WithClientOptions(opts...),
		),
		updateSkill: connect.NewClient[v1.UpdateSkillRequest, v1.UpdateSkillResponse](
			httpClient,
			baseURL+AgentsGatewayUpdateSkillProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("UpdateSkill")),
			connect.WithClientOptions(opts...),
		),
		deleteSkill: connect.NewClient[v1.DeleteSkillRequest, v1.DeleteSkillResponse](
			httpClient,
			baseURL+AgentsGatewayDeleteSkillProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("DeleteSkill")),
			connect.WithClientOptions(opts...),
		),
		listSkills: connect.NewClient[v1.ListSkillsRequest, v1.ListSkillsResponse](
			httpClient,
			baseURL+AgentsGatewayListSkillsProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("ListSkills")),
			connect.WithClientOptions(opts...),
		),
		createHook: connect.NewClient[v1.CreateHookRequest, v1.CreateHookResponse](
			httpClient,
			baseURL+AgentsGatewayCreateHookProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("CreateHook")),
			connect.WithClientOptions(opts...),
		),
		getHook: connect.NewClient[v1.GetHookRequest, v1.GetHookResponse](
			httpClient,
			baseURL+AgentsGatewayGetHookProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("GetHook")),
			connect.WithClientOptions(opts...),
		),
		updateHook: connect.NewClient[v1.UpdateHookRequest, v1.UpdateHookResponse](
			httpClient,
			baseURL+AgentsGatewayUpdateHookProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("UpdateHook")),
			connect.WithClientOptions(opts...),
		),
		deleteHook: connect.NewClient[v1.DeleteHookRequest, v1.DeleteHookResponse](
			httpClient,
			baseURL+AgentsGatewayDeleteHookProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("DeleteHook")),
			connect.WithClientOptions(opts...),
		),
		listHooks: connect.NewClient[v1.ListHooksRequest, v1.ListHooksResponse](
			httpClient,
			baseURL+AgentsGatewayListHooksProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("ListHooks")),
			connect.WithClientOptions(opts...),
		),
		createEnv: connect.NewClient[v1.CreateEnvRequest, v1.CreateEnvResponse](
			httpClient,
			baseURL+AgentsGatewayCreateEnvProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("CreateEnv")),
			connect.WithClientOptions(opts...),
		),
		getEnv: connect.NewClient[v1.GetEnvRequest, v1.GetEnvResponse](
			httpClient,
			baseURL+AgentsGatewayGetEnvProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("GetEnv")),
			connect.WithClientOptions(opts...),
		),
		updateEnv: connect.NewClient[v1.UpdateEnvRequest, v1.UpdateEnvResponse](
			httpClient,
			baseURL+AgentsGatewayUpdateEnvProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("UpdateEnv")),
			connect.WithClientOptions(opts...),
		),
		deleteEnv: connect.NewClient[v1.DeleteEnvRequest, v1.DeleteEnvResponse](
			httpClient,
			baseURL+AgentsGatewayDeleteEnvProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("DeleteEnv")),
			connect.WithClientOptions(opts...),
		),
		listEnvs: connect.NewClient[v1.ListEnvsRequest, v1.ListEnvsResponse](
			httpClient,
			baseURL+AgentsGatewayListEnvsProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("ListEnvs")),
			connect.WithClientOptions(opts...),
		),
		createInitScript: connect.NewClient[v1.CreateInitScriptRequest, v1.CreateInitScriptResponse](
			httpClient,
			baseURL+AgentsGatewayCreateInitScriptProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("CreateInitScript")),
			connect.WithClientOptions(opts...),
		),
		getInitScript: connect.NewClient[v1.GetInitScriptRequest, v1.GetInitScriptResponse](
			httpClient,
			baseURL+AgentsGatewayGetInitScriptProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("GetInitScript")),
			connect.WithClientOptions(opts...),
		),
		updateInitScript: connect.NewClient[v1.UpdateInitScriptRequest, v1.UpdateInitScriptResponse](
			httpClient,
			baseURL+AgentsGatewayUpdateInitScriptProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("UpdateInitScript")),
			connect.WithClientOptions(opts...),
		),
		deleteInitScript: connect.NewClient[v1.DeleteInitScriptRequest, v1.DeleteInitScriptResponse](
			httpClient,
			baseURL+AgentsGatewayDeleteInitScriptProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("DeleteInitScript")),
			connect.WithClientOptions(opts...),
		),
		listInitScripts: connect.NewClient[v1.ListInitScriptsRequest, v1.ListInitScriptsResponse](
			httpClient,
			baseURL+AgentsGatewayListInitScriptsProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("ListInitScripts")),
			connect.WithClientOptions(opts...),
		),
		createImagePullSecretAttachment: connect.NewClient[v1.CreateImagePullSecretAttachmentRequest, v1.CreateImagePullSecretAttachmentResponse](
			httpClient,
			baseURL+AgentsGatewayCreateImagePullSecretAttachmentProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("CreateImagePullSecretAttachment")),
			connect.WithClientOptions(opts...),
		),
		getImagePullSecretAttachment: connect.NewClient[v1.GetImagePullSecretAttachmentRequest, v1.GetImagePullSecretAttachmentResponse](
			httpClient,
			baseURL+AgentsGatewayGetImagePullSecretAttachmentProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("GetImagePullSecretAttachment")),
			connect.WithClientOptions(opts...),
		),
		deleteImagePullSecretAttachment: connect.NewClient[v1.DeleteImagePullSecretAttachmentRequest, v1.DeleteImagePullSecretAttachmentResponse](
			httpClient,
			baseURL+AgentsGatewayDeleteImagePullSecretAttachmentProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("DeleteImagePullSecretAttachment")),
			connect.WithClientOptions(opts...),
		),
		listImagePullSecretAttachments: connect.NewClient[v1.ListImagePullSecretAttachmentsRequest, v1.ListImagePullSecretAttachmentsResponse](
			httpClient,
			baseURL+AgentsGatewayListImagePullSecretAttachmentsProcedure,
			connect.WithSchema(agentsGatewayMethods.ByName("ListImagePullSecretAttachments")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentsGatewayClient implements AgentsGatewayClient.
type agentsGatewayClient struct {
	createAgent                     *connect.Client[v1.CreateAgentRequest, v1.CreateAgentResponse]
	getAgent                        *connect.Client[v1.GetAgentRequest, v1.GetAgentResponse]
	updateAgent                     *connect.Client[v1.UpdateAgentRequest, v1.UpdateAgentResponse]
	deleteAgent                     *connect.Client[v1.DeleteAgentRequest, v1.DeleteAgentResponse]
	listAgents                      *connect.Client[v1.ListAgentsRequest, v1.ListAgentsResponse]
	createVolume                    *connect.Client[v1.CreateVolumeRequest, v1.CreateVolumeResponse]
	getVolume                       *connect.Client[v1.GetVolumeRequest, v1.GetVolumeResponse]
	updateVolume                    *connect.Client[v1.UpdateVolumeRequest, v1.UpdateVolumeResponse]
	deleteVolume                    *connect.Client[v1.DeleteVolumeRequest, v1.DeleteVolumeResponse]
	listVolumes                     *connect.Client[v1.ListVolumesRequest, v1.ListVolumesResponse]
	createVolumeAttachment          *connect.Client[v1.CreateVolumeAttachmentRequest, v1.CreateVolumeAttachmentResponse]
	getVolumeAttachment             *connect.Client[v1.GetVolumeAttachmentRequest, v1.GetVolumeAttachmentResponse]
	deleteVolumeAttachment          *connect.Client[v1.DeleteVolumeAttachmentRequest, v1.DeleteVolumeAttachmentResponse]
	listVolumeAttachments           *connect.Client[v1.ListVolumeAttachmentsRequest, v1.ListVolumeAttachmentsResponse]
	createMcp                       *connect.Client[v1.CreateMcpRequest, v1.CreateMcpResponse]
	getMcp                          *connect.Client[v1.GetMcpRequest, v1.GetMcpResponse]
	updateMcp                       *connect.Client[v1.UpdateMcpRequest, v1.UpdateMcpResponse]
	deleteMcp                       *connect.Client[v1.DeleteMcpRequest, v1.DeleteMcpResponse]
	listMcps                        *connect.Client[v1.ListMcpsRequest, v1.ListMcpsResponse]
	createSkill                     *connect.Client[v1.CreateSkillRequest, v1.CreateSkillResponse]
	getSkill                        *connect.Client[v1.GetSkillRequest, v1.GetSkillResponse]
	updateSkill                     *connect.Client[v1.UpdateSkillRequest, v1.UpdateSkillResponse]
	deleteSkill                     *connect.Client[v1.DeleteSkillRequest, v1.DeleteSkillResponse]
	listSkills                      *connect.Client[v1.ListSkillsRequest, v1.ListSkillsResponse]
	createHook                      *connect.Client[v1.CreateHookRequest, v1.CreateHookResponse]
	getHook                         *connect.Client[v1.GetHookRequest, v1.GetHookResponse]
	updateHook                      *connect.Client[v1.UpdateHookRequest, v1.UpdateHookResponse]
	deleteHook                      *connect.Client[v1.DeleteHookRequest, v1.DeleteHookResponse]
	listHooks                       *connect.Client[v1.ListHooksRequest, v1.ListHooksResponse]
	createEnv                       *connect.Client[v1.CreateEnvRequest, v1.CreateEnvResponse]
	getEnv                          *connect.Client[v1.GetEnvRequest, v1.GetEnvResponse]
	updateEnv                       *connect.Client[v1.UpdateEnvRequest, v1.UpdateEnvResponse]
	deleteEnv                       *connect.Client[v1.DeleteEnvRequest, v1.DeleteEnvResponse]
	listEnvs                        *connect.Client[v1.ListEnvsRequest, v1.ListEnvsResponse]
	createInitScript                *connect.Client[v1.CreateInitScriptRequest, v1.CreateInitScriptResponse]
	getInitScript                   *connect.Client[v1.GetInitScriptRequest, v1.GetInitScriptResponse]
	updateInitScript                *connect.Client[v1.UpdateInitScriptRequest, v1.UpdateInitScriptResponse]
	deleteInitScript                *connect.Client[v1.DeleteInitScriptRequest, v1.DeleteInitScriptResponse]
	listInitScripts                 *connect.Client[v1.ListInitScriptsRequest, v1.ListInitScriptsResponse]
	createImagePullSecretAttachment *connect.Client[v1.CreateImagePullSecretAttachmentRequest, v1.CreateImagePullSecretAttachmentResponse]
	getImagePullSecretAttachment    *connect.Client[v1.GetImagePullSecretAttachmentRequest, v1.GetImagePullSecretAttachmentResponse]
	deleteImagePullSecretAttachment *connect.Client[v1.DeleteImagePullSecretAttachmentRequest, v1.DeleteImagePullSecretAttachmentResponse]
	listImagePullSecretAttachments  *connect.Client[v1.ListImagePullSecretAttachmentsRequest, v1.ListImagePullSecretAttachmentsResponse]
}

// CreateAgent calls agynio.api.gateway.v1.AgentsGateway.CreateAgent.
func (c *agentsGatewayClient) CreateAgent(ctx context.Context, req *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error) {
	return c.createAgent.CallUnary(ctx, req)
}

// GetAgent calls agynio.api.gateway.v1.AgentsGateway.GetAgent.
func (c *agentsGatewayClient) GetAgent(ctx context.Context, req *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error) {
	return c.getAgent.CallUnary(ctx, req)
}

// UpdateAgent calls agynio.api.gateway.v1.AgentsGateway.UpdateAgent.
func (c *agentsGatewayClient) UpdateAgent(ctx context.Context, req *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.UpdateAgentResponse], error) {
	return c.updateAgent.CallUnary(ctx, req)
}

// DeleteAgent calls agynio.api.gateway.v1.AgentsGateway.DeleteAgent.
func (c *agentsGatewayClient) DeleteAgent(ctx context.Context, req *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[v1.DeleteAgentResponse], error) {
	return c.deleteAgent.CallUnary(ctx, req)
}

// ListAgents calls agynio.api.gateway.v1.AgentsGateway.ListAgents.
func (c *agentsGatewayClient) ListAgents(ctx context.Context, req *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// CreateVolume calls agynio.api.gateway.v1.AgentsGateway.CreateVolume.
func (c *agentsGatewayClient) CreateVolume(ctx context.Context, req *connect.Request[v1.CreateVolumeRequest]) (*connect.Response[v1.CreateVolumeResponse], error) {
	return c.createVolume.CallUnary(ctx, req)
}

// GetVolume calls agynio.api.gateway.v1.AgentsGateway.GetVolume.
func (c *agentsGatewayClient) GetVolume(ctx context.Context, req *connect.Request[v1.GetVolumeRequest]) (*connect.Response[v1.GetVolumeResponse], error) {
	return c.getVolume.CallUnary(ctx, req)
}

// UpdateVolume calls agynio.api.gateway.v1.AgentsGateway.UpdateVolume.
func (c *agentsGatewayClient) UpdateVolume(ctx context.Context, req *connect.Request[v1.UpdateVolumeRequest]) (*connect.Response[v1.UpdateVolumeResponse], error) {
	return c.updateVolume.CallUnary(ctx, req)
}

// DeleteVolume calls agynio.api.gateway.v1.AgentsGateway.DeleteVolume.
func (c *agentsGatewayClient) DeleteVolume(ctx context.Context, req *connect.Request[v1.DeleteVolumeRequest]) (*connect.Response[v1.DeleteVolumeResponse], error) {
	return c.deleteVolume.CallUnary(ctx, req)
}

// ListVolumes calls agynio.api.gateway.v1.AgentsGateway.ListVolumes.
func (c *agentsGatewayClient) ListVolumes(ctx context.Context, req *connect.Request[v1.ListVolumesRequest]) (*connect.Response[v1.ListVolumesResponse], error) {
	return c.listVolumes.CallUnary(ctx, req)
}

// CreateVolumeAttachment calls agynio.api.gateway.v1.AgentsGateway.CreateVolumeAttachment.
func (c *agentsGatewayClient) CreateVolumeAttachment(ctx context.Context, req *connect.Request[v1.CreateVolumeAttachmentRequest]) (*connect.Response[v1.CreateVolumeAttachmentResponse], error) {
	return c.createVolumeAttachment.CallUnary(ctx, req)
}

// GetVolumeAttachment calls agynio.api.gateway.v1.AgentsGateway.GetVolumeAttachment.
func (c *agentsGatewayClient) GetVolumeAttachment(ctx context.Context, req *connect.Request[v1.GetVolumeAttachmentRequest]) (*connect.Response[v1.GetVolumeAttachmentResponse], error) {
	return c.getVolumeAttachment.CallUnary(ctx, req)
}

// DeleteVolumeAttachment calls agynio.api.gateway.v1.AgentsGateway.DeleteVolumeAttachment.
func (c *agentsGatewayClient) DeleteVolumeAttachment(ctx context.Context, req *connect.Request[v1.DeleteVolumeAttachmentRequest]) (*connect.Response[v1.DeleteVolumeAttachmentResponse], error) {
	return c.deleteVolumeAttachment.CallUnary(ctx, req)
}

// ListVolumeAttachments calls agynio.api.gateway.v1.AgentsGateway.ListVolumeAttachments.
func (c *agentsGatewayClient) ListVolumeAttachments(ctx context.Context, req *connect.Request[v1.ListVolumeAttachmentsRequest]) (*connect.Response[v1.ListVolumeAttachmentsResponse], error) {
	return c.listVolumeAttachments.CallUnary(ctx, req)
}

// CreateMcp calls agynio.api.gateway.v1.AgentsGateway.CreateMcp.
func (c *agentsGatewayClient) CreateMcp(ctx context.Context, req *connect.Request[v1.CreateMcpRequest]) (*connect.Response[v1.CreateMcpResponse], error) {
	return c.createMcp.CallUnary(ctx, req)
}

// GetMcp calls agynio.api.gateway.v1.AgentsGateway.GetMcp.
func (c *agentsGatewayClient) GetMcp(ctx context.Context, req *connect.Request[v1.GetMcpRequest]) (*connect.Response[v1.GetMcpResponse], error) {
	return c.getMcp.CallUnary(ctx, req)
}

// UpdateMcp calls agynio.api.gateway.v1.AgentsGateway.UpdateMcp.
func (c *agentsGatewayClient) UpdateMcp(ctx context.Context, req *connect.Request[v1.UpdateMcpRequest]) (*connect.Response[v1.UpdateMcpResponse], error) {
	return c.updateMcp.CallUnary(ctx, req)
}

// DeleteMcp calls agynio.api.gateway.v1.AgentsGateway.DeleteMcp.
func (c *agentsGatewayClient) DeleteMcp(ctx context.Context, req *connect.Request[v1.DeleteMcpRequest]) (*connect.Response[v1.DeleteMcpResponse], error) {
	return c.deleteMcp.CallUnary(ctx, req)
}

// ListMcps calls agynio.api.gateway.v1.AgentsGateway.ListMcps.
func (c *agentsGatewayClient) ListMcps(ctx context.Context, req *connect.Request[v1.ListMcpsRequest]) (*connect.Response[v1.ListMcpsResponse], error) {
	return c.listMcps.CallUnary(ctx, req)
}

// CreateSkill calls agynio.api.gateway.v1.AgentsGateway.CreateSkill.
func (c *agentsGatewayClient) CreateSkill(ctx context.Context, req *connect.Request[v1.CreateSkillRequest]) (*connect.Response[v1.CreateSkillResponse], error) {
	return c.createSkill.CallUnary(ctx, req)
}

// GetSkill calls agynio.api.gateway.v1.AgentsGateway.GetSkill.
func (c *agentsGatewayClient) GetSkill(ctx context.Context, req *connect.Request[v1.GetSkillRequest]) (*connect.Response[v1.GetSkillResponse], error) {
	return c.getSkill.CallUnary(ctx, req)
}

// UpdateSkill calls agynio.api.gateway.v1.AgentsGateway.UpdateSkill.
func (c *agentsGatewayClient) UpdateSkill(ctx context.Context, req *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error) {
	return c.updateSkill.CallUnary(ctx, req)
}

// DeleteSkill calls agynio.api.gateway.v1.AgentsGateway.DeleteSkill.
func (c *agentsGatewayClient) DeleteSkill(ctx context.Context, req *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error) {
	return c.deleteSkill.CallUnary(ctx, req)
}

// ListSkills calls agynio.api.gateway.v1.AgentsGateway.ListSkills.
func (c *agentsGatewayClient) ListSkills(ctx context.Context, req *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error) {
	return c.listSkills.CallUnary(ctx, req)
}

// CreateHook calls agynio.api.gateway.v1.AgentsGateway.CreateHook.
func (c *agentsGatewayClient) CreateHook(ctx context.Context, req *connect.Request[v1.CreateHookRequest]) (*connect.Response[v1.CreateHookResponse], error) {
	return c.createHook.CallUnary(ctx, req)
}

// GetHook calls agynio.api.gateway.v1.AgentsGateway.GetHook.
func (c *agentsGatewayClient) GetHook(ctx context.Context, req *connect.Request[v1.GetHookRequest]) (*connect.Response[v1.GetHookResponse], error) {
	return c.getHook.CallUnary(ctx, req)
}

// UpdateHook calls agynio.api.gateway.v1.AgentsGateway.UpdateHook.
func (c *agentsGatewayClient) UpdateHook(ctx context.Context, req *connect.Request[v1.UpdateHookRequest]) (*connect.Response[v1.UpdateHookResponse], error) {
	return c.updateHook.CallUnary(ctx, req)
}

// DeleteHook calls agynio.api.gateway.v1.AgentsGateway.DeleteHook.
func (c *agentsGatewayClient) DeleteHook(ctx context.Context, req *connect.Request[v1.DeleteHookRequest]) (*connect.Response[v1.DeleteHookResponse], error) {
	return c.deleteHook.CallUnary(ctx, req)
}

// ListHooks calls agynio.api.gateway.v1.AgentsGateway.ListHooks.
func (c *agentsGatewayClient) ListHooks(ctx context.Context, req *connect.Request[v1.ListHooksRequest]) (*connect.Response[v1.ListHooksResponse], error) {
	return c.listHooks.CallUnary(ctx, req)
}

// CreateEnv calls agynio.api.gateway.v1.AgentsGateway.CreateEnv.
func (c *agentsGatewayClient) CreateEnv(ctx context.Context, req *connect.Request[v1.CreateEnvRequest]) (*connect.Response[v1.CreateEnvResponse], error) {
	return c.createEnv.CallUnary(ctx, req)
}

// GetEnv calls agynio.api.gateway.v1.AgentsGateway.GetEnv.
func (c *agentsGatewayClient) GetEnv(ctx context.Context, req *connect.Request[v1.GetEnvRequest]) (*connect.Response[v1.GetEnvResponse], error) {
	return c.getEnv.CallUnary(ctx, req)
}

// UpdateEnv calls agynio.api.gateway.v1.AgentsGateway.UpdateEnv.
func (c *agentsGatewayClient) UpdateEnv(ctx context.Context, req *connect.Request[v1.UpdateEnvRequest]) (*connect.Response[v1.UpdateEnvResponse], error) {
	return c.updateEnv.CallUnary(ctx, req)
}

// DeleteEnv calls agynio.api.gateway.v1.AgentsGateway.DeleteEnv.
func (c *agentsGatewayClient) DeleteEnv(ctx context.Context, req *connect.Request[v1.DeleteEnvRequest]) (*connect.Response[v1.DeleteEnvResponse], error) {
	return c.deleteEnv.CallUnary(ctx, req)
}

// ListEnvs calls agynio.api.gateway.v1.AgentsGateway.ListEnvs.
func (c *agentsGatewayClient) ListEnvs(ctx context.Context, req *connect.Request[v1.ListEnvsRequest]) (*connect.Response[v1.ListEnvsResponse], error) {
	return c.listEnvs.CallUnary(ctx, req)
}

// CreateInitScript calls agynio.api.gateway.v1.AgentsGateway.CreateInitScript.
func (c *agentsGatewayClient) CreateInitScript(ctx context.Context, req *connect.Request[v1.CreateInitScriptRequest]) (*connect.Response[v1.CreateInitScriptResponse], error) {
	return c.createInitScript.CallUnary(ctx, req)
}

// GetInitScript calls agynio.api.gateway.v1.AgentsGateway.GetInitScript.
func (c *agentsGatewayClient) GetInitScript(ctx context.Context, req *connect.Request[v1.GetInitScriptRequest]) (*connect.Response[v1.GetInitScriptResponse], error) {
	return c.getInitScript.CallUnary(ctx, req)
}

// UpdateInitScript calls agynio.api.gateway.v1.AgentsGateway.UpdateInitScript.
func (c *agentsGatewayClient) UpdateInitScript(ctx context.Context, req *connect.Request[v1.UpdateInitScriptRequest]) (*connect.Response[v1.UpdateInitScriptResponse], error) {
	return c.updateInitScript.CallUnary(ctx, req)
}

// DeleteInitScript calls agynio.api.gateway.v1.AgentsGateway.DeleteInitScript.
func (c *agentsGatewayClient) DeleteInitScript(ctx context.Context, req *connect.Request[v1.DeleteInitScriptRequest]) (*connect.Response[v1.DeleteInitScriptResponse], error) {
	return c.deleteInitScript.CallUnary(ctx, req)
}

// ListInitScripts calls agynio.api.gateway.v1.AgentsGateway.ListInitScripts.
func (c *agentsGatewayClient) ListInitScripts(ctx context.Context, req *connect.Request[v1.ListInitScriptsRequest]) (*connect.Response[v1.ListInitScriptsResponse], error) {
	return c.listInitScripts.CallUnary(ctx, req)
}

// CreateImagePullSecretAttachment calls
// agynio.api.gateway.v1.AgentsGateway.CreateImagePullSecretAttachment.
func (c *agentsGatewayClient) CreateImagePullSecretAttachment(ctx context.Context, req *connect.Request[v1.CreateImagePullSecretAttachmentRequest]) (*connect.Response[v1.CreateImagePullSecretAttachmentResponse], error) {
	return c.createImagePullSecretAttachment.CallUnary(ctx, req)
}

// GetImagePullSecretAttachment calls
// agynio.api.gateway.v1.AgentsGateway.GetImagePullSecretAttachment.
func (c *agentsGatewayClient) GetImagePullSecretAttachment(ctx context.Context, req *connect.Request[v1.GetImagePullSecretAttachmentRequest]) (*connect.Response[v1.GetImagePullSecretAttachmentResponse], error) {
	return c.getImagePullSecretAttachment.CallUnary(ctx, req)
}

// DeleteImagePullSecretAttachment calls
// agynio.api.gateway.v1.AgentsGateway.DeleteImagePullSecretAttachment.
func (c *agentsGatewayClient) DeleteImagePullSecretAttachment(ctx context.Context, req *connect.Request[v1.DeleteImagePullSecretAttachmentRequest]) (*connect.Response[v1.DeleteImagePullSecretAttachmentResponse], error) {
	return c.deleteImagePullSecretAttachment.CallUnary(ctx, req)
}

// ListImagePullSecretAttachments calls
// agynio.api.gateway.v1.AgentsGateway.ListImagePullSecretAttachments.
func (c *agentsGatewayClient) ListImagePullSecretAttachments(ctx context.Context, req *connect.Request[v1.ListImagePullSecretAttachmentsRequest]) (*connect.Response[v1.ListImagePullSecretAttachmentsResponse], error) {
	return c.listImagePullSecretAttachments.CallUnary(ctx, req)
}

// AgentsGatewayHandler is an implementation of the agynio.api.gateway.v1.AgentsGateway service.
type AgentsGatewayHandler interface {
	// --- Agents ---
	CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error)
	GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error)
	UpdateAgent(context.Context, *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.UpdateAgentResponse], error)
	DeleteAgent(context.Context, *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[v1.DeleteAgentResponse], error)
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	// --- Volumes ---
	CreateVolume(context.Context, *connect.Request[v1.CreateVolumeRequest]) (*connect.Response[v1.CreateVolumeResponse], error)
	GetVolume(context.Context, *connect.Request[v1.GetVolumeRequest]) (*connect.Response[v1.GetVolumeResponse], error)
	UpdateVolume(context.Context, *connect.Request[v1.UpdateVolumeRequest]) (*connect.Response[v1.UpdateVolumeResponse], error)
	DeleteVolume(context.Context, *connect.Request[v1.DeleteVolumeRequest]) (*connect.Response[v1.DeleteVolumeResponse], error)
	ListVolumes(context.Context, *connect.Request[v1.ListVolumesRequest]) (*connect.Response[v1.ListVolumesResponse], error)
	// --- Volume Attachments (no Update) ---
	CreateVolumeAttachment(context.Context, *connect.Request[v1.CreateVolumeAttachmentRequest]) (*connect.Response[v1.CreateVolumeAttachmentResponse], error)
	GetVolumeAttachment(context.Context, *connect.Request[v1.GetVolumeAttachmentRequest]) (*connect.Response[v1.GetVolumeAttachmentResponse], error)
	DeleteVolumeAttachment(context.Context, *connect.Request[v1.DeleteVolumeAttachmentRequest]) (*connect.Response[v1.DeleteVolumeAttachmentResponse], error)
	ListVolumeAttachments(context.Context, *connect.Request[v1.ListVolumeAttachmentsRequest]) (*connect.Response[v1.ListVolumeAttachmentsResponse], error)
	// --- MCPs ---
	CreateMcp(context.Context, *connect.Request[v1.CreateMcpRequest]) (*connect.Response[v1.CreateMcpResponse], error)
	GetMcp(context.Context, *connect.Request[v1.GetMcpRequest]) (*connect.Response[v1.GetMcpResponse], error)
	UpdateMcp(context.Context, *connect.Request[v1.UpdateMcpRequest]) (*connect.Response[v1.UpdateMcpResponse], error)
	DeleteMcp(context.Context, *connect.Request[v1.DeleteMcpRequest]) (*connect.Response[v1.DeleteMcpResponse], error)
	ListMcps(context.Context, *connect.Request[v1.ListMcpsRequest]) (*connect.Response[v1.ListMcpsResponse], error)
	// --- Skills ---
	CreateSkill(context.Context, *connect.Request[v1.CreateSkillRequest]) (*connect.Response[v1.CreateSkillResponse], error)
	GetSkill(context.Context, *connect.Request[v1.GetSkillRequest]) (*connect.Response[v1.GetSkillResponse], error)
	UpdateSkill(context.Context, *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error)
	DeleteSkill(context.Context, *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error)
	ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error)
	// --- Hooks ---
	CreateHook(context.Context, *connect.Request[v1.CreateHookRequest]) (*connect.Response[v1.CreateHookResponse], error)
	GetHook(context.Context, *connect.Request[v1.GetHookRequest]) (*connect.Response[v1.GetHookResponse], error)
	UpdateHook(context.Context, *connect.Request[v1.UpdateHookRequest]) (*connect.Response[v1.UpdateHookResponse], error)
	DeleteHook(context.Context, *connect.Request[v1.DeleteHookRequest]) (*connect.Response[v1.DeleteHookResponse], error)
	ListHooks(context.Context, *connect.Request[v1.ListHooksRequest]) (*connect.Response[v1.ListHooksResponse], error)
	// --- Envs ---
	CreateEnv(context.Context, *connect.Request[v1.CreateEnvRequest]) (*connect.Response[v1.CreateEnvResponse], error)
	GetEnv(context.Context, *connect.Request[v1.GetEnvRequest]) (*connect.Response[v1.GetEnvResponse], error)
	UpdateEnv(context.Context, *connect.Request[v1.UpdateEnvRequest]) (*connect.Response[v1.UpdateEnvResponse], error)
	DeleteEnv(context.Context, *connect.Request[v1.DeleteEnvRequest]) (*connect.Response[v1.DeleteEnvResponse], error)
	ListEnvs(context.Context, *connect.Request[v1.ListEnvsRequest]) (*connect.Response[v1.ListEnvsResponse], error)
	// --- Init Scripts ---
	CreateInitScript(context.Context, *connect.Request[v1.CreateInitScriptRequest]) (*connect.Response[v1.CreateInitScriptResponse], error)
	GetInitScript(context.Context, *connect.Request[v1.GetInitScriptRequest]) (*connect.Response[v1.GetInitScriptResponse], error)
	UpdateInitScript(context.Context, *connect.Request[v1.UpdateInitScriptRequest]) (*connect.Response[v1.UpdateInitScriptResponse], error)
	DeleteInitScript(context.Context, *connect.Request[v1.DeleteInitScriptRequest]) (*connect.Response[v1.DeleteInitScriptResponse], error)
	ListInitScripts(context.Context, *connect.Request[v1.ListInitScriptsRequest]) (*connect.Response[v1.ListInitScriptsResponse], error)
	// --- Image Pull Secret Attachments (no Update - immutable) ---
	CreateImagePullSecretAttachment(context.Context, *connect.Request[v1.CreateImagePullSecretAttachmentRequest]) (*connect.Response[v1.CreateImagePullSecretAttachmentResponse], error)
	GetImagePullSecretAttachment(context.Context, *connect.Request[v1.GetImagePullSecretAttachmentRequest]) (*connect.Response[v1.GetImagePullSecretAttachmentResponse], error)
	DeleteImagePullSecretAttachment(context.Context, *connect.Request[v1.DeleteImagePullSecretAttachmentRequest]) (*connect.Response[v1.DeleteImagePullSecretAttachmentResponse], error)
	ListImagePullSecretAttachments(context.Context, *connect.Request[v1.ListImagePullSecretAttachmentsRequest]) (*connect.Response[v1.ListImagePullSecretAttachmentsResponse], error)
}

// NewAgentsGatewayHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentsGatewayHandler(svc AgentsGatewayHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentsGatewayMethods := v11.File_agynio_api_gateway_v1_agents_proto.Services().ByName("AgentsGateway").Methods()
	agentsGatewayCreateAgentHandler := connect.NewUnaryHandler(
		AgentsGatewayCreateAgentProcedure,
		svc.CreateAgent,
		connect.WithSchema(agentsGatewayMethods.ByName("CreateAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayGetAgentHandler := connect.NewUnaryHandler(
		AgentsGatewayGetAgentProcedure,
		svc.GetAgent,
		connect.WithSchema(agentsGatewayMethods.ByName("GetAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayUpdateAgentHandler := connect.NewUnaryHandler(
		AgentsGatewayUpdateAgentProcedure,
		svc.UpdateAgent,
		connect.WithSchema(agentsGatewayMethods.ByName("UpdateAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayDeleteAgentHandler := connect.NewUnaryHandler(
		AgentsGatewayDeleteAgentProcedure,
		svc.DeleteAgent,
		connect.WithSchema(agentsGatewayMethods.ByName("DeleteAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayListAgentsHandler := connect.NewUnaryHandler(
		AgentsGatewayListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(agentsGatewayMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayCreateVolumeHandler := connect.NewUnaryHandler(
		AgentsGatewayCreateVolumeProcedure,
		svc.CreateVolume,
		connect.WithSchema(agentsGatewayMethods.ByName("CreateVolume")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayGetVolumeHandler := connect.NewUnaryHandler(
		AgentsGatewayGetVolumeProcedure,
		svc.GetVolume,
		connect.WithSchema(agentsGatewayMethods.ByName("GetVolume")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayUpdateVolumeHandler := connect.NewUnaryHandler(
		AgentsGatewayUpdateVolumeProcedure,
		svc.UpdateVolume,
		connect.WithSchema(agentsGatewayMethods.ByName("UpdateVolume")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayDeleteVolumeHandler := connect.NewUnaryHandler(
		AgentsGatewayDeleteVolumeProcedure,
		svc.DeleteVolume,
		connect.WithSchema(agentsGatewayMethods.ByName("DeleteVolume")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayListVolumesHandler := connect.NewUnaryHandler(
		AgentsGatewayListVolumesProcedure,
		svc.ListVolumes,
		connect.WithSchema(agentsGatewayMethods.ByName("ListVolumes")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayCreateVolumeAttachmentHandler := connect.NewUnaryHandler(
		AgentsGatewayCreateVolumeAttachmentProcedure,
		svc.CreateVolumeAttachment,
		connect.WithSchema(agentsGatewayMethods.ByName("CreateVolumeAttachment")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayGetVolumeAttachmentHandler := connect.NewUnaryHandler(
		AgentsGatewayGetVolumeAttachmentProcedure,
		svc.GetVolumeAttachment,
		connect.WithSchema(agentsGatewayMethods.ByName("GetVolumeAttachment")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayDeleteVolumeAttachmentHandler := connect.NewUnaryHandler(
		AgentsGatewayDeleteVolumeAttachmentProcedure,
		svc.DeleteVolumeAttachment,
		connect.WithSchema(agentsGatewayMethods.ByName("DeleteVolumeAttachment")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayListVolumeAttachmentsHandler := connect.NewUnaryHandler(
		AgentsGatewayListVolumeAttachmentsProcedure,
		svc.ListVolumeAttachments,
		connect.WithSchema(agentsGatewayMethods.ByName("ListVolumeAttachments")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayCreateMcpHandler := connect.NewUnaryHandler(
		AgentsGatewayCreateMcpProcedure,
		svc.CreateMcp,
		connect.WithSchema(agentsGatewayMethods.ByName("CreateMcp")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayGetMcpHandler := connect.NewUnaryHandler(
		AgentsGatewayGetMcpProcedure,
		svc.GetMcp,
		connect.WithSchema(agentsGatewayMethods.ByName("GetMcp")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayUpdateMcpHandler := connect.NewUnaryHandler(
		AgentsGatewayUpdateMcpProcedure,
		svc.UpdateMcp,
		connect.WithSchema(agentsGatewayMethods.ByName("UpdateMcp")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayDeleteMcpHandler := connect.NewUnaryHandler(
		AgentsGatewayDeleteMcpProcedure,
		svc.DeleteMcp,
		connect.WithSchema(agentsGatewayMethods.ByName("DeleteMcp")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayListMcpsHandler := connect.NewUnaryHandler(
		AgentsGatewayListMcpsProcedure,
		svc.ListMcps,
		connect.WithSchema(agentsGatewayMethods.ByName("ListMcps")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayCreateSkillHandler := connect.NewUnaryHandler(
		AgentsGatewayCreateSkillProcedure,
		svc.CreateSkill,
		connect.WithSchema(agentsGatewayMethods.ByName("CreateSkill")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayGetSkillHandler := connect.NewUnaryHandler(
		AgentsGatewayGetSkillProcedure,
		svc.GetSkill,
		connect.WithSchema(agentsGatewayMethods.ByName("GetSkill")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayUpdateSkillHandler := connect.NewUnaryHandler(
		AgentsGatewayUpdateSkillProcedure,
		svc.UpdateSkill,
		connect.WithSchema(agentsGatewayMethods.ByName("UpdateSkill")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayDeleteSkillHandler := connect.NewUnaryHandler(
		AgentsGatewayDeleteSkillProcedure,
		svc.DeleteSkill,
		connect.WithSchema(agentsGatewayMethods.ByName("DeleteSkill")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayListSkillsHandler := connect.NewUnaryHandler(
		AgentsGatewayListSkillsProcedure,
		svc.ListSkills,
		connect.WithSchema(agentsGatewayMethods.ByName("ListSkills")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayCreateHookHandler := connect.NewUnaryHandler(
		AgentsGatewayCreateHookProcedure,
		svc.CreateHook,
		connect.WithSchema(agentsGatewayMethods.ByName("CreateHook")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayGetHookHandler := connect.NewUnaryHandler(
		AgentsGatewayGetHookProcedure,
		svc.GetHook,
		connect.WithSchema(agentsGatewayMethods.ByName("GetHook")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayUpdateHookHandler := connect.NewUnaryHandler(
		AgentsGatewayUpdateHookProcedure,
		svc.UpdateHook,
		connect.WithSchema(agentsGatewayMethods.ByName("UpdateHook")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayDeleteHookHandler := connect.NewUnaryHandler(
		AgentsGatewayDeleteHookProcedure,
		svc.DeleteHook,
		connect.WithSchema(agentsGatewayMethods.ByName("DeleteHook")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayListHooksHandler := connect.NewUnaryHandler(
		AgentsGatewayListHooksProcedure,
		svc.ListHooks,
		connect.WithSchema(agentsGatewayMethods.ByName("ListHooks")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayCreateEnvHandler := connect.NewUnaryHandler(
		AgentsGatewayCreateEnvProcedure,
		svc.CreateEnv,
		connect.WithSchema(agentsGatewayMethods.ByName("CreateEnv")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayGetEnvHandler := connect.NewUnaryHandler(
		AgentsGatewayGetEnvProcedure,
		svc.GetEnv,
		connect.WithSchema(agentsGatewayMethods.ByName("GetEnv")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayUpdateEnvHandler := connect.NewUnaryHandler(
		AgentsGatewayUpdateEnvProcedure,
		svc.UpdateEnv,
		connect.WithSchema(agentsGatewayMethods.ByName("UpdateEnv")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayDeleteEnvHandler := connect.NewUnaryHandler(
		AgentsGatewayDeleteEnvProcedure,
		svc.DeleteEnv,
		connect.WithSchema(agentsGatewayMethods.ByName("DeleteEnv")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayListEnvsHandler := connect.NewUnaryHandler(
		AgentsGatewayListEnvsProcedure,
		svc.ListEnvs,
		connect.WithSchema(agentsGatewayMethods.ByName("ListEnvs")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayCreateInitScriptHandler := connect.NewUnaryHandler(
		AgentsGatewayCreateInitScriptProcedure,
		svc.CreateInitScript,
		connect.WithSchema(agentsGatewayMethods.ByName("CreateInitScript")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayGetInitScriptHandler := connect.NewUnaryHandler(
		AgentsGatewayGetInitScriptProcedure,
		svc.GetInitScript,
		connect.WithSchema(agentsGatewayMethods.ByName("GetInitScript")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayUpdateInitScriptHandler := connect.NewUnaryHandler(
		AgentsGatewayUpdateInitScriptProcedure,
		svc.UpdateInitScript,
		connect.WithSchema(agentsGatewayMethods.ByName("UpdateInitScript")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayDeleteInitScriptHandler := connect.NewUnaryHandler(
		AgentsGatewayDeleteInitScriptProcedure,
		svc.DeleteInitScript,
		connect.WithSchema(agentsGatewayMethods.ByName("DeleteInitScript")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayListInitScriptsHandler := connect.NewUnaryHandler(
		AgentsGatewayListInitScriptsProcedure,
		svc.ListInitScripts,
		connect.WithSchema(agentsGatewayMethods.ByName("ListInitScripts")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayCreateImagePullSecretAttachmentHandler := connect.NewUnaryHandler(
		AgentsGatewayCreateImagePullSecretAttachmentProcedure,
		svc.CreateImagePullSecretAttachment,
		connect.WithSchema(agentsGatewayMethods.ByName("CreateImagePullSecretAttachment")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayGetImagePullSecretAttachmentHandler := connect.NewUnaryHandler(
		AgentsGatewayGetImagePullSecretAttachmentProcedure,
		svc.GetImagePullSecretAttachment,
		connect.WithSchema(agentsGatewayMethods.ByName("GetImagePullSecretAttachment")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayDeleteImagePullSecretAttachmentHandler := connect.NewUnaryHandler(
		AgentsGatewayDeleteImagePullSecretAttachmentProcedure,
		svc.DeleteImagePullSecretAttachment,
		connect.WithSchema(agentsGatewayMethods.ByName("DeleteImagePullSecretAttachment")),
		connect.WithHandlerOptions(opts...),
	)
	agentsGatewayListImagePullSecretAttachmentsHandler := connect.NewUnaryHandler(
		AgentsGatewayListImagePullSecretAttachmentsProcedure,
		svc.ListImagePullSecretAttachments,
		connect.WithSchema(agentsGatewayMethods.ByName("ListImagePullSecretAttachments")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agynio.api.gateway.v1.AgentsGateway/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentsGatewayCreateAgentProcedure:
			agentsGatewayCreateAgentHandler.ServeHTTP(w, r)
		case AgentsGatewayGetAgentProcedure:
			agentsGatewayGetAgentHandler.ServeHTTP(w, r)
		case AgentsGatewayUpdateAgentProcedure:
			agentsGatewayUpdateAgentHandler.ServeHTTP(w, r)
		case AgentsGatewayDeleteAgentProcedure:
			agentsGatewayDeleteAgentHandler.ServeHTTP(w, r)
		case AgentsGatewayListAgentsProcedure:
			agentsGatewayListAgentsHandler.ServeHTTP(w, r)
		case AgentsGatewayCreateVolumeProcedure:
			agentsGatewayCreateVolumeHandler.ServeHTTP(w, r)
		case AgentsGatewayGetVolumeProcedure:
			agentsGatewayGetVolumeHandler.ServeHTTP(w, r)
		case AgentsGatewayUpdateVolumeProcedure:
			agentsGatewayUpdateVolumeHandler.ServeHTTP(w, r)
		case AgentsGatewayDeleteVolumeProcedure:
			agentsGatewayDeleteVolumeHandler.ServeHTTP(w, r)
		case AgentsGatewayListVolumesProcedure:
			agentsGatewayListVolumesHandler.ServeHTTP(w, r)
		case AgentsGatewayCreateVolumeAttachmentProcedure:
			agentsGatewayCreateVolumeAttachmentHandler.ServeHTTP(w, r)
		case AgentsGatewayGetVolumeAttachmentProcedure:
			agentsGatewayGetVolumeAttachmentHandler.ServeHTTP(w, r)
		case AgentsGatewayDeleteVolumeAttachmentProcedure:
			agentsGatewayDeleteVolumeAttachmentHandler.ServeHTTP(w, r)
		case AgentsGatewayListVolumeAttachmentsProcedure:
			agentsGatewayListVolumeAttachmentsHandler.ServeHTTP(w, r)
		case AgentsGatewayCreateMcpProcedure:
			agentsGatewayCreateMcpHandler.ServeHTTP(w, r)
		case AgentsGatewayGetMcpProcedure:
			agentsGatewayGetMcpHandler.ServeHTTP(w, r)
		case AgentsGatewayUpdateMcpProcedure:
			agentsGatewayUpdateMcpHandler.ServeHTTP(w, r)
		case AgentsGatewayDeleteMcpProcedure:
			agentsGatewayDeleteMcpHandler.ServeHTTP(w, r)
		case AgentsGatewayListMcpsProcedure:
			agentsGatewayListMcpsHandler.ServeHTTP(w, r)
		case AgentsGatewayCreateSkillProcedure:
			agentsGatewayCreateSkillHandler.ServeHTTP(w, r)
		case AgentsGatewayGetSkillProcedure:
			agentsGatewayGetSkillHandler.ServeHTTP(w, r)
		case AgentsGatewayUpdateSkillProcedure:
			agentsGatewayUpdateSkillHandler.ServeHTTP(w, r)
		case AgentsGatewayDeleteSkillProcedure:
			agentsGatewayDeleteSkillHandler.ServeHTTP(w, r)
		case AgentsGatewayListSkillsProcedure:
			agentsGatewayListSkillsHandler.ServeHTTP(w, r)
		case AgentsGatewayCreateHookProcedure:
			agentsGatewayCreateHookHandler.ServeHTTP(w, r)
		case AgentsGatewayGetHookProcedure:
			agentsGatewayGetHookHandler.ServeHTTP(w, r)
		case AgentsGatewayUpdateHookProcedure:
			agentsGatewayUpdateHookHandler.ServeHTTP(w, r)
		case AgentsGatewayDeleteHookProcedure:
			agentsGatewayDeleteHookHandler.ServeHTTP(w, r)
		case AgentsGatewayListHooksProcedure:
			agentsGatewayListHooksHandler.ServeHTTP(w, r)
		case AgentsGatewayCreateEnvProcedure:
			agentsGatewayCreateEnvHandler.ServeHTTP(w, r)
		case AgentsGatewayGetEnvProcedure:
			agentsGatewayGetEnvHandler.ServeHTTP(w, r)
		case AgentsGatewayUpdateEnvProcedure:
			agentsGatewayUpdateEnvHandler.ServeHTTP(w, r)
		case AgentsGatewayDeleteEnvProcedure:
			agentsGatewayDeleteEnvHandler.ServeHTTP(w, r)
		case AgentsGatewayListEnvsProcedure:
			agentsGatewayListEnvsHandler.ServeHTTP(w, r)
		case AgentsGatewayCreateInitScriptProcedure:
			agentsGatewayCreateInitScriptHandler.ServeHTTP(w, r)
		case AgentsGatewayGetInitScriptProcedure:
			agentsGatewayGetInitScriptHandler.ServeHTTP(w, r)
		case AgentsGatewayUpdateInitScriptProcedure:
			agentsGatewayUpdateInitScriptHandler.ServeHTTP(w, r)
		case AgentsGatewayDeleteInitScriptProcedure:
			agentsGatewayDeleteInitScriptHandler.ServeHTTP(w, r)
		case AgentsGatewayListInitScriptsProcedure:
			agentsGatewayListInitScriptsHandler.ServeHTTP(w, r)
		case AgentsGatewayCreateImagePullSecretAttachmentProcedure:
			agentsGatewayCreateImagePullSecretAttachmentHandler.ServeHTTP(w, r)
		case AgentsGatewayGetImagePullSecretAttachmentProcedure:
			agentsGatewayGetImagePullSecretAttachmentHandler.ServeHTTP(w, r)
		case AgentsGatewayDeleteImagePullSecretAttachmentProcedure:
			agentsGatewayDeleteImagePullSecretAttachmentHandler.ServeHTTP(w, r)
		case AgentsGatewayListImagePullSecretAttachmentsProcedure:
			agentsGatewayListImagePullSecretAttachmentsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentsGatewayHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentsGatewayHandler struct{}

func (UnimplementedAgentsGatewayHandler) CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.CreateAgent is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.GetAgent is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) UpdateAgent(context.Context, *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.UpdateAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.UpdateAgent is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) DeleteAgent(context.Context, *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[v1.DeleteAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.DeleteAgent is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.ListAgents is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) CreateVolume(context.Context, *connect.Request[v1.CreateVolumeRequest]) (*connect.Response[v1.CreateVolumeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.CreateVolume is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) GetVolume(context.Context, *connect.Request[v1.GetVolumeRequest]) (*connect.Response[v1.GetVolumeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.GetVolume is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) UpdateVolume(context.Context, *connect.Request[v1.UpdateVolumeRequest]) (*connect.Response[v1.UpdateVolumeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.UpdateVolume is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) DeleteVolume(context.Context, *connect.Request[v1.DeleteVolumeRequest]) (*connect.Response[v1.DeleteVolumeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.DeleteVolume is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) ListVolumes(context.Context, *connect.Request[v1.ListVolumesRequest]) (*connect.Response[v1.ListVolumesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.ListVolumes is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) CreateVolumeAttachment(context.Context, *connect.Request[v1.CreateVolumeAttachmentRequest]) (*connect.Response[v1.CreateVolumeAttachmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.CreateVolumeAttachment is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) GetVolumeAttachment(context.Context, *connect.Request[v1.GetVolumeAttachmentRequest]) (*connect.Response[v1.GetVolumeAttachmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.GetVolumeAttachment is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) DeleteVolumeAttachment(context.Context, *connect.Request[v1.DeleteVolumeAttachmentRequest]) (*connect.Response[v1.DeleteVolumeAttachmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.DeleteVolumeAttachment is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) ListVolumeAttachments(context.Context, *connect.Request[v1.ListVolumeAttachmentsRequest]) (*connect.Response[v1.ListVolumeAttachmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.ListVolumeAttachments is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) CreateMcp(context.Context, *connect.Request[v1.CreateMcpRequest]) (*connect.Response[v1.CreateMcpResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.CreateMcp is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) GetMcp(context.Context, *connect.Request[v1.GetMcpRequest]) (*connect.Response[v1.GetMcpResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.GetMcp is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) UpdateMcp(context.Context, *connect.Request[v1.UpdateMcpRequest]) (*connect.Response[v1.UpdateMcpResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.UpdateMcp is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) DeleteMcp(context.Context, *connect.Request[v1.DeleteMcpRequest]) (*connect.Response[v1.DeleteMcpResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.DeleteMcp is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) ListMcps(context.Context, *connect.Request[v1.ListMcpsRequest]) (*connect.Response[v1.ListMcpsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.ListMcps is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) CreateSkill(context.Context, *connect.Request[v1.CreateSkillRequest]) (*connect.Response[v1.CreateSkillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.CreateSkill is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) GetSkill(context.Context, *connect.Request[v1.GetSkillRequest]) (*connect.Response[v1.GetSkillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.GetSkill is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) UpdateSkill(context.Context, *connect.Request[v1.UpdateSkillRequest]) (*connect.Response[v1.UpdateSkillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.UpdateSkill is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) DeleteSkill(context.Context, *connect.Request[v1.DeleteSkillRequest]) (*connect.Response[v1.DeleteSkillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.DeleteSkill is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.ListSkills is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) CreateHook(context.Context, *connect.Request[v1.CreateHookRequest]) (*connect.Response[v1.CreateHookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.CreateHook is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) GetHook(context.Context, *connect.Request[v1.GetHookRequest]) (*connect.Response[v1.GetHookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.GetHook is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) UpdateHook(context.Context, *connect.Request[v1.UpdateHookRequest]) (*connect.Response[v1.UpdateHookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.UpdateHook is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) DeleteHook(context.Context, *connect.Request[v1.DeleteHookRequest]) (*connect.Response[v1.DeleteHookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.DeleteHook is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) ListHooks(context.Context, *connect.Request[v1.ListHooksRequest]) (*connect.Response[v1.ListHooksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.ListHooks is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) CreateEnv(context.Context, *connect.Request[v1.CreateEnvRequest]) (*connect.Response[v1.CreateEnvResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.CreateEnv is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) GetEnv(context.Context, *connect.Request[v1.GetEnvRequest]) (*connect.Response[v1.GetEnvResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.GetEnv is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) UpdateEnv(context.Context, *connect.Request[v1.UpdateEnvRequest]) (*connect.Response[v1.UpdateEnvResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.UpdateEnv is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) DeleteEnv(context.Context, *connect.Request[v1.DeleteEnvRequest]) (*connect.Response[v1.DeleteEnvResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.DeleteEnv is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) ListEnvs(context.Context, *connect.Request[v1.ListEnvsRequest]) (*connect.Response[v1.ListEnvsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.ListEnvs is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) CreateInitScript(context.Context, *connect.Request[v1.CreateInitScriptRequest]) (*connect.Response[v1.CreateInitScriptResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.CreateInitScript is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) GetInitScript(context.Context, *connect.Request[v1.GetInitScriptRequest]) (*connect.Response[v1.GetInitScriptResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.GetInitScript is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) UpdateInitScript(context.Context, *connect.Request[v1.UpdateInitScriptRequest]) (*connect.Response[v1.UpdateInitScriptResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.UpdateInitScript is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) DeleteInitScript(context.Context, *connect.Request[v1.DeleteInitScriptRequest]) (*connect.Response[v1.DeleteInitScriptResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.DeleteInitScript is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) ListInitScripts(context.Context, *connect.Request[v1.ListInitScriptsRequest]) (*connect.Response[v1.ListInitScriptsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.ListInitScripts is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) CreateImagePullSecretAttachment(context.Context, *connect.Request[v1.CreateImagePullSecretAttachmentRequest]) (*connect.Response[v1.CreateImagePullSecretAttachmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.CreateImagePullSecretAttachment is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) GetImagePullSecretAttachment(context.Context, *connect.Request[v1.GetImagePullSecretAttachmentRequest]) (*connect.Response[v1.GetImagePullSecretAttachmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.GetImagePullSecretAttachment is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) DeleteImagePullSecretAttachment(context.Context, *connect.Request[v1.DeleteImagePullSecretAttachmentRequest]) (*connect.Response[v1.DeleteImagePullSecretAttachmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.DeleteImagePullSecretAttachment is not implemented"))
}

func (UnimplementedAgentsGatewayHandler) ListImagePullSecretAttachments(context.Context, *connect.Request[v1.ListImagePullSecretAttachmentsRequest]) (*connect.Response[v1.ListImagePullSecretAttachmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.AgentsGateway.ListImagePullSecretAttachments is not implemented"))
}
