// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agynio/api/gateway/v1/llm.proto

package gatewayv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v11 "github.com/agynio/e2e/suites/go-core/.gen/go/agynio/api/gateway/v1"
	v1 "github.com/agynio/e2e/suites/go-core/.gen/go/agynio/api/llm/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LLMGatewayName is the fully-qualified name of the LLMGateway service.
	LLMGatewayName = "agynio.api.gateway.v1.LLMGateway"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LLMGatewayCreateLLMProviderProcedure is the fully-qualified name of the LLMGateway's
	// CreateLLMProvider RPC.
	LLMGatewayCreateLLMProviderProcedure = "/agynio.api.gateway.v1.LLMGateway/CreateLLMProvider"
	// LLMGatewayGetLLMProviderProcedure is the fully-qualified name of the LLMGateway's GetLLMProvider
	// RPC.
	LLMGatewayGetLLMProviderProcedure = "/agynio.api.gateway.v1.LLMGateway/GetLLMProvider"
	// LLMGatewayUpdateLLMProviderProcedure is the fully-qualified name of the LLMGateway's
	// UpdateLLMProvider RPC.
	LLMGatewayUpdateLLMProviderProcedure = "/agynio.api.gateway.v1.LLMGateway/UpdateLLMProvider"
	// LLMGatewayDeleteLLMProviderProcedure is the fully-qualified name of the LLMGateway's
	// DeleteLLMProvider RPC.
	LLMGatewayDeleteLLMProviderProcedure = "/agynio.api.gateway.v1.LLMGateway/DeleteLLMProvider"
	// LLMGatewayListLLMProvidersProcedure is the fully-qualified name of the LLMGateway's
	// ListLLMProviders RPC.
	LLMGatewayListLLMProvidersProcedure = "/agynio.api.gateway.v1.LLMGateway/ListLLMProviders"
	// LLMGatewayCreateModelProcedure is the fully-qualified name of the LLMGateway's CreateModel RPC.
	LLMGatewayCreateModelProcedure = "/agynio.api.gateway.v1.LLMGateway/CreateModel"
	// LLMGatewayGetModelProcedure is the fully-qualified name of the LLMGateway's GetModel RPC.
	LLMGatewayGetModelProcedure = "/agynio.api.gateway.v1.LLMGateway/GetModel"
	// LLMGatewayUpdateModelProcedure is the fully-qualified name of the LLMGateway's UpdateModel RPC.
	LLMGatewayUpdateModelProcedure = "/agynio.api.gateway.v1.LLMGateway/UpdateModel"
	// LLMGatewayDeleteModelProcedure is the fully-qualified name of the LLMGateway's DeleteModel RPC.
	LLMGatewayDeleteModelProcedure = "/agynio.api.gateway.v1.LLMGateway/DeleteModel"
	// LLMGatewayListModelsProcedure is the fully-qualified name of the LLMGateway's ListModels RPC.
	LLMGatewayListModelsProcedure = "/agynio.api.gateway.v1.LLMGateway/ListModels"
	// LLMGatewayCreateSubscriptionProcedure is the fully-qualified name of the LLMGateway's
	// CreateSubscription RPC.
	LLMGatewayCreateSubscriptionProcedure = "/agynio.api.gateway.v1.LLMGateway/CreateSubscription"
	// LLMGatewayGetSubscriptionProcedure is the fully-qualified name of the LLMGateway's
	// GetSubscription RPC.
	LLMGatewayGetSubscriptionProcedure = "/agynio.api.gateway.v1.LLMGateway/GetSubscription"
	// LLMGatewayUpdateSubscriptionProcedure is the fully-qualified name of the LLMGateway's
	// UpdateSubscription RPC.
	LLMGatewayUpdateSubscriptionProcedure = "/agynio.api.gateway.v1.LLMGateway/UpdateSubscription"
	// LLMGatewayDeleteSubscriptionProcedure is the fully-qualified name of the LLMGateway's
	// DeleteSubscription RPC.
	LLMGatewayDeleteSubscriptionProcedure = "/agynio.api.gateway.v1.LLMGateway/DeleteSubscription"
	// LLMGatewayListSubscriptionsProcedure is the fully-qualified name of the LLMGateway's
	// ListSubscriptions RPC.
	LLMGatewayListSubscriptionsProcedure = "/agynio.api.gateway.v1.LLMGateway/ListSubscriptions"
	// LLMGatewayCreateSubscriptionAttachmentProcedure is the fully-qualified name of the LLMGateway's
	// CreateSubscriptionAttachment RPC.
	LLMGatewayCreateSubscriptionAttachmentProcedure = "/agynio.api.gateway.v1.LLMGateway/CreateSubscriptionAttachment"
	// LLMGatewayDeleteSubscriptionAttachmentProcedure is the fully-qualified name of the LLMGateway's
	// DeleteSubscriptionAttachment RPC.
	LLMGatewayDeleteSubscriptionAttachmentProcedure = "/agynio.api.gateway.v1.LLMGateway/DeleteSubscriptionAttachment"
	// LLMGatewayListSubscriptionAttachmentsProcedure is the fully-qualified name of the LLMGateway's
	// ListSubscriptionAttachments RPC.
	LLMGatewayListSubscriptionAttachmentsProcedure = "/agynio.api.gateway.v1.LLMGateway/ListSubscriptionAttachments"
	// LLMGatewayTestModelProcedure is the fully-qualified name of the LLMGateway's TestModel RPC.
	LLMGatewayTestModelProcedure = "/agynio.api.gateway.v1.LLMGateway/TestModel"
)

// LLMGatewayClient is a client for the agynio.api.gateway.v1.LLMGateway service.
type LLMGatewayClient interface {
	// --- Providers ---
	CreateLLMProvider(context.Context, *connect.Request[v1.CreateLLMProviderRequest]) (*connect.Response[v1.CreateLLMProviderResponse], error)
	GetLLMProvider(context.Context, *connect.Request[v1.GetLLMProviderRequest]) (*connect.Response[v1.GetLLMProviderResponse], error)
	UpdateLLMProvider(context.Context, *connect.Request[v1.UpdateLLMProviderRequest]) (*connect.Response[v1.UpdateLLMProviderResponse], error)
	DeleteLLMProvider(context.Context, *connect.Request[v1.DeleteLLMProviderRequest]) (*connect.Response[v1.DeleteLLMProviderResponse], error)
	ListLLMProviders(context.Context, *connect.Request[v1.ListLLMProvidersRequest]) (*connect.Response[v1.ListLLMProvidersResponse], error)
	// --- Models ---
	CreateModel(context.Context, *connect.Request[v1.CreateModelRequest]) (*connect.Response[v1.CreateModelResponse], error)
	GetModel(context.Context, *connect.Request[v1.GetModelRequest]) (*connect.Response[v1.GetModelResponse], error)
	UpdateModel(context.Context, *connect.Request[v1.UpdateModelRequest]) (*connect.Response[v1.UpdateModelResponse], error)
	DeleteModel(context.Context, *connect.Request[v1.DeleteModelRequest]) (*connect.Response[v1.DeleteModelResponse], error)
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
	// --- Subscriptions ---
	CreateSubscription(context.Context, *connect.Request[v1.CreateSubscriptionRequest]) (*connect.Response[v1.CreateSubscriptionResponse], error)
	GetSubscription(context.Context, *connect.Request[v1.GetSubscriptionRequest]) (*connect.Response[v1.GetSubscriptionResponse], error)
	UpdateSubscription(context.Context, *connect.Request[v1.UpdateSubscriptionRequest]) (*connect.Response[v1.UpdateSubscriptionResponse], error)
	DeleteSubscription(context.Context, *connect.Request[v1.DeleteSubscriptionRequest]) (*connect.Response[v1.DeleteSubscriptionResponse], error)
	ListSubscriptions(context.Context, *connect.Request[v1.ListSubscriptionsRequest]) (*connect.Response[v1.ListSubscriptionsResponse], error)
	// --- Subscription attachments ---
	CreateSubscriptionAttachment(context.Context, *connect.Request[v1.CreateSubscriptionAttachmentRequest]) (*connect.Response[v1.CreateSubscriptionAttachmentResponse], error)
	DeleteSubscriptionAttachment(context.Context, *connect.Request[v1.DeleteSubscriptionAttachmentRequest]) (*connect.Response[v1.DeleteSubscriptionAttachmentResponse], error)
	ListSubscriptionAttachments(context.Context, *connect.Request[v1.ListSubscriptionAttachmentsRequest]) (*connect.Response[v1.ListSubscriptionAttachmentsResponse], error)
	// --- Test ---
	TestModel(context.Context, *connect.Request[v1.TestModelRequest]) (*connect.Response[v1.TestModelResponse], error)
}

// NewLLMGatewayClient constructs a client for the agynio.api.gateway.v1.LLMGateway service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLLMGatewayClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LLMGatewayClient {
	baseURL = strings.TrimRight(baseURL, "/")
	lLMGatewayMethods := v11.File_agynio_api_gateway_v1_llm_proto.Services().ByName("LLMGateway").Methods()
	return &lLMGatewayClient{
		createLLMProvider: connect.NewClient[v1.CreateLLMProviderRequest, v1.CreateLLMProviderResponse](
			httpClient,
			baseURL+LLMGatewayCreateLLMProviderProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("CreateLLMProvider")),
			connect.WithClientOptions(opts...),
		),
		getLLMProvider: connect.NewClient[v1.GetLLMProviderRequest, v1.GetLLMProviderResponse](
			httpClient,
			baseURL+LLMGatewayGetLLMProviderProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("GetLLMProvider")),
			connect.WithClientOptions(opts...),
		),
		updateLLMProvider: connect.NewClient[v1.UpdateLLMProviderRequest, v1.UpdateLLMProviderResponse](
			httpClient,
			baseURL+LLMGatewayUpdateLLMProviderProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("UpdateLLMProvider")),
			connect.WithClientOptions(opts...),
		),
		deleteLLMProvider: connect.NewClient[v1.DeleteLLMProviderRequest, v1.DeleteLLMProviderResponse](
			httpClient,
			baseURL+LLMGatewayDeleteLLMProviderProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("DeleteLLMProvider")),
			connect.WithClientOptions(opts...),
		),
		listLLMProviders: connect.NewClient[v1.ListLLMProvidersRequest, v1.ListLLMProvidersResponse](
			httpClient,
			baseURL+LLMGatewayListLLMProvidersProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("ListLLMProviders")),
			connect.WithClientOptions(opts...),
		),
		createModel: connect.NewClient[v1.CreateModelRequest, v1.CreateModelResponse](
			httpClient,
			baseURL+LLMGatewayCreateModelProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("CreateModel")),
			connect.WithClientOptions(opts...),
		),
		getModel: connect.NewClient[v1.GetModelRequest, v1.GetModelResponse](
			httpClient,
			baseURL+LLMGatewayGetModelProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("GetModel")),
			connect.WithClientOptions(opts...),
		),
		updateModel: connect.NewClient[v1.UpdateModelRequest, v1.UpdateModelResponse](
			httpClient,
			baseURL+LLMGatewayUpdateModelProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("UpdateModel")),
			connect.WithClientOptions(opts...),
		),
		deleteModel: connect.NewClient[v1.DeleteModelRequest, v1.DeleteModelResponse](
			httpClient,
			baseURL+LLMGatewayDeleteModelProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("DeleteModel")),
			connect.WithClientOptions(opts...),
		),
		listModels: connect.NewClient[v1.ListModelsRequest, v1.ListModelsResponse](
			httpClient,
			baseURL+LLMGatewayListModelsProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("ListModels")),
			connect.WithClientOptions(opts...),
		),
		createSubscription: connect.NewClient[v1.CreateSubscriptionRequest, v1.CreateSubscriptionResponse](
			httpClient,
			baseURL+LLMGatewayCreateSubscriptionProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("CreateSubscription")),
			connect.WithClientOptions(opts...),
		),
		getSubscription: connect.NewClient[v1.GetSubscriptionRequest, v1.GetSubscriptionResponse](
			httpClient,
			baseURL+LLMGatewayGetSubscriptionProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("GetSubscription")),
			connect.WithClientOptions(opts...),
		),
		updateSubscription: connect.NewClient[v1.UpdateSubscriptionRequest, v1.UpdateSubscriptionResponse](
			httpClient,
			baseURL+LLMGatewayUpdateSubscriptionProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("UpdateSubscription")),
			connect.WithClientOptions(opts...),
		),
		deleteSubscription: connect.NewClient[v1.DeleteSubscriptionRequest, v1.DeleteSubscriptionResponse](
			httpClient,
			baseURL+LLMGatewayDeleteSubscriptionProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("DeleteSubscription")),
			connect.WithClientOptions(opts...),
		),
		listSubscriptions: connect.NewClient[v1.ListSubscriptionsRequest, v1.ListSubscriptionsResponse](
			httpClient,
			baseURL+LLMGatewayListSubscriptionsProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("ListSubscriptions")),
			connect.WithClientOptions(opts...),
		),
		createSubscriptionAttachment: connect.NewClient[v1.CreateSubscriptionAttachmentRequest, v1.CreateSubscriptionAttachmentResponse](
			httpClient,
			baseURL+LLMGatewayCreateSubscriptionAttachmentProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("CreateSubscriptionAttachment")),
			connect.WithClientOptions(opts...),
		),
		deleteSubscriptionAttachment: connect.NewClient[v1.DeleteSubscriptionAttachmentRequest, v1.DeleteSubscriptionAttachmentResponse](
			httpClient,
			baseURL+LLMGatewayDeleteSubscriptionAttachmentProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("DeleteSubscriptionAttachment")),
			connect.WithClientOptions(opts...),
		),
		listSubscriptionAttachments: connect.NewClient[v1.ListSubscriptionAttachmentsRequest, v1.ListSubscriptionAttachmentsResponse](
			httpClient,
			baseURL+LLMGatewayListSubscriptionAttachmentsProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("ListSubscriptionAttachments")),
			connect.WithClientOptions(opts...),
		),
		testModel: connect.NewClient[v1.TestModelRequest, v1.TestModelResponse](
			httpClient,
			baseURL+LLMGatewayTestModelProcedure,
			connect.WithSchema(lLMGatewayMethods.ByName("TestModel")),
			connect.WithClientOptions(opts...),
		),
	}
}

// lLMGatewayClient implements LLMGatewayClient.
type lLMGatewayClient struct {
	createLLMProvider            *connect.Client[v1.CreateLLMProviderRequest, v1.CreateLLMProviderResponse]
	getLLMProvider               *connect.Client[v1.GetLLMProviderRequest, v1.GetLLMProviderResponse]
	updateLLMProvider            *connect.Client[v1.UpdateLLMProviderRequest, v1.UpdateLLMProviderResponse]
	deleteLLMProvider            *connect.Client[v1.DeleteLLMProviderRequest, v1.DeleteLLMProviderResponse]
	listLLMProviders             *connect.Client[v1.ListLLMProvidersRequest, v1.ListLLMProvidersResponse]
	createModel                  *connect.Client[v1.CreateModelRequest, v1.CreateModelResponse]
	getModel                     *connect.Client[v1.GetModelRequest, v1.GetModelResponse]
	updateModel                  *connect.Client[v1.UpdateModelRequest, v1.UpdateModelResponse]
	deleteModel                  *connect.Client[v1.DeleteModelRequest, v1.DeleteModelResponse]
	listModels                   *connect.Client[v1.ListModelsRequest, v1.ListModelsResponse]
	createSubscription           *connect.Client[v1.CreateSubscriptionRequest, v1.CreateSubscriptionResponse]
	getSubscription              *connect.Client[v1.GetSubscriptionRequest, v1.GetSubscriptionResponse]
	updateSubscription           *connect.Client[v1.UpdateSubscriptionRequest, v1.UpdateSubscriptionResponse]
	deleteSubscription           *connect.Client[v1.DeleteSubscriptionRequest, v1.DeleteSubscriptionResponse]
	listSubscriptions            *connect.Client[v1.ListSubscriptionsRequest, v1.ListSubscriptionsResponse]
	createSubscriptionAttachment *connect.Client[v1.CreateSubscriptionAttachmentRequest, v1.CreateSubscriptionAttachmentResponse]
	deleteSubscriptionAttachment *connect.Client[v1.DeleteSubscriptionAttachmentRequest, v1.DeleteSubscriptionAttachmentResponse]
	listSubscriptionAttachments  *connect.Client[v1.ListSubscriptionAttachmentsRequest, v1.ListSubscriptionAttachmentsResponse]
	testModel                    *connect.Client[v1.TestModelRequest, v1.TestModelResponse]
}

// CreateLLMProvider calls agynio.api.gateway.v1.LLMGateway.CreateLLMProvider.
func (c *lLMGatewayClient) CreateLLMProvider(ctx context.Context, req *connect.Request[v1.CreateLLMProviderRequest]) (*connect.Response[v1.CreateLLMProviderResponse], error) {
	return c.createLLMProvider.CallUnary(ctx, req)
}

// GetLLMProvider calls agynio.api.gateway.v1.LLMGateway.GetLLMProvider.
func (c *lLMGatewayClient) GetLLMProvider(ctx context.Context, req *connect.Request[v1.GetLLMProviderRequest]) (*connect.Response[v1.GetLLMProviderResponse], error) {
	return c.getLLMProvider.CallUnary(ctx, req)
}

// UpdateLLMProvider calls agynio.api.gateway.v1.LLMGateway.UpdateLLMProvider.
func (c *lLMGatewayClient) UpdateLLMProvider(ctx context.Context, req *connect.Request[v1.UpdateLLMProviderRequest]) (*connect.Response[v1.UpdateLLMProviderResponse], error) {
	return c.updateLLMProvider.CallUnary(ctx, req)
}

// DeleteLLMProvider calls agynio.api.gateway.v1.LLMGateway.DeleteLLMProvider.
func (c *lLMGatewayClient) DeleteLLMProvider(ctx context.Context, req *connect.Request[v1.DeleteLLMProviderRequest]) (*connect.Response[v1.DeleteLLMProviderResponse], error) {
	return c.deleteLLMProvider.CallUnary(ctx, req)
}

// ListLLMProviders calls agynio.api.gateway.v1.LLMGateway.ListLLMProviders.
func (c *lLMGatewayClient) ListLLMProviders(ctx context.Context, req *connect.Request[v1.ListLLMProvidersRequest]) (*connect.Response[v1.ListLLMProvidersResponse], error) {
	return c.listLLMProviders.CallUnary(ctx, req)
}

// CreateModel calls agynio.api.gateway.v1.LLMGateway.CreateModel.
func (c *lLMGatewayClient) CreateModel(ctx context.Context, req *connect.Request[v1.CreateModelRequest]) (*connect.Response[v1.CreateModelResponse], error) {
	return c.createModel.CallUnary(ctx, req)
}

// GetModel calls agynio.api.gateway.v1.LLMGateway.GetModel.
func (c *lLMGatewayClient) GetModel(ctx context.Context, req *connect.Request[v1.GetModelRequest]) (*connect.Response[v1.GetModelResponse], error) {
	return c.getModel.CallUnary(ctx, req)
}

// UpdateModel calls agynio.api.gateway.v1.LLMGateway.UpdateModel.
func (c *lLMGatewayClient) UpdateModel(ctx context.Context, req *connect.Request[v1.UpdateModelRequest]) (*connect.Response[v1.UpdateModelResponse], error) {
	return c.updateModel.CallUnary(ctx, req)
}

// DeleteModel calls agynio.api.gateway.v1.LLMGateway.DeleteModel.
func (c *lLMGatewayClient) DeleteModel(ctx context.Context, req *connect.Request[v1.DeleteModelRequest]) (*connect.Response[v1.DeleteModelResponse], error) {
	return c.deleteModel.CallUnary(ctx, req)
}

// ListModels calls agynio.api.gateway.v1.LLMGateway.ListModels.
func (c *lLMGatewayClient) ListModels(ctx context.Context, req *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return c.listModels.CallUnary(ctx, req)
}

// CreateSubscription calls agynio.api.gateway.v1.LLMGateway.CreateSubscription.
func (c *lLMGatewayClient) CreateSubscription(ctx context.Context, req *connect.Request[v1.CreateSubscriptionRequest]) (*connect.Response[v1.CreateSubscriptionResponse], error) {
	return c.createSubscription.CallUnary(ctx, req)
}

// GetSubscription calls agynio.api.gateway.v1.LLMGateway.GetSubscription.
func (c *lLMGatewayClient) GetSubscription(ctx context.Context, req *connect.Request[v1.GetSubscriptionRequest]) (*connect.Response[v1.GetSubscriptionResponse], error) {
	return c.getSubscription.CallUnary(ctx, req)
}

// UpdateSubscription calls agynio.api.gateway.v1.LLMGateway.UpdateSubscription.
func (c *lLMGatewayClient) UpdateSubscription(ctx context.Context, req *connect.Request[v1.UpdateSubscriptionRequest]) (*connect.Response[v1.UpdateSubscriptionResponse], error) {
	return c.updateSubscription.CallUnary(ctx, req)
}

// DeleteSubscription calls agynio.api.gateway.v1.LLMGateway.DeleteSubscription.
func (c *lLMGatewayClient) DeleteSubscription(ctx context.Context, req *connect.Request[v1.DeleteSubscriptionRequest]) (*connect.Response[v1.DeleteSubscriptionResponse], error) {
	return c.deleteSubscription.CallUnary(ctx, req)
}

// ListSubscriptions calls agynio.api.gateway.v1.LLMGateway.ListSubscriptions.
func (c *lLMGatewayClient) ListSubscriptions(ctx context.Context, req *connect.Request[v1.ListSubscriptionsRequest]) (*connect.Response[v1.ListSubscriptionsResponse], error) {
	return c.listSubscriptions.CallUnary(ctx, req)
}

// CreateSubscriptionAttachment calls agynio.api.gateway.v1.LLMGateway.CreateSubscriptionAttachment.
func (c *lLMGatewayClient) CreateSubscriptionAttachment(ctx context.Context, req *connect.Request[v1.CreateSubscriptionAttachmentRequest]) (*connect.Response[v1.CreateSubscriptionAttachmentResponse], error) {
	return c.createSubscriptionAttachment.CallUnary(ctx, req)
}

// DeleteSubscriptionAttachment calls agynio.api.gateway.v1.LLMGateway.DeleteSubscriptionAttachment.
func (c *lLMGatewayClient) DeleteSubscriptionAttachment(ctx context.Context, req *connect.Request[v1.DeleteSubscriptionAttachmentRequest]) (*connect.Response[v1.DeleteSubscriptionAttachmentResponse], error) {
	return c.deleteSubscriptionAttachment.CallUnary(ctx, req)
}

// ListSubscriptionAttachments calls agynio.api.gateway.v1.LLMGateway.ListSubscriptionAttachments.
func (c *lLMGatewayClient) ListSubscriptionAttachments(ctx context.Context, req *connect.Request[v1.ListSubscriptionAttachmentsRequest]) (*connect.Response[v1.ListSubscriptionAttachmentsResponse], error) {
	return c.listSubscriptionAttachments.CallUnary(ctx, req)
}

// TestModel calls agynio.api.gateway.v1.LLMGateway.TestModel.
func (c *lLMGatewayClient) TestModel(ctx context.Context, req *connect.Request[v1.TestModelRequest]) (*connect.Response[v1.TestModelResponse], error) {
	return c.testModel.CallUnary(ctx, req)
}

// LLMGatewayHandler is an implementation of the agynio.api.gateway.v1.LLMGateway service.
type LLMGatewayHandler interface {
	// --- Providers ---
	CreateLLMProvider(context.Context, *connect.Request[v1.CreateLLMProviderRequest]) (*connect.Response[v1.CreateLLMProviderResponse], error)
	GetLLMProvider(context.Context, *connect.Request[v1.GetLLMProviderRequest]) (*connect.Response[v1.GetLLMProviderResponse], error)
	UpdateLLMProvider(context.Context, *connect.Request[v1.UpdateLLMProviderRequest]) (*connect.Response[v1.UpdateLLMProviderResponse], error)
	DeleteLLMProvider(context.Context, *connect.Request[v1.DeleteLLMProviderRequest]) (*connect.Response[v1.DeleteLLMProviderResponse], error)
	ListLLMProviders(context.Context, *connect.Request[v1.ListLLMProvidersRequest]) (*connect.Response[v1.ListLLMProvidersResponse], error)
	// --- Models ---
	CreateModel(context.Context, *connect.Request[v1.CreateModelRequest]) (*connect.Response[v1.CreateModelResponse], error)
	GetModel(context.Context, *connect.Request[v1.GetModelRequest]) (*connect.Response[v1.GetModelResponse], error)
	UpdateModel(context.Context, *connect.Request[v1.UpdateModelRequest]) (*connect.Response[v1.UpdateModelResponse], error)
	DeleteModel(context.Context, *connect.Request[v1.DeleteModelRequest]) (*connect.Response[v1.DeleteModelResponse], error)
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
	// --- Subscriptions ---
	CreateSubscription(context.Context, *connect.Request[v1.CreateSubscriptionRequest]) (*connect.Response[v1.CreateSubscriptionResponse], error)
	GetSubscription(context.Context, *connect.Request[v1.GetSubscriptionRequest]) (*connect.Response[v1.GetSubscriptionResponse], error)
	UpdateSubscription(context.Context, *connect.Request[v1.UpdateSubscriptionRequest]) (*connect.Response[v1.UpdateSubscriptionResponse], error)
	DeleteSubscription(context.Context, *connect.Request[v1.DeleteSubscriptionRequest]) (*connect.Response[v1.DeleteSubscriptionResponse], error)
	ListSubscriptions(context.Context, *connect.Request[v1.ListSubscriptionsRequest]) (*connect.Response[v1.ListSubscriptionsResponse], error)
	// --- Subscription attachments ---
	CreateSubscriptionAttachment(context.Context, *connect.Request[v1.CreateSubscriptionAttachmentRequest]) (*connect.Response[v1.CreateSubscriptionAttachmentResponse], error)
	DeleteSubscriptionAttachment(context.Context, *connect.Request[v1.DeleteSubscriptionAttachmentRequest]) (*connect.Response[v1.DeleteSubscriptionAttachmentResponse], error)
	ListSubscriptionAttachments(context.Context, *connect.Request[v1.ListSubscriptionAttachmentsRequest]) (*connect.Response[v1.ListSubscriptionAttachmentsResponse], error)
	// --- Test ---
	TestModel(context.Context, *connect.Request[v1.TestModelRequest]) (*connect.Response[v1.TestModelResponse], error)
}

// NewLLMGatewayHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLLMGatewayHandler(svc LLMGatewayHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	lLMGatewayMethods := v11.File_agynio_api_gateway_v1_llm_proto.Services().ByName("LLMGateway").Methods()
	lLMGatewayCreateLLMProviderHandler := connect.NewUnaryHandler(
		LLMGatewayCreateLLMProviderProcedure,
		svc.CreateLLMProvider,
		connect.WithSchema(lLMGatewayMethods.ByName("CreateLLMProvider")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayGetLLMProviderHandler := connect.NewUnaryHandler(
		LLMGatewayGetLLMProviderProcedure,
		svc.GetLLMProvider,
		connect.WithSchema(lLMGatewayMethods.ByName("GetLLMProvider")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayUpdateLLMProviderHandler := connect.NewUnaryHandler(
		LLMGatewayUpdateLLMProviderProcedure,
		svc.UpdateLLMProvider,
		connect.WithSchema(lLMGatewayMethods.ByName("UpdateLLMProvider")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayDeleteLLMProviderHandler := connect.NewUnaryHandler(
		LLMGatewayDeleteLLMProviderProcedure,
		svc.DeleteLLMProvider,
		connect.WithSchema(lLMGatewayMethods.ByName("DeleteLLMProvider")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayListLLMProvidersHandler := connect.NewUnaryHandler(
		LLMGatewayListLLMProvidersProcedure,
		svc.ListLLMProviders,
		connect.WithSchema(lLMGatewayMethods.ByName("ListLLMProviders")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayCreateModelHandler := connect.NewUnaryHandler(
		LLMGatewayCreateModelProcedure,
		svc.CreateModel,
		connect.WithSchema(lLMGatewayMethods.ByName("CreateModel")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayGetModelHandler := connect.NewUnaryHandler(
		LLMGatewayGetModelProcedure,
		svc.GetModel,
		connect.WithSchema(lLMGatewayMethods.ByName("GetModel")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayUpdateModelHandler := connect.NewUnaryHandler(
		LLMGatewayUpdateModelProcedure,
		svc.UpdateModel,
		connect.WithSchema(lLMGatewayMethods.ByName("UpdateModel")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayDeleteModelHandler := connect.NewUnaryHandler(
		LLMGatewayDeleteModelProcedure,
		svc.DeleteModel,
		connect.WithSchema(lLMGatewayMethods.ByName("DeleteModel")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayListModelsHandler := connect.NewUnaryHandler(
		LLMGatewayListModelsProcedure,
		svc.ListModels,
		connect.WithSchema(lLMGatewayMethods.ByName("ListModels")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayCreateSubscriptionHandler := connect.NewUnaryHandler(
		LLMGatewayCreateSubscriptionProcedure,
		svc.CreateSubscription,
		connect.WithSchema(lLMGatewayMethods.ByName("CreateSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayGetSubscriptionHandler := connect.NewUnaryHandler(
		LLMGatewayGetSubscriptionProcedure,
		svc.GetSubscription,
		connect.WithSchema(lLMGatewayMethods.ByName("GetSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayUpdateSubscriptionHandler := connect.NewUnaryHandler(
		LLMGatewayUpdateSubscriptionProcedure,
		svc.UpdateSubscription,
		connect.WithSchema(lLMGatewayMethods.ByName("UpdateSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayDeleteSubscriptionHandler := connect.NewUnaryHandler(
		LLMGatewayDeleteSubscriptionProcedure,
		svc.DeleteSubscription,
		connect.WithSchema(lLMGatewayMethods.ByName("DeleteSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayListSubscriptionsHandler := connect.NewUnaryHandler(
		LLMGatewayListSubscriptionsProcedure,
		svc.ListSubscriptions,
		connect.WithSchema(lLMGatewayMethods.ByName("ListSubscriptions")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayCreateSubscriptionAttachmentHandler := connect.NewUnaryHandler(
		LLMGatewayCreateSubscriptionAttachmentProcedure,
		svc.CreateSubscriptionAttachment,
		connect.WithSchema(lLMGatewayMethods.ByName("CreateSubscriptionAttachment")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayDeleteSubscriptionAttachmentHandler := connect.NewUnaryHandler(
		LLMGatewayDeleteSubscriptionAttachmentProcedure,
		svc.DeleteSubscriptionAttachment,
		connect.WithSchema(lLMGatewayMethods.ByName("DeleteSubscriptionAttachment")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayListSubscriptionAttachmentsHandler := connect.NewUnaryHandler(
		LLMGatewayListSubscriptionAttachmentsProcedure,
		svc.ListSubscriptionAttachments,
		connect.WithSchema(lLMGatewayMethods.ByName("ListSubscriptionAttachments")),
		connect.WithHandlerOptions(opts...),
	)
	lLMGatewayTestModelHandler := connect.NewUnaryHandler(
		LLMGatewayTestModelProcedure,
		svc.TestModel,
		connect.WithSchema(lLMGatewayMethods.ByName("TestModel")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agynio.api.gateway.v1.LLMGateway/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LLMGatewayCreateLLMProviderProcedure:
			lLMGatewayCreateLLMProviderHandler.ServeHTTP(w, r)
		case LLMGatewayGetLLMProviderProcedure:
			lLMGatewayGetLLMProviderHandler.ServeHTTP(w, r)
		case LLMGatewayUpdateLLMProviderProcedure:
			lLMGatewayUpdateLLMProviderHandler.ServeHTTP(w, r)
		case LLMGatewayDeleteLLMProviderProcedure:
			lLMGatewayDeleteLLMProviderHandler.ServeHTTP(w, r)
		case LLMGatewayListLLMProvidersProcedure:
			lLMGatewayListLLMProvidersHandler.ServeHTTP(w, r)
		case LLMGatewayCreateModelProcedure:
			lLMGatewayCreateModelHandler.ServeHTTP(w, r)
		case LLMGatewayGetModelProcedure:
			lLMGatewayGetModelHandler.ServeHTTP(w, r)
		case LLMGatewayUpdateModelProcedure:
			lLMGatewayUpdateModelHandler.ServeHTTP(w, r)
		case LLMGatewayDeleteModelProcedure:
			lLMGatewayDeleteModelHandler.ServeHTTP(w, r)
		case LLMGatewayListModelsProcedure:
			lLMGatewayListModelsHandler.ServeHTTP(w, r)
		case LLMGatewayCreateSubscriptionProcedure:
			lLMGatewayCreateSubscriptionHandler.ServeHTTP(w, r)
		case LLMGatewayGetSubscriptionProcedure:
			lLMGatewayGetSubscriptionHandler.ServeHTTP(w, r)
		case LLMGatewayUpdateSubscriptionProcedure:
			lLMGatewayUpdateSubscriptionHandler.ServeHTTP(w, r)
		case LLMGatewayDeleteSubscriptionProcedure:
			lLMGatewayDeleteSubscriptionHandler.ServeHTTP(w, r)
		case LLMGatewayListSubscriptionsProcedure:
			lLMGatewayListSubscriptionsHandler.ServeHTTP(w, r)
		case LLMGatewayCreateSubscriptionAttachmentProcedure:
			lLMGatewayCreateSubscriptionAttachmentHandler.ServeHTTP(w, r)
		case LLMGatewayDeleteSubscriptionAttachmentProcedure:
			lLMGatewayDeleteSubscriptionAttachmentHandler.ServeHTTP(w, r)
		case LLMGatewayListSubscriptionAttachmentsProcedure:
			lLMGatewayListSubscriptionAttachmentsHandler.ServeHTTP(w, r)
		case LLMGatewayTestModelProcedure:
			lLMGatewayTestModelHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLLMGatewayHandler returns CodeUnimplemented from all methods.
type UnimplementedLLMGatewayHandler struct{}

func (UnimplementedLLMGatewayHandler) CreateLLMProvider(context.Context, *connect.Request[v1.CreateLLMProviderRequest]) (*connect.Response[v1.CreateLLMProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.CreateLLMProvider is not implemented"))
}

func (UnimplementedLLMGatewayHandler) GetLLMProvider(context.Context, *connect.Request[v1.GetLLMProviderRequest]) (*connect.Response[v1.GetLLMProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.GetLLMProvider is not implemented"))
}

func (UnimplementedLLMGatewayHandler) UpdateLLMProvider(context.Context, *connect.Request[v1.UpdateLLMProviderRequest]) (*connect.Response[v1.UpdateLLMProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.UpdateLLMProvider is not implemented"))
}

func (UnimplementedLLMGatewayHandler) DeleteLLMProvider(context.Context, *connect.Request[v1.DeleteLLMProviderRequest]) (*connect.Response[v1.DeleteLLMProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.DeleteLLMProvider is not implemented"))
}

func (UnimplementedLLMGatewayHandler) ListLLMProviders(context.Context, *connect.Request[v1.ListLLMProvidersRequest]) (*connect.Response[v1.ListLLMProvidersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.ListLLMProviders is not implemented"))
}

func (UnimplementedLLMGatewayHandler) CreateModel(context.Context, *connect.Request[v1.CreateModelRequest]) (*connect.Response[v1.CreateModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.CreateModel is not implemented"))
}

func (UnimplementedLLMGatewayHandler) GetModel(context.Context, *connect.Request[v1.GetModelRequest]) (*connect.Response[v1.GetModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.GetModel is not implemented"))
}

func (UnimplementedLLMGatewayHandler) UpdateModel(context.Context, *connect.Request[v1.UpdateModelRequest]) (*connect.Response[v1.UpdateModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.UpdateModel is not implemented"))
}

func (UnimplementedLLMGatewayHandler) DeleteModel(context.Context, *connect.Request[v1.DeleteModelRequest]) (*connect.Response[v1.DeleteModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.DeleteModel is not implemented"))
}

func (UnimplementedLLMGatewayHandler) ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.ListModels is not implemented"))
}

func (UnimplementedLLMGatewayHandler) CreateSubscription(context.Context, *connect.Request[v1.CreateSubscriptionRequest]) (*connect.Response[v1.CreateSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.CreateSubscription is not implemented"))
}

func (UnimplementedLLMGatewayHandler) GetSubscription(context.Context, *connect.Request[v1.GetSubscriptionRequest]) (*connect.Response[v1.GetSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.GetSubscription is not implemented"))
}

func (UnimplementedLLMGatewayHandler) UpdateSubscription(context.Context, *connect.Request[v1.UpdateSubscriptionRequest]) (*connect.Response[v1.UpdateSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.UpdateSubscription is not implemented"))
}

func (UnimplementedLLMGatewayHandler) DeleteSubscription(context.Context, *connect.Request[v1.DeleteSubscriptionRequest]) (*connect.Response[v1.DeleteSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.DeleteSubscription is not implemented"))
}

func (UnimplementedLLMGatewayHandler) ListSubscriptions(context.Context, *connect.Request[v1.ListSubscriptionsRequest]) (*connect.Response[v1.ListSubscriptionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.ListSubscriptions is not implemented"))
}

func (UnimplementedLLMGatewayHandler) CreateSubscriptionAttachment(context.Context, *connect.Request[v1.CreateSubscriptionAttachmentRequest]) (*connect.Response[v1.CreateSubscriptionAttachmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.CreateSubscriptionAttachment is not implemented"))
}

func (UnimplementedLLMGatewayHandler) DeleteSubscriptionAttachment(context.Context, *connect.Request[v1.DeleteSubscriptionAttachmentRequest]) (*connect.Response[v1.DeleteSubscriptionAttachmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.DeleteSubscriptionAttachment is not implemented"))
}

func (UnimplementedLLMGatewayHandler) ListSubscriptionAttachments(context.Context, *connect.Request[v1.ListSubscriptionAttachmentsRequest]) (*connect.Response[v1.ListSubscriptionAttachmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.ListSubscriptionAttachments is not implemented"))
}

func (UnimplementedLLMGatewayHandler) TestModel(context.Context, *connect.Request[v1.TestModelRequest]) (*connect.Response[v1.TestModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.gateway.v1.LLMGateway.TestModel is not implemented"))
}
