// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agynio/api/ziti_management/v1/ziti_management.proto

package ziti_managementv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/agynio/e2e/suites/go-core/.gen/go/agynio/api/ziti_management/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ZitiManagementServiceName is the fully-qualified name of the ZitiManagementService service.
	ZitiManagementServiceName = "agynio.api.ziti_management.v1.ZitiManagementService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ZitiManagementServiceCreateAgentIdentityProcedure is the fully-qualified name of the
	// ZitiManagementService's CreateAgentIdentity RPC.
	ZitiManagementServiceCreateAgentIdentityProcedure = "/agynio.api.ziti_management.v1.ZitiManagementService/CreateAgentIdentity"
	// ZitiManagementServiceCreateAppIdentityProcedure is the fully-qualified name of the
	// ZitiManagementService's CreateAppIdentity RPC.
	ZitiManagementServiceCreateAppIdentityProcedure = "/agynio.api.ziti_management.v1.ZitiManagementService/CreateAppIdentity"
	// ZitiManagementServiceCreateServiceProcedure is the fully-qualified name of the
	// ZitiManagementService's CreateService RPC.
	ZitiManagementServiceCreateServiceProcedure = "/agynio.api.ziti_management.v1.ZitiManagementService/CreateService"
	// ZitiManagementServiceDeleteIdentityProcedure is the fully-qualified name of the
	// ZitiManagementService's DeleteIdentity RPC.
	ZitiManagementServiceDeleteIdentityProcedure = "/agynio.api.ziti_management.v1.ZitiManagementService/DeleteIdentity"
	// ZitiManagementServiceDeleteAppIdentityProcedure is the fully-qualified name of the
	// ZitiManagementService's DeleteAppIdentity RPC.
	ZitiManagementServiceDeleteAppIdentityProcedure = "/agynio.api.ziti_management.v1.ZitiManagementService/DeleteAppIdentity"
	// ZitiManagementServiceCreateRunnerIdentityProcedure is the fully-qualified name of the
	// ZitiManagementService's CreateRunnerIdentity RPC.
	ZitiManagementServiceCreateRunnerIdentityProcedure = "/agynio.api.ziti_management.v1.ZitiManagementService/CreateRunnerIdentity"
	// ZitiManagementServiceDeleteRunnerIdentityProcedure is the fully-qualified name of the
	// ZitiManagementService's DeleteRunnerIdentity RPC.
	ZitiManagementServiceDeleteRunnerIdentityProcedure = "/agynio.api.ziti_management.v1.ZitiManagementService/DeleteRunnerIdentity"
	// ZitiManagementServiceListManagedIdentitiesProcedure is the fully-qualified name of the
	// ZitiManagementService's ListManagedIdentities RPC.
	ZitiManagementServiceListManagedIdentitiesProcedure = "/agynio.api.ziti_management.v1.ZitiManagementService/ListManagedIdentities"
	// ZitiManagementServiceResolveIdentityProcedure is the fully-qualified name of the
	// ZitiManagementService's ResolveIdentity RPC.
	ZitiManagementServiceResolveIdentityProcedure = "/agynio.api.ziti_management.v1.ZitiManagementService/ResolveIdentity"
	// ZitiManagementServiceRequestServiceIdentityProcedure is the fully-qualified name of the
	// ZitiManagementService's RequestServiceIdentity RPC.
	ZitiManagementServiceRequestServiceIdentityProcedure = "/agynio.api.ziti_management.v1.ZitiManagementService/RequestServiceIdentity"
	// ZitiManagementServiceExtendIdentityLeaseProcedure is the fully-qualified name of the
	// ZitiManagementService's ExtendIdentityLease RPC.
	ZitiManagementServiceExtendIdentityLeaseProcedure = "/agynio.api.ziti_management.v1.ZitiManagementService/ExtendIdentityLease"
	// ZitiManagementServiceCreateServicePolicyProcedure is the fully-qualified name of the
	// ZitiManagementService's CreateServicePolicy RPC.
	ZitiManagementServiceCreateServicePolicyProcedure = "/agynio.api.ziti_management.v1.ZitiManagementService/CreateServicePolicy"
	// ZitiManagementServiceDeleteServicePolicyProcedure is the fully-qualified name of the
	// ZitiManagementService's DeleteServicePolicy RPC.
	ZitiManagementServiceDeleteServicePolicyProcedure = "/agynio.api.ziti_management.v1.ZitiManagementService/DeleteServicePolicy"
	// ZitiManagementServiceDeleteServiceProcedure is the fully-qualified name of the
	// ZitiManagementService's DeleteService RPC.
	ZitiManagementServiceDeleteServiceProcedure = "/agynio.api.ziti_management.v1.ZitiManagementService/DeleteService"
	// ZitiManagementServiceCreateDeviceIdentityProcedure is the fully-qualified name of the
	// ZitiManagementService's CreateDeviceIdentity RPC.
	ZitiManagementServiceCreateDeviceIdentityProcedure = "/agynio.api.ziti_management.v1.ZitiManagementService/CreateDeviceIdentity"
	// ZitiManagementServiceDeleteDeviceIdentityProcedure is the fully-qualified name of the
	// ZitiManagementService's DeleteDeviceIdentity RPC.
	ZitiManagementServiceDeleteDeviceIdentityProcedure = "/agynio.api.ziti_management.v1.ZitiManagementService/DeleteDeviceIdentity"
)

// ZitiManagementServiceClient is a client for the
// agynio.api.ziti_management.v1.ZitiManagementService service.
type ZitiManagementServiceClient interface {
	// Orchestrator -> create OpenZiti identity for an agent, return enrollment JWT.
	CreateAgentIdentity(context.Context, *connect.Request[v1.CreateAgentIdentityRequest]) (*connect.Response[v1.CreateAgentIdentityResponse], error)
	// Apps Service -> create and enroll an OpenZiti identity for an app. If a previous
	// identity exists, deletes it first. Returns enrolled credentials.
	CreateAppIdentity(context.Context, *connect.Request[v1.CreateAppIdentityRequest]) (*connect.Response[v1.CreateAppIdentityResponse], error)
	// Runners Service, Apps Service -> create a per-runner or per-app OpenZiti service.
	CreateService(context.Context, *connect.Request[v1.CreateServiceRequest]) (*connect.Response[v1.CreateServiceResponse], error)
	// Orchestrator -> delete OpenZiti identity and its platform mapping.
	DeleteIdentity(context.Context, *connect.Request[v1.DeleteIdentityRequest]) (*connect.Response[v1.DeleteIdentityResponse], error)
	// Apps Service -> delete an app's OpenZiti identity and its associated service.
	// Looked up by platform identity_id.
	DeleteAppIdentity(context.Context, *connect.Request[v1.DeleteAppIdentityRequest]) (*connect.Response[v1.DeleteAppIdentityResponse], error)
	// Runners Service -> create and enroll an OpenZiti identity for a runner. If a previous
	// identity exists, deletes it first. Returns enrolled credentials.
	CreateRunnerIdentity(context.Context, *connect.Request[v1.CreateRunnerIdentityRequest]) (*connect.Response[v1.CreateRunnerIdentityResponse], error)
	// Runners Service -> delete a runner's OpenZiti identity and its associated service.
	// Looked up by platform identity_id.
	DeleteRunnerIdentity(context.Context, *connect.Request[v1.DeleteRunnerIdentityRequest]) (*connect.Response[v1.DeleteRunnerIdentityResponse], error)
	// Orchestrator -> list all platform-managed identities (orphan reconciliation).
	ListManagedIdentities(context.Context, *connect.Request[v1.ListManagedIdentitiesRequest]) (*connect.Response[v1.ListManagedIdentitiesResponse], error)
	// Gateway -> map OpenZiti identity ID to platform identity (hot path).
	ResolveIdentity(context.Context, *connect.Request[v1.ResolveIdentityRequest]) (*connect.Response[v1.ResolveIdentityResponse], error)
	// Infrastructure services (Gateway, Orchestrator, Runner) -> request an enrolled
	// OpenZiti identity for the calling service. Ziti Management creates the identity
	// on the Controller, enrolls it (generates key pair, submits CSR, receives cert),
	// and returns the enrolled identity to the caller.
	RequestServiceIdentity(context.Context, *connect.Request[v1.RequestServiceIdentityRequest]) (*connect.Response[v1.RequestServiceIdentityResponse], error)
	// Infrastructure services -> extend the lease on a service identity.
	// Called periodically by the service to prevent GC from deleting the identity.
	ExtendIdentityLease(context.Context, *connect.Request[v1.ExtendIdentityLeaseRequest]) (*connect.Response[v1.ExtendIdentityLeaseResponse], error)
	// Expose Service -> create a single OpenZiti service policy (Bind or Dial).
	// Returns the policy ID.
	CreateServicePolicy(context.Context, *connect.Request[v1.CreateServicePolicyRequest]) (*connect.Response[v1.CreateServicePolicyResponse], error)
	// Expose Service -> delete an OpenZiti service policy by ID.
	DeleteServicePolicy(context.Context, *connect.Request[v1.DeleteServicePolicyRequest]) (*connect.Response[v1.DeleteServicePolicyResponse], error)
	// Expose Service -> delete an OpenZiti service by ID.
	// Also deletes attached config objects.
	DeleteService(context.Context, *connect.Request[v1.DeleteServiceRequest]) (*connect.Response[v1.DeleteServiceResponse], error)
	// Users Service -> create an OpenZiti identity for a user device with
	// roleAttributes: ["devices"] and enrollment.ott: true.
	// Returns the identity ID and enrollment JWT.
	CreateDeviceIdentity(context.Context, *connect.Request[v1.CreateDeviceIdentityRequest]) (*connect.Response[v1.CreateDeviceIdentityResponse], error)
	// Users Service -> delete a device's OpenZiti identity.
	DeleteDeviceIdentity(context.Context, *connect.Request[v1.DeleteDeviceIdentityRequest]) (*connect.Response[v1.DeleteDeviceIdentityResponse], error)
}

// NewZitiManagementServiceClient constructs a client for the
// agynio.api.ziti_management.v1.ZitiManagementService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewZitiManagementServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ZitiManagementServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	zitiManagementServiceMethods := v1.File_agynio_api_ziti_management_v1_ziti_management_proto.Services().ByName("ZitiManagementService").Methods()
	return &zitiManagementServiceClient{
		createAgentIdentity: connect.NewClient[v1.CreateAgentIdentityRequest, v1.CreateAgentIdentityResponse](
			httpClient,
			baseURL+ZitiManagementServiceCreateAgentIdentityProcedure,
			connect.WithSchema(zitiManagementServiceMethods.ByName("CreateAgentIdentity")),
			connect.WithClientOptions(opts...),
		),
		createAppIdentity: connect.NewClient[v1.CreateAppIdentityRequest, v1.CreateAppIdentityResponse](
			httpClient,
			baseURL+ZitiManagementServiceCreateAppIdentityProcedure,
			connect.WithSchema(zitiManagementServiceMethods.ByName("CreateAppIdentity")),
			connect.WithClientOptions(opts...),
		),
		createService: connect.NewClient[v1.CreateServiceRequest, v1.CreateServiceResponse](
			httpClient,
			baseURL+ZitiManagementServiceCreateServiceProcedure,
			connect.WithSchema(zitiManagementServiceMethods.ByName("CreateService")),
			connect.WithClientOptions(opts...),
		),
		deleteIdentity: connect.NewClient[v1.DeleteIdentityRequest, v1.DeleteIdentityResponse](
			httpClient,
			baseURL+ZitiManagementServiceDeleteIdentityProcedure,
			connect.WithSchema(zitiManagementServiceMethods.ByName("DeleteIdentity")),
			connect.WithClientOptions(opts...),
		),
		deleteAppIdentity: connect.NewClient[v1.DeleteAppIdentityRequest, v1.DeleteAppIdentityResponse](
			httpClient,
			baseURL+ZitiManagementServiceDeleteAppIdentityProcedure,
			connect.WithSchema(zitiManagementServiceMethods.ByName("DeleteAppIdentity")),
			connect.WithClientOptions(opts...),
		),
		createRunnerIdentity: connect.NewClient[v1.CreateRunnerIdentityRequest, v1.CreateRunnerIdentityResponse](
			httpClient,
			baseURL+ZitiManagementServiceCreateRunnerIdentityProcedure,
			connect.WithSchema(zitiManagementServiceMethods.ByName("CreateRunnerIdentity")),
			connect.WithClientOptions(opts...),
		),
		deleteRunnerIdentity: connect.NewClient[v1.DeleteRunnerIdentityRequest, v1.DeleteRunnerIdentityResponse](
			httpClient,
			baseURL+ZitiManagementServiceDeleteRunnerIdentityProcedure,
			connect.WithSchema(zitiManagementServiceMethods.ByName("DeleteRunnerIdentity")),
			connect.WithClientOptions(opts...),
		),
		listManagedIdentities: connect.NewClient[v1.ListManagedIdentitiesRequest, v1.ListManagedIdentitiesResponse](
			httpClient,
			baseURL+ZitiManagementServiceListManagedIdentitiesProcedure,
			connect.WithSchema(zitiManagementServiceMethods.ByName("ListManagedIdentities")),
			connect.WithClientOptions(opts...),
		),
		resolveIdentity: connect.NewClient[v1.ResolveIdentityRequest, v1.ResolveIdentityResponse](
			httpClient,
			baseURL+ZitiManagementServiceResolveIdentityProcedure,
			connect.WithSchema(zitiManagementServiceMethods.ByName("ResolveIdentity")),
			connect.WithClientOptions(opts...),
		),
		requestServiceIdentity: connect.NewClient[v1.RequestServiceIdentityRequest, v1.RequestServiceIdentityResponse](
			httpClient,
			baseURL+ZitiManagementServiceRequestServiceIdentityProcedure,
			connect.WithSchema(zitiManagementServiceMethods.ByName("RequestServiceIdentity")),
			connect.WithClientOptions(opts...),
		),
		extendIdentityLease: connect.NewClient[v1.ExtendIdentityLeaseRequest, v1.ExtendIdentityLeaseResponse](
			httpClient,
			baseURL+ZitiManagementServiceExtendIdentityLeaseProcedure,
			connect.WithSchema(zitiManagementServiceMethods.ByName("ExtendIdentityLease")),
			connect.WithClientOptions(opts...),
		),
		createServicePolicy: connect.NewClient[v1.CreateServicePolicyRequest, v1.CreateServicePolicyResponse](
			httpClient,
			baseURL+ZitiManagementServiceCreateServicePolicyProcedure,
			connect.WithSchema(zitiManagementServiceMethods.ByName("CreateServicePolicy")),
			connect.WithClientOptions(opts...),
		),
		deleteServicePolicy: connect.NewClient[v1.DeleteServicePolicyRequest, v1.DeleteServicePolicyResponse](
			httpClient,
			baseURL+ZitiManagementServiceDeleteServicePolicyProcedure,
			connect.WithSchema(zitiManagementServiceMethods.ByName("DeleteServicePolicy")),
			connect.WithClientOptions(opts...),
		),
		deleteService: connect.NewClient[v1.DeleteServiceRequest, v1.DeleteServiceResponse](
			httpClient,
			baseURL+ZitiManagementServiceDeleteServiceProcedure,
			connect.WithSchema(zitiManagementServiceMethods.ByName("DeleteService")),
			connect.WithClientOptions(opts...),
		),
		createDeviceIdentity: connect.NewClient[v1.CreateDeviceIdentityRequest, v1.CreateDeviceIdentityResponse](
			httpClient,
			baseURL+ZitiManagementServiceCreateDeviceIdentityProcedure,
			connect.WithSchema(zitiManagementServiceMethods.ByName("CreateDeviceIdentity")),
			connect.WithClientOptions(opts...),
		),
		deleteDeviceIdentity: connect.NewClient[v1.DeleteDeviceIdentityRequest, v1.DeleteDeviceIdentityResponse](
			httpClient,
			baseURL+ZitiManagementServiceDeleteDeviceIdentityProcedure,
			connect.WithSchema(zitiManagementServiceMethods.ByName("DeleteDeviceIdentity")),
			connect.WithClientOptions(opts...),
		),
	}
}

// zitiManagementServiceClient implements ZitiManagementServiceClient.
type zitiManagementServiceClient struct {
	createAgentIdentity    *connect.Client[v1.CreateAgentIdentityRequest, v1.CreateAgentIdentityResponse]
	createAppIdentity      *connect.Client[v1.CreateAppIdentityRequest, v1.CreateAppIdentityResponse]
	createService          *connect.Client[v1.CreateServiceRequest, v1.CreateServiceResponse]
	deleteIdentity         *connect.Client[v1.DeleteIdentityRequest, v1.DeleteIdentityResponse]
	deleteAppIdentity      *connect.Client[v1.DeleteAppIdentityRequest, v1.DeleteAppIdentityResponse]
	createRunnerIdentity   *connect.Client[v1.CreateRunnerIdentityRequest, v1.CreateRunnerIdentityResponse]
	deleteRunnerIdentity   *connect.Client[v1.DeleteRunnerIdentityRequest, v1.DeleteRunnerIdentityResponse]
	listManagedIdentities  *connect.Client[v1.ListManagedIdentitiesRequest, v1.ListManagedIdentitiesResponse]
	resolveIdentity        *connect.Client[v1.ResolveIdentityRequest, v1.ResolveIdentityResponse]
	requestServiceIdentity *connect.Client[v1.RequestServiceIdentityRequest, v1.RequestServiceIdentityResponse]
	extendIdentityLease    *connect.Client[v1.ExtendIdentityLeaseRequest, v1.ExtendIdentityLeaseResponse]
	createServicePolicy    *connect.Client[v1.CreateServicePolicyRequest, v1.CreateServicePolicyResponse]
	deleteServicePolicy    *connect.Client[v1.DeleteServicePolicyRequest, v1.DeleteServicePolicyResponse]
	deleteService          *connect.Client[v1.DeleteServiceRequest, v1.DeleteServiceResponse]
	createDeviceIdentity   *connect.Client[v1.CreateDeviceIdentityRequest, v1.CreateDeviceIdentityResponse]
	deleteDeviceIdentity   *connect.Client[v1.DeleteDeviceIdentityRequest, v1.DeleteDeviceIdentityResponse]
}

// CreateAgentIdentity calls
// agynio.api.ziti_management.v1.ZitiManagementService.CreateAgentIdentity.
func (c *zitiManagementServiceClient) CreateAgentIdentity(ctx context.Context, req *connect.Request[v1.CreateAgentIdentityRequest]) (*connect.Response[v1.CreateAgentIdentityResponse], error) {
	return c.createAgentIdentity.CallUnary(ctx, req)
}

// CreateAppIdentity calls agynio.api.ziti_management.v1.ZitiManagementService.CreateAppIdentity.
func (c *zitiManagementServiceClient) CreateAppIdentity(ctx context.Context, req *connect.Request[v1.CreateAppIdentityRequest]) (*connect.Response[v1.CreateAppIdentityResponse], error) {
	return c.createAppIdentity.CallUnary(ctx, req)
}

// CreateService calls agynio.api.ziti_management.v1.ZitiManagementService.CreateService.
func (c *zitiManagementServiceClient) CreateService(ctx context.Context, req *connect.Request[v1.CreateServiceRequest]) (*connect.Response[v1.CreateServiceResponse], error) {
	return c.createService.CallUnary(ctx, req)
}

// DeleteIdentity calls agynio.api.ziti_management.v1.ZitiManagementService.DeleteIdentity.
func (c *zitiManagementServiceClient) DeleteIdentity(ctx context.Context, req *connect.Request[v1.DeleteIdentityRequest]) (*connect.Response[v1.DeleteIdentityResponse], error) {
	return c.deleteIdentity.CallUnary(ctx, req)
}

// DeleteAppIdentity calls agynio.api.ziti_management.v1.ZitiManagementService.DeleteAppIdentity.
func (c *zitiManagementServiceClient) DeleteAppIdentity(ctx context.Context, req *connect.Request[v1.DeleteAppIdentityRequest]) (*connect.Response[v1.DeleteAppIdentityResponse], error) {
	return c.deleteAppIdentity.CallUnary(ctx, req)
}

// CreateRunnerIdentity calls
// agynio.api.ziti_management.v1.ZitiManagementService.CreateRunnerIdentity.
func (c *zitiManagementServiceClient) CreateRunnerIdentity(ctx context.Context, req *connect.Request[v1.CreateRunnerIdentityRequest]) (*connect.Response[v1.CreateRunnerIdentityResponse], error) {
	return c.createRunnerIdentity.CallUnary(ctx, req)
}

// DeleteRunnerIdentity calls
// agynio.api.ziti_management.v1.ZitiManagementService.DeleteRunnerIdentity.
func (c *zitiManagementServiceClient) DeleteRunnerIdentity(ctx context.Context, req *connect.Request[v1.DeleteRunnerIdentityRequest]) (*connect.Response[v1.DeleteRunnerIdentityResponse], error) {
	return c.deleteRunnerIdentity.CallUnary(ctx, req)
}

// ListManagedIdentities calls
// agynio.api.ziti_management.v1.ZitiManagementService.ListManagedIdentities.
func (c *zitiManagementServiceClient) ListManagedIdentities(ctx context.Context, req *connect.Request[v1.ListManagedIdentitiesRequest]) (*connect.Response[v1.ListManagedIdentitiesResponse], error) {
	return c.listManagedIdentities.CallUnary(ctx, req)
}

// ResolveIdentity calls agynio.api.ziti_management.v1.ZitiManagementService.ResolveIdentity.
func (c *zitiManagementServiceClient) ResolveIdentity(ctx context.Context, req *connect.Request[v1.ResolveIdentityRequest]) (*connect.Response[v1.ResolveIdentityResponse], error) {
	return c.resolveIdentity.CallUnary(ctx, req)
}

// RequestServiceIdentity calls
// agynio.api.ziti_management.v1.ZitiManagementService.RequestServiceIdentity.
func (c *zitiManagementServiceClient) RequestServiceIdentity(ctx context.Context, req *connect.Request[v1.RequestServiceIdentityRequest]) (*connect.Response[v1.RequestServiceIdentityResponse], error) {
	return c.requestServiceIdentity.CallUnary(ctx, req)
}

// ExtendIdentityLease calls
// agynio.api.ziti_management.v1.ZitiManagementService.ExtendIdentityLease.
func (c *zitiManagementServiceClient) ExtendIdentityLease(ctx context.Context, req *connect.Request[v1.ExtendIdentityLeaseRequest]) (*connect.Response[v1.ExtendIdentityLeaseResponse], error) {
	return c.extendIdentityLease.CallUnary(ctx, req)
}

// CreateServicePolicy calls
// agynio.api.ziti_management.v1.ZitiManagementService.CreateServicePolicy.
func (c *zitiManagementServiceClient) CreateServicePolicy(ctx context.Context, req *connect.Request[v1.CreateServicePolicyRequest]) (*connect.Response[v1.CreateServicePolicyResponse], error) {
	return c.createServicePolicy.CallUnary(ctx, req)
}

// DeleteServicePolicy calls
// agynio.api.ziti_management.v1.ZitiManagementService.DeleteServicePolicy.
func (c *zitiManagementServiceClient) DeleteServicePolicy(ctx context.Context, req *connect.Request[v1.DeleteServicePolicyRequest]) (*connect.Response[v1.DeleteServicePolicyResponse], error) {
	return c.deleteServicePolicy.CallUnary(ctx, req)
}

// DeleteService calls agynio.api.ziti_management.v1.ZitiManagementService.DeleteService.
func (c *zitiManagementServiceClient) DeleteService(ctx context.Context, req *connect.Request[v1.DeleteServiceRequest]) (*connect.Response[v1.DeleteServiceResponse], error) {
	return c.deleteService.CallUnary(ctx, req)
}

// CreateDeviceIdentity calls
// agynio.api.ziti_management.v1.ZitiManagementService.CreateDeviceIdentity.
func (c *zitiManagementServiceClient) CreateDeviceIdentity(ctx context.Context, req *connect.Request[v1.CreateDeviceIdentityRequest]) (*connect.Response[v1.CreateDeviceIdentityResponse], error) {
	return c.createDeviceIdentity.CallUnary(ctx, req)
}

// DeleteDeviceIdentity calls
// agynio.api.ziti_management.v1.ZitiManagementService.DeleteDeviceIdentity.
func (c *zitiManagementServiceClient) DeleteDeviceIdentity(ctx context.Context, req *connect.Request[v1.DeleteDeviceIdentityRequest]) (*connect.Response[v1.DeleteDeviceIdentityResponse], error) {
	return c.deleteDeviceIdentity.CallUnary(ctx, req)
}

// ZitiManagementServiceHandler is an implementation of the
// agynio.api.ziti_management.v1.ZitiManagementService service.
type ZitiManagementServiceHandler interface {
	// Orchestrator -> create OpenZiti identity for an agent, return enrollment JWT.
	CreateAgentIdentity(context.Context, *connect.Request[v1.CreateAgentIdentityRequest]) (*connect.Response[v1.CreateAgentIdentityResponse], error)
	// Apps Service -> create and enroll an OpenZiti identity for an app. If a previous
	// identity exists, deletes it first. Returns enrolled credentials.
	CreateAppIdentity(context.Context, *connect.Request[v1.CreateAppIdentityRequest]) (*connect.Response[v1.CreateAppIdentityResponse], error)
	// Runners Service, Apps Service -> create a per-runner or per-app OpenZiti service.
	CreateService(context.Context, *connect.Request[v1.CreateServiceRequest]) (*connect.Response[v1.CreateServiceResponse], error)
	// Orchestrator -> delete OpenZiti identity and its platform mapping.
	DeleteIdentity(context.Context, *connect.Request[v1.DeleteIdentityRequest]) (*connect.Response[v1.DeleteIdentityResponse], error)
	// Apps Service -> delete an app's OpenZiti identity and its associated service.
	// Looked up by platform identity_id.
	DeleteAppIdentity(context.Context, *connect.Request[v1.DeleteAppIdentityRequest]) (*connect.Response[v1.DeleteAppIdentityResponse], error)
	// Runners Service -> create and enroll an OpenZiti identity for a runner. If a previous
	// identity exists, deletes it first. Returns enrolled credentials.
	CreateRunnerIdentity(context.Context, *connect.Request[v1.CreateRunnerIdentityRequest]) (*connect.Response[v1.CreateRunnerIdentityResponse], error)
	// Runners Service -> delete a runner's OpenZiti identity and its associated service.
	// Looked up by platform identity_id.
	DeleteRunnerIdentity(context.Context, *connect.Request[v1.DeleteRunnerIdentityRequest]) (*connect.Response[v1.DeleteRunnerIdentityResponse], error)
	// Orchestrator -> list all platform-managed identities (orphan reconciliation).
	ListManagedIdentities(context.Context, *connect.Request[v1.ListManagedIdentitiesRequest]) (*connect.Response[v1.ListManagedIdentitiesResponse], error)
	// Gateway -> map OpenZiti identity ID to platform identity (hot path).
	ResolveIdentity(context.Context, *connect.Request[v1.ResolveIdentityRequest]) (*connect.Response[v1.ResolveIdentityResponse], error)
	// Infrastructure services (Gateway, Orchestrator, Runner) -> request an enrolled
	// OpenZiti identity for the calling service. Ziti Management creates the identity
	// on the Controller, enrolls it (generates key pair, submits CSR, receives cert),
	// and returns the enrolled identity to the caller.
	RequestServiceIdentity(context.Context, *connect.Request[v1.RequestServiceIdentityRequest]) (*connect.Response[v1.RequestServiceIdentityResponse], error)
	// Infrastructure services -> extend the lease on a service identity.
	// Called periodically by the service to prevent GC from deleting the identity.
	ExtendIdentityLease(context.Context, *connect.Request[v1.ExtendIdentityLeaseRequest]) (*connect.Response[v1.ExtendIdentityLeaseResponse], error)
	// Expose Service -> create a single OpenZiti service policy (Bind or Dial).
	// Returns the policy ID.
	CreateServicePolicy(context.Context, *connect.Request[v1.CreateServicePolicyRequest]) (*connect.Response[v1.CreateServicePolicyResponse], error)
	// Expose Service -> delete an OpenZiti service policy by ID.
	DeleteServicePolicy(context.Context, *connect.Request[v1.DeleteServicePolicyRequest]) (*connect.Response[v1.DeleteServicePolicyResponse], error)
	// Expose Service -> delete an OpenZiti service by ID.
	// Also deletes attached config objects.
	DeleteService(context.Context, *connect.Request[v1.DeleteServiceRequest]) (*connect.Response[v1.DeleteServiceResponse], error)
	// Users Service -> create an OpenZiti identity for a user device with
	// roleAttributes: ["devices"] and enrollment.ott: true.
	// Returns the identity ID and enrollment JWT.
	CreateDeviceIdentity(context.Context, *connect.Request[v1.CreateDeviceIdentityRequest]) (*connect.Response[v1.CreateDeviceIdentityResponse], error)
	// Users Service -> delete a device's OpenZiti identity.
	DeleteDeviceIdentity(context.Context, *connect.Request[v1.DeleteDeviceIdentityRequest]) (*connect.Response[v1.DeleteDeviceIdentityResponse], error)
}

// NewZitiManagementServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewZitiManagementServiceHandler(svc ZitiManagementServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	zitiManagementServiceMethods := v1.File_agynio_api_ziti_management_v1_ziti_management_proto.Services().ByName("ZitiManagementService").Methods()
	zitiManagementServiceCreateAgentIdentityHandler := connect.NewUnaryHandler(
		ZitiManagementServiceCreateAgentIdentityProcedure,
		svc.CreateAgentIdentity,
		connect.WithSchema(zitiManagementServiceMethods.ByName("CreateAgentIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	zitiManagementServiceCreateAppIdentityHandler := connect.NewUnaryHandler(
		ZitiManagementServiceCreateAppIdentityProcedure,
		svc.CreateAppIdentity,
		connect.WithSchema(zitiManagementServiceMethods.ByName("CreateAppIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	zitiManagementServiceCreateServiceHandler := connect.NewUnaryHandler(
		ZitiManagementServiceCreateServiceProcedure,
		svc.CreateService,
		connect.WithSchema(zitiManagementServiceMethods.ByName("CreateService")),
		connect.WithHandlerOptions(opts...),
	)
	zitiManagementServiceDeleteIdentityHandler := connect.NewUnaryHandler(
		ZitiManagementServiceDeleteIdentityProcedure,
		svc.DeleteIdentity,
		connect.WithSchema(zitiManagementServiceMethods.ByName("DeleteIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	zitiManagementServiceDeleteAppIdentityHandler := connect.NewUnaryHandler(
		ZitiManagementServiceDeleteAppIdentityProcedure,
		svc.DeleteAppIdentity,
		connect.WithSchema(zitiManagementServiceMethods.ByName("DeleteAppIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	zitiManagementServiceCreateRunnerIdentityHandler := connect.NewUnaryHandler(
		ZitiManagementServiceCreateRunnerIdentityProcedure,
		svc.CreateRunnerIdentity,
		connect.WithSchema(zitiManagementServiceMethods.ByName("CreateRunnerIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	zitiManagementServiceDeleteRunnerIdentityHandler := connect.NewUnaryHandler(
		ZitiManagementServiceDeleteRunnerIdentityProcedure,
		svc.DeleteRunnerIdentity,
		connect.WithSchema(zitiManagementServiceMethods.ByName("DeleteRunnerIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	zitiManagementServiceListManagedIdentitiesHandler := connect.NewUnaryHandler(
		ZitiManagementServiceListManagedIdentitiesProcedure,
		svc.ListManagedIdentities,
		connect.WithSchema(zitiManagementServiceMethods.ByName("ListManagedIdentities")),
		connect.WithHandlerOptions(opts...),
	)
	zitiManagementServiceResolveIdentityHandler := connect.NewUnaryHandler(
		ZitiManagementServiceResolveIdentityProcedure,
		svc.ResolveIdentity,
		connect.WithSchema(zitiManagementServiceMethods.ByName("ResolveIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	zitiManagementServiceRequestServiceIdentityHandler := connect.NewUnaryHandler(
		ZitiManagementServiceRequestServiceIdentityProcedure,
		svc.RequestServiceIdentity,
		connect.WithSchema(zitiManagementServiceMethods.ByName("RequestServiceIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	zitiManagementServiceExtendIdentityLeaseHandler := connect.NewUnaryHandler(
		ZitiManagementServiceExtendIdentityLeaseProcedure,
		svc.ExtendIdentityLease,
		connect.WithSchema(zitiManagementServiceMethods.ByName("ExtendIdentityLease")),
		connect.WithHandlerOptions(opts...),
	)
	zitiManagementServiceCreateServicePolicyHandler := connect.NewUnaryHandler(
		ZitiManagementServiceCreateServicePolicyProcedure,
		svc.CreateServicePolicy,
		connect.WithSchema(zitiManagementServiceMethods.ByName("CreateServicePolicy")),
		connect.WithHandlerOptions(opts...),
	)
	zitiManagementServiceDeleteServicePolicyHandler := connect.NewUnaryHandler(
		ZitiManagementServiceDeleteServicePolicyProcedure,
		svc.DeleteServicePolicy,
		connect.WithSchema(zitiManagementServiceMethods.ByName("DeleteServicePolicy")),
		connect.WithHandlerOptions(opts...),
	)
	zitiManagementServiceDeleteServiceHandler := connect.NewUnaryHandler(
		ZitiManagementServiceDeleteServiceProcedure,
		svc.DeleteService,
		connect.WithSchema(zitiManagementServiceMethods.ByName("DeleteService")),
		connect.WithHandlerOptions(opts...),
	)
	zitiManagementServiceCreateDeviceIdentityHandler := connect.NewUnaryHandler(
		ZitiManagementServiceCreateDeviceIdentityProcedure,
		svc.CreateDeviceIdentity,
		connect.WithSchema(zitiManagementServiceMethods.ByName("CreateDeviceIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	zitiManagementServiceDeleteDeviceIdentityHandler := connect.NewUnaryHandler(
		ZitiManagementServiceDeleteDeviceIdentityProcedure,
		svc.DeleteDeviceIdentity,
		connect.WithSchema(zitiManagementServiceMethods.ByName("DeleteDeviceIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agynio.api.ziti_management.v1.ZitiManagementService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ZitiManagementServiceCreateAgentIdentityProcedure:
			zitiManagementServiceCreateAgentIdentityHandler.ServeHTTP(w, r)
		case ZitiManagementServiceCreateAppIdentityProcedure:
			zitiManagementServiceCreateAppIdentityHandler.ServeHTTP(w, r)
		case ZitiManagementServiceCreateServiceProcedure:
			zitiManagementServiceCreateServiceHandler.ServeHTTP(w, r)
		case ZitiManagementServiceDeleteIdentityProcedure:
			zitiManagementServiceDeleteIdentityHandler.ServeHTTP(w, r)
		case ZitiManagementServiceDeleteAppIdentityProcedure:
			zitiManagementServiceDeleteAppIdentityHandler.ServeHTTP(w, r)
		case ZitiManagementServiceCreateRunnerIdentityProcedure:
			zitiManagementServiceCreateRunnerIdentityHandler.ServeHTTP(w, r)
		case ZitiManagementServiceDeleteRunnerIdentityProcedure:
			zitiManagementServiceDeleteRunnerIdentityHandler.ServeHTTP(w, r)
		case ZitiManagementServiceListManagedIdentitiesProcedure:
			zitiManagementServiceListManagedIdentitiesHandler.ServeHTTP(w, r)
		case ZitiManagementServiceResolveIdentityProcedure:
			zitiManagementServiceResolveIdentityHandler.ServeHTTP(w, r)
		case ZitiManagementServiceRequestServiceIdentityProcedure:
			zitiManagementServiceRequestServiceIdentityHandler.ServeHTTP(w, r)
		case ZitiManagementServiceExtendIdentityLeaseProcedure:
			zitiManagementServiceExtendIdentityLeaseHandler.ServeHTTP(w, r)
		case ZitiManagementServiceCreateServicePolicyProcedure:
			zitiManagementServiceCreateServicePolicyHandler.ServeHTTP(w, r)
		case ZitiManagementServiceDeleteServicePolicyProcedure:
			zitiManagementServiceDeleteServicePolicyHandler.ServeHTTP(w, r)
		case ZitiManagementServiceDeleteServiceProcedure:
			zitiManagementServiceDeleteServiceHandler.ServeHTTP(w, r)
		case ZitiManagementServiceCreateDeviceIdentityProcedure:
			zitiManagementServiceCreateDeviceIdentityHandler.ServeHTTP(w, r)
		case ZitiManagementServiceDeleteDeviceIdentityProcedure:
			zitiManagementServiceDeleteDeviceIdentityHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedZitiManagementServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedZitiManagementServiceHandler struct{}

func (UnimplementedZitiManagementServiceHandler) CreateAgentIdentity(context.Context, *connect.Request[v1.CreateAgentIdentityRequest]) (*connect.Response[v1.CreateAgentIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.ziti_management.v1.ZitiManagementService.CreateAgentIdentity is not implemented"))
}

func (UnimplementedZitiManagementServiceHandler) CreateAppIdentity(context.Context, *connect.Request[v1.CreateAppIdentityRequest]) (*connect.Response[v1.CreateAppIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.ziti_management.v1.ZitiManagementService.CreateAppIdentity is not implemented"))
}

func (UnimplementedZitiManagementServiceHandler) CreateService(context.Context, *connect.Request[v1.CreateServiceRequest]) (*connect.Response[v1.CreateServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.ziti_management.v1.ZitiManagementService.CreateService is not implemented"))
}

func (UnimplementedZitiManagementServiceHandler) DeleteIdentity(context.Context, *connect.Request[v1.DeleteIdentityRequest]) (*connect.Response[v1.DeleteIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.ziti_management.v1.ZitiManagementService.DeleteIdentity is not implemented"))
}

func (UnimplementedZitiManagementServiceHandler) DeleteAppIdentity(context.Context, *connect.Request[v1.DeleteAppIdentityRequest]) (*connect.Response[v1.DeleteAppIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.ziti_management.v1.ZitiManagementService.DeleteAppIdentity is not implemented"))
}

func (UnimplementedZitiManagementServiceHandler) CreateRunnerIdentity(context.Context, *connect.Request[v1.CreateRunnerIdentityRequest]) (*connect.Response[v1.CreateRunnerIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.ziti_management.v1.ZitiManagementService.CreateRunnerIdentity is not implemented"))
}

func (UnimplementedZitiManagementServiceHandler) DeleteRunnerIdentity(context.Context, *connect.Request[v1.DeleteRunnerIdentityRequest]) (*connect.Response[v1.DeleteRunnerIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.ziti_management.v1.ZitiManagementService.DeleteRunnerIdentity is not implemented"))
}

func (UnimplementedZitiManagementServiceHandler) ListManagedIdentities(context.Context, *connect.Request[v1.ListManagedIdentitiesRequest]) (*connect.Response[v1.ListManagedIdentitiesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.ziti_management.v1.ZitiManagementService.ListManagedIdentities is not implemented"))
}

func (UnimplementedZitiManagementServiceHandler) ResolveIdentity(context.Context, *connect.Request[v1.ResolveIdentityRequest]) (*connect.Response[v1.ResolveIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.ziti_management.v1.ZitiManagementService.ResolveIdentity is not implemented"))
}

func (UnimplementedZitiManagementServiceHandler) RequestServiceIdentity(context.Context, *connect.Request[v1.RequestServiceIdentityRequest]) (*connect.Response[v1.RequestServiceIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.ziti_management.v1.ZitiManagementService.RequestServiceIdentity is not implemented"))
}

func (UnimplementedZitiManagementServiceHandler) ExtendIdentityLease(context.Context, *connect.Request[v1.ExtendIdentityLeaseRequest]) (*connect.Response[v1.ExtendIdentityLeaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.ziti_management.v1.ZitiManagementService.ExtendIdentityLease is not implemented"))
}

func (UnimplementedZitiManagementServiceHandler) CreateServicePolicy(context.Context, *connect.Request[v1.CreateServicePolicyRequest]) (*connect.Response[v1.CreateServicePolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.ziti_management.v1.ZitiManagementService.CreateServicePolicy is not implemented"))
}

func (UnimplementedZitiManagementServiceHandler) DeleteServicePolicy(context.Context, *connect.Request[v1.DeleteServicePolicyRequest]) (*connect.Response[v1.DeleteServicePolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.ziti_management.v1.ZitiManagementService.DeleteServicePolicy is not implemented"))
}

func (UnimplementedZitiManagementServiceHandler) DeleteService(context.Context, *connect.Request[v1.DeleteServiceRequest]) (*connect.Response[v1.DeleteServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.ziti_management.v1.ZitiManagementService.DeleteService is not implemented"))
}

func (UnimplementedZitiManagementServiceHandler) CreateDeviceIdentity(context.Context, *connect.Request[v1.CreateDeviceIdentityRequest]) (*connect.Response[v1.CreateDeviceIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.ziti_management.v1.ZitiManagementService.CreateDeviceIdentity is not implemented"))
}

func (UnimplementedZitiManagementServiceHandler) DeleteDeviceIdentity(context.Context, *connect.Request[v1.DeleteDeviceIdentityRequest]) (*connect.Response[v1.DeleteDeviceIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agynio.api.ziti_management.v1.ZitiManagementService.DeleteDeviceIdentity is not implemented"))
}
