// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agynio/api/files/v1/files.proto

package filesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadFileRequest_Metadata
	//	*UploadFileRequest_Chunk
	Payload       isUploadFileRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_files_v1_files_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetPayload() isUploadFileRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadFileRequest) GetMetadata() *UploadFileMetadata {
	if x != nil {
		if x, ok := x.Payload.(*UploadFileRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadFileRequest) GetChunk() *UploadFileChunk {
	if x != nil {
		if x, ok := x.Payload.(*UploadFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadFileRequest_Payload interface {
	isUploadFileRequest_Payload()
}

type UploadFileRequest_Metadata struct {
	Metadata *UploadFileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadFileRequest_Chunk struct {
	Chunk *UploadFileChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadFileRequest_Metadata) isUploadFileRequest_Payload() {}

func (*UploadFileRequest_Chunk) isUploadFileRequest_Payload() {}

type UploadFileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileMetadata) Reset() {
	*x = UploadFileMetadata{}
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileMetadata) ProtoMessage() {}

func (x *UploadFileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileMetadata.ProtoReflect.Descriptor instead.
func (*UploadFileMetadata) Descriptor() ([]byte, []int) {
	return file_agynio_api_files_v1_files_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadFileMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadFileMetadata) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type UploadFileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileChunk) Reset() {
	*x = UploadFileChunk{}
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileChunk) ProtoMessage() {}

func (x *UploadFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileChunk.ProtoReflect.Descriptor instead.
func (*UploadFileChunk) Descriptor() ([]byte, []int) {
	return file_agynio_api_files_v1_files_proto_rawDescGZIP(), []int{2}
}

func (x *UploadFileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_files_v1_files_proto_rawDescGZIP(), []int{3}
}

func (x *UploadFileResponse) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type GetFileMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileMetadataRequest) Reset() {
	*x = GetFileMetadataRequest{}
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetadataRequest) ProtoMessage() {}

func (x *GetFileMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetFileMetadataRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_files_v1_files_proto_rawDescGZIP(), []int{4}
}

func (x *GetFileMetadataRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetFileMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileMetadataResponse) Reset() {
	*x = GetFileMetadataResponse{}
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetadataResponse) ProtoMessage() {}

func (x *GetFileMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetFileMetadataResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_files_v1_files_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileMetadataResponse) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type GetDownloadUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Expiry        *durationpb.Duration   `protobuf:"bytes,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlRequest) Reset() {
	*x = GetDownloadUrlRequest{}
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlRequest) ProtoMessage() {}

func (x *GetDownloadUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_files_v1_files_proto_rawDescGZIP(), []int{6}
}

func (x *GetDownloadUrlRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GetDownloadUrlRequest) GetExpiry() *durationpb.Duration {
	if x != nil {
		return x.Expiry
	}
	return nil
}

type GetDownloadUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlResponse) Reset() {
	*x = GetDownloadUrlResponse{}
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlResponse) ProtoMessage() {}

func (x *GetDownloadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_files_v1_files_proto_rawDescGZIP(), []int{7}
}

func (x *GetDownloadUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetDownloadUrlResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type GetFileContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileContentRequest) Reset() {
	*x = GetFileContentRequest{}
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileContentRequest) ProtoMessage() {}

func (x *GetFileContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileContentRequest.ProtoReflect.Descriptor instead.
func (*GetFileContentRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_files_v1_files_proto_rawDescGZIP(), []int{8}
}

func (x *GetFileContentRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetFileContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkData     []byte                 `protobuf:"bytes,1,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileContentResponse) Reset() {
	*x = GetFileContentResponse{}
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileContentResponse) ProtoMessage() {}

func (x *GetFileContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileContentResponse.ProtoReflect.Descriptor instead.
func (*GetFileContentResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_files_v1_files_proto_rawDescGZIP(), []int{9}
}

func (x *GetFileContentResponse) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_files_v1_files_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_agynio_api_files_v1_files_proto_rawDescGZIP(), []int{10}
}

func (x *FileInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_agynio_api_files_v1_files_proto protoreflect.FileDescriptor

const file_agynio_api_files_v1_files_proto_rawDesc = "" +
	"\n" +
	"\x1fagynio/api/files/v1/files.proto\x12\x13agynio.api.files.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x01\n" +
	"\x11UploadFileRequest\x12E\n" +
	"\bmetadata\x18\x01 \x01(\v2'.agynio.api.files.v1.UploadFileMetadataH\x00R\bmetadata\x12<\n" +
	"\x05chunk\x18\x02 \x01(\v2$.agynio.api.files.v1.UploadFileChunkH\x00R\x05chunkB\t\n" +
	"\apayload\"r\n" +
	"\x12UploadFileMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\"%\n" +
	"\x0fUploadFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"G\n" +
	"\x12UploadFileResponse\x121\n" +
	"\x04file\x18\x01 \x01(\v2\x1d.agynio.api.files.v1.FileInfoR\x04file\"1\n" +
	"\x16GetFileMetadataRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"L\n" +
	"\x17GetFileMetadataResponse\x121\n" +
	"\x04file\x18\x01 \x01(\v2\x1d.agynio.api.files.v1.FileInfoR\x04file\"c\n" +
	"\x15GetDownloadUrlRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x121\n" +
	"\x06expiry\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x06expiry\"e\n" +
	"\x16GetDownloadUrlResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"0\n" +
	"\x15GetFileContentRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"7\n" +
	"\x16GetFileContentResponse\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x01 \x01(\fR\tchunkData\"\xb3\x01\n" +
	"\bFileInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xb5\x03\n" +
	"\fFilesService\x12_\n" +
	"\n" +
	"UploadFile\x12&.agynio.api.files.v1.UploadFileRequest\x1a'.agynio.api.files.v1.UploadFileResponse(\x01\x12l\n" +
	"\x0fGetFileMetadata\x12+.agynio.api.files.v1.GetFileMetadataRequest\x1a,.agynio.api.files.v1.GetFileMetadataResponse\x12i\n" +
	"\x0eGetDownloadUrl\x12*.agynio.api.files.v1.GetDownloadUrlRequest\x1a+.agynio.api.files.v1.GetDownloadUrlResponse\x12k\n" +
	"\x0eGetFileContent\x12*.agynio.api.files.v1.GetFileContentRequest\x1a+.agynio.api.files.v1.GetFileContentResponse0\x01B\xde\x01\n" +
	"\x17com.agynio.api.files.v1B\n" +
	"FilesProtoP\x01ZHgithub.com/agynio/e2e/suites/go-core/.gen/go/agynio/api/files/v1;filesv1\xa2\x02\x03AAF\xaa\x02\x13Agynio.Api.Files.V1\xca\x02\x13Agynio\\Api\\Files\\V1\xe2\x02\x1fAgynio\\Api\\Files\\V1\\GPBMetadata\xea\x02\x16Agynio::Api::Files::V1b\x06proto3"

var (
	file_agynio_api_files_v1_files_proto_rawDescOnce sync.Once
	file_agynio_api_files_v1_files_proto_rawDescData []byte
)

func file_agynio_api_files_v1_files_proto_rawDescGZIP() []byte {
	file_agynio_api_files_v1_files_proto_rawDescOnce.Do(func() {
		file_agynio_api_files_v1_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agynio_api_files_v1_files_proto_rawDesc), len(file_agynio_api_files_v1_files_proto_rawDesc)))
	})
	return file_agynio_api_files_v1_files_proto_rawDescData
}

var file_agynio_api_files_v1_files_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_agynio_api_files_v1_files_proto_goTypes = []any{
	(*UploadFileRequest)(nil),       // 0: agynio.api.files.v1.UploadFileRequest
	(*UploadFileMetadata)(nil),      // 1: agynio.api.files.v1.UploadFileMetadata
	(*UploadFileChunk)(nil),         // 2: agynio.api.files.v1.UploadFileChunk
	(*UploadFileResponse)(nil),      // 3: agynio.api.files.v1.UploadFileResponse
	(*GetFileMetadataRequest)(nil),  // 4: agynio.api.files.v1.GetFileMetadataRequest
	(*GetFileMetadataResponse)(nil), // 5: agynio.api.files.v1.GetFileMetadataResponse
	(*GetDownloadUrlRequest)(nil),   // 6: agynio.api.files.v1.GetDownloadUrlRequest
	(*GetDownloadUrlResponse)(nil),  // 7: agynio.api.files.v1.GetDownloadUrlResponse
	(*GetFileContentRequest)(nil),   // 8: agynio.api.files.v1.GetFileContentRequest
	(*GetFileContentResponse)(nil),  // 9: agynio.api.files.v1.GetFileContentResponse
	(*FileInfo)(nil),                // 10: agynio.api.files.v1.FileInfo
	(*durationpb.Duration)(nil),     // 11: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
}
var file_agynio_api_files_v1_files_proto_depIdxs = []int32{
	1,  // 0: agynio.api.files.v1.UploadFileRequest.metadata:type_name -> agynio.api.files.v1.UploadFileMetadata
	2,  // 1: agynio.api.files.v1.UploadFileRequest.chunk:type_name -> agynio.api.files.v1.UploadFileChunk
	10, // 2: agynio.api.files.v1.UploadFileResponse.file:type_name -> agynio.api.files.v1.FileInfo
	10, // 3: agynio.api.files.v1.GetFileMetadataResponse.file:type_name -> agynio.api.files.v1.FileInfo
	11, // 4: agynio.api.files.v1.GetDownloadUrlRequest.expiry:type_name -> google.protobuf.Duration
	12, // 5: agynio.api.files.v1.GetDownloadUrlResponse.expires_at:type_name -> google.protobuf.Timestamp
	12, // 6: agynio.api.files.v1.FileInfo.created_at:type_name -> google.protobuf.Timestamp
	0,  // 7: agynio.api.files.v1.FilesService.UploadFile:input_type -> agynio.api.files.v1.UploadFileRequest
	4,  // 8: agynio.api.files.v1.FilesService.GetFileMetadata:input_type -> agynio.api.files.v1.GetFileMetadataRequest
	6,  // 9: agynio.api.files.v1.FilesService.GetDownloadUrl:input_type -> agynio.api.files.v1.GetDownloadUrlRequest
	8,  // 10: agynio.api.files.v1.FilesService.GetFileContent:input_type -> agynio.api.files.v1.GetFileContentRequest
	3,  // 11: agynio.api.files.v1.FilesService.UploadFile:output_type -> agynio.api.files.v1.UploadFileResponse
	5,  // 12: agynio.api.files.v1.FilesService.GetFileMetadata:output_type -> agynio.api.files.v1.GetFileMetadataResponse
	7,  // 13: agynio.api.files.v1.FilesService.GetDownloadUrl:output_type -> agynio.api.files.v1.GetDownloadUrlResponse
	9,  // 14: agynio.api.files.v1.FilesService.GetFileContent:output_type -> agynio.api.files.v1.GetFileContentResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_agynio_api_files_v1_files_proto_init() }
func file_agynio_api_files_v1_files_proto_init() {
	if File_agynio_api_files_v1_files_proto != nil {
		return
	}
	file_agynio_api_files_v1_files_proto_msgTypes[0].OneofWrappers = []any{
		(*UploadFileRequest_Metadata)(nil),
		(*UploadFileRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agynio_api_files_v1_files_proto_rawDesc), len(file_agynio_api_files_v1_files_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agynio_api_files_v1_files_proto_goTypes,
		DependencyIndexes: file_agynio_api_files_v1_files_proto_depIdxs,
		MessageInfos:      file_agynio_api_files_v1_files_proto_msgTypes,
	}.Build()
	File_agynio_api_files_v1_files_proto = out.File
	file_agynio_api_files_v1_files_proto_goTypes = nil
	file_agynio_api_files_v1_files_proto_depIdxs = nil
}
